### ISSUE TITLE
Click outside logic is broken for Popover in Gatsby

### ISSUE THREAD

**Issue by marcobusemann** [tailwindlabs/headlessui#1007]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.4.2

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/headless-popover-gatsby-doctorderek-dep-versions-forked-1lwhn?file=/src/pages/index.js

**Describe your issue**

Within our Gatsby project, the click outside logic for Popover's is not working properly. The Popover is closed If you click somewhere inside of it. 
Solutions described [here](https://github.com/tailwindlabs/headlessui/issues/283) are working (tabIndex={-1}) but I think this should be solved in headlessui instead.

**Comment by vannyle** [comment]
I have the same issue with the click outside logic with Gatsby project, this workaround `tabIndex={-1}` solved the problem. but it doesn't look like a proper solution.
Also, I have tried using `npm install @headlessui/react@dev`, which was recommended [here](https://github.com/tailwindlabs/headlessui/issues/283#issuecomment-938665332), but it doesn't work. Has anyone already tried this version?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed a strange error but the reason why this is happening is because in the Popover we have some logic where we say "If the focus leaves the Popover, then close the Popover". This is useful and needed so that if you are going through a list of menu's (e.g.: https://tailwindui.com/components/ecommerce/components/store-navigation#component-05d207688239bbe040029b5bfa5ddf92) then when you `<tab>` outside of the Popover that it closes automatically.

The reason it is happening on in Gatsby projects is because Gatsby has this at the top:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1834413/156356817-0f31c4e8-2d33-449c-8d69-17330d5be1a2.png">

```html
<div tabindex="-1" id="gatsby-focus-wrapper" style="outline: none;">
  <!-- All of your contents -->
</div>
``` 

This means that when you click inside the Popover, that we actually move focus to that `gatsby-focus-wrapper`. Since this is located _outside_ of the Popover, it means that we will close the Popover.

For now to prevent this behaviour, what you can do is apply a `tabIndex={-1}` to the `Popover.Panel`. That way, we keep the focus inside the Popover and therefore it won't close.
