### ISSUE TITLE
Typeahead does not follow the WAI-ARIA spec when repeatedly typing a character

### ISSUE THREAD

**Issue by rgossiaux** [tailwindlabs/headlessui#1046]
A user reported this to my Svelte port and it also affects the upstream repo:

> The WAI-ARIA spec for Listbox mentions (emphasis mine):
> 
> > Type a character: focus moves to the **next** item with a name that starts with the typed character.
> 
> However, as reported by a user on Reddit, Headless UI does not do that; instead, we search for the **first** item with a name that starts with the typed character. You can see this in action on https://headlessui.dev/react/menu by repeatedly typing the letter d (with pauses in between). This affects Listbox and Menu both.

The React Listbox bug, for example, is here: https://github.com/tailwindlabs/headlessui/blob/1affad12714ae831fce3f20d276a02682d255514/packages/%40headlessui-react/src/components/listbox/listbox.tsx#L134

Instead of always calling `findIndex` on the entire list of `options`, we should first search only for `options` later than the current `activeOptionIndex`, and only then search from the beginning.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1051, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
