### ISSUE TITLE
Production ready and backward compatibility 

### ISSUE THREAD

**Issue by nouman91** [tailwindlabs/headlessui#107]
Thank you for this amazing library and for the awesome concept as well

I am planning to adopt it into a really complex project and planning on waiting for new releases. I have one question though Are these components production ready? And will you be providing backward compatibility?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You can already use it in production. There are some features that we didn't implement yet. For example, the `Menu` component doesn't work in a `Menu Bar` yet. You can use multiple Menu's but you won't have the expected behaviour of a menu bar as described in https://www.w3.org/TR/wai-aria-practices-1.2/#menu
For the Listbox component we didn't implement multiple values yet.
Apart from those 'missing' features we tried to come up with an API to make sure that we don't have to change a lot. I can't guarantee that we never change some parts, but if we do then we will provide upgrade guides.

We came up with a good public API for the Menu, Listbox and Switch components. We are probably going to use the same API in the Transition component. This means that there might be a breaking change for the Transition component. Note that this is a component in the React version of Headless UI so the Vue version won't be affected.

The consistent API I'm talking about:

1. Each component can render a default component. For example a `<Menu.Button />` will render a `button` by default.
2. Each component can render a different component if you want: `<Menu.Button as={MyButton}" />`.
3. All props that we don't control (e.g.: we do control props like `id` or `aria-*`) are forwarded to the actual DOM node.
4. When a component renders a fragment `<Menu.Button as={React.Fragment}><button /></Menu.Button>` then all the properties are forwarded on the only child. (The equivalent in Vue is `<MenuButton as="template"><button /></MenuButton>`)
5. Components can also use a render prop `<Menu.Button>{(data) => <button />}</Menu.Button>`, each component can expose some data for example `{ open }` to get the state of the menu. (The equivalent in Vue is `<MenuButton v-slot="data"></MenuButton>`)

But all of this is documented as well. 
Does this answer your question?

**Comment by nouman91** [comment]
Thank you for amazing detailed response. Yes it definitely clears out some of the major concerns. I know its gradual activity and things will change it the future but I hope there will be a migration plan as well.

I also would love to contribute in anyway shape or form. I have been advocate of headless pattern for quite sometime nice to see this taking shape.

**Comment by RobinMalfait** [comment]
Hey! Regarding the contributions I want to link to this comment from Adam: https://github.com/tailwindlabs/headlessui/issues/58#issuecomment-704398729
