### ISSUE TITLE
[BUG] Using popover with as="a" causes panel to close only after (Gatsby)

### ISSUE THREAD

**Issue by tudor2004** [tailwindlabs/headlessui#1073]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.4.3

**What browser are you using?**

Chrome

**Reproduction URL**

[Gatsby minimal setup with headless popover](https://github.com/tudor2004/gatsby-headless-popover-bug/blob/main/src/pages/index.js)

**Describe your issue**

There is a strange bug that causes the popover panel to reopen once you click on the Popover.Button in Gatsby. This happens only when the Popover.Button component is defined with an "as" property with value of "a" and the Popover.Panel includes elements of type "button". 
You can reproduce it like this: 
1. Click on the Popover.Button element so that the panel opens
2. Click on one of the buttons inside the panel
3. Click again on the Popover.Button element so that the panel closes 
4.   -> the panel will close and than quickly reopens by itself. Now you have to click again the button in order to close it. 

![headless-popover-bug](https://user-images.githubusercontent.com/2884281/151656240-352de9cc-fded-4b78-9f70-b0f6dc35ef5a.gif)

```
import React from "react"

import { Popover } from "@headlessui/react"

export default function Home() {
  return (
    <div>
      <Popover>
        {({ open }) => (
          <>
            <Popover.Button as="a">
              <span>Solutions</span>
            </Popover.Button>

            <Popover.Panel tabIndex={-1}>
              <div>
                <button type="button">First button</button>
                <button type="button">Second button</button>
              </div>
            </Popover.Panel>
          </>
        )}
      </Popover>
    </div>
  )
}
```

**Comment by adamwathan** [comment]
Hey! Can you explain why you want to make the popover button an `a` tag? That feels semantically incorrect, shouldn't be an `a` tag unless there's an `href` and it's actually meant to link somewhere, but here it's just meant to open the popover.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I agree that semantically speaking it is a bit odd to use an `as="a`. Typically you probably want to use the `as=""` prop for like a styled variant. E.g.: `<Popover.Button as={StyledButton} />` or if you want want to swap a `div` for as `span` to make styling easier. 

That said, this strange behaviour is now fixed in the latest insiders version, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
