### ISSUE TITLE
Transition.Child Element Unmounts Before Parent, Tips for Working With Children?

### ISSUE THREAD

**Issue by mikehawkfish** [tailwindlabs/headlessui#108]
Hey Tailwind Team,

I'm struggling with implementing `Transition.Child` elements and could use your help. Either there is a bug, or my mental model for working with children is wrong and could use some correcting.

**A child transition currently unmounts before the parent**. Is that intended? 

Here's a fork of your Code Sandbox showing a child unmounting before the parent: https://codesandbox.io/s/headlessuireact-menu-example-forked-nzr2p?file=/src/App.js:2169-2305

Can you help me understand how to properly use `Transition.Child`?. 

Say the parent Transition has an `opacity` transition, and I want to delay a child opacity transitioning, I'm running into a lot of headache because it's not working the way I expect. For example, I would expect the parent transition to apply to all of it's children, even if the child doesn't have a leave animation set. If the child doesn't have a `leave` set, it immediately unmounts.

Am I using it the wrong way? Should I be using the `Parent/Child` only to handle the `show` prop for it's children?

Thanks!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

> A child transition currently unmounts before the parent. Is that intended?

Yep this is intended. The idea is that every `Transition.Child` will delay the unmounting of a parent `Transition.Child` or a parent `Transition`. If you want to decouple those items then you can use a `Transition` directly.

> For example, I would expect the parent transition to apply to all of it's children, even if the child doesn't have a leave animation set.

Do you mean that you would expect when you have `<Transition leave="some-class" />` that a nested `<Transition.Child />` also gets this `some-class` on leave? Because that's not how it works. The relation between the 2 is that `Transition` waits for all `Transition.Child` components. And a `Transition.Child` component automatically "inherits" the `show` prop via context.

> Am I using it the wrong way? Should I be using the Parent/Child only to handle the show prop for it's children?

Yep, it's mainly for the `show` prop!

---

Could you explain what the expected result should be in that codesandbox? Or could you create a sandbox where you have something that might not work + expected result?

**Comment by mikehawkfish** [comment]
@RobinMalfait Hey thanks again for your help! This makes sense and I see where I went wrong.

I saw the example from the docs and thought I could use it for the `.Child` elements to inherit the parent transitions. From your answer, that's not the intended usecase and it's only to access the `show` prop.

I'm having trouble thinking of a use with Child elements since it always unmounts first but it seems like a good rule of thumb is to use `Transition` until I need to share `show`.
