### ISSUE TITLE
Un-control `tabIndex` when applicable components are static

### ISSUE THREAD

**Issue by realStandal** [tailwindlabs/headlessui#1097]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

`v1.4.3`

**What browser are you using?**

Edge `v98.0.1108.43`

**Reproduction URL**

[Stackblitz](https://stackblitz.com/edit/react-ts-cupyec?file=index.tsx)

> Inspect Element > Notice the `tabindex` value of the element associated with the `Menu.Items` component.
>
> Instead of being the expected `-1` it is the `0` "controlled" by HeadlessUI.

**Describe your issue**

When wanting to not rely upon HeadlessUI's internal open/close state (`static={true}`), it's also desirable to want control over the underlying element's `tabIndex`.

**Workaround**

Right now, it's easy enough to manually set the element's tab index immediately after Headless has rendered it.

It'd be ideal if, instead, Headless respected the given `tabIndex` whenever its visibility was manually controlled.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

For the Menu we are using the active descendant logic instead of a roving tab index. This means that the `Menu.Items` should stay focused to keep all accessibility features present, even when using the `static` prop.

We currently don't want to change this behaviour unless we can prove that it is safe to change this behaviour without any repercussions because that would also mean that you could set the `tabIndex` to undefined and therefore removing the tabIndex altogether.
