### ISSUE TITLE
Using Dialog and Menu together: prompting user for confirmation from context menu fails to trigger onClick

### ISSUE THREAD

**Issue by adamhp** [tailwindlabs/headlessui#1110]
**What package within Headless UI are you using?**
`@headlessui/react`

**What version of that package are you using?**
`1.4.3`

**What browser are you using?**
Google Chrome 
`Version 98.0.4758.80 (Official Build) (x86_64)`

**Reproduction URL**
https://codesandbox.io/s/confirm-dialog-in-context-menu-rryfbw?file=/pages/index.js

**Note**: Expected behavior of the above is that it should trigger a browser alert when you click Delete -> Confirm. It _may_ work the first time. Please try multiple times, as the error behavior is intermittent.

**Describe your issue**
When nesting a Dialog in a Menu, it appears that certain onClick events only fire sometimes, or there is otherwise odd behavior in handling click events when nesting a Dialog in a Menu.

I have a simple use case of having a delete button within a context menu (`Menu`). The delete button is wrapped in a custom component I call `Confirm`, that opens a `Dialog` and prompts the user to confirm the action (e.g. "Are you sure you want to delete that?"). The `onClick` handler of the "Confirm" appears to fire intermittently. I haven't had much luck discerning whether or not it is firing but not being handled, or not firing at all.

**Comment by bollingerdorian** [comment]
I have the same problem, when I call up a modal via the menu component, I can no longer navigate through the modal with Tab.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you update the reproduction url to get it into a "working" / debuggable state? Currently when I load it (https://rryfbw.sse.codesandbox.io) I see:
<img width="2548" alt="image" src="https://user-images.githubusercontent.com/1834413/154768782-746696a5-e68e-4d4c-baab-000c964c7c20.png">

**Comment by adamhp** [comment]
@RobinMalfait Not sure how that happened. Should be good now.

**Comment by ttsirkia** [comment]
I noticed that it occurs more often if you click first "Cancel" and then "Confirm" next time.

**Comment by RobinMalfait** [comment]
Hmm this is very odd I cannot for the life of me reproduce this issue. Here is a video where I try a dozen of times to reproduce it.

https://user-images.githubusercontent.com/1834413/155572344-6d5dce67-efd5-4a8d-83ea-843a5143cee7.mov

I also tried to do what @ttsirkia mentioned by using `Cancel` first a few times, but no luck... 

https://user-images.githubusercontent.com/1834413/155572452-43dda40b-2da7-4678-a25c-0ecaf26b9456.mov


---

If somebody can reproduce this in a consistent way and provide me a GitHub repo / codesandbox then I'm happy to help. For now, I'm going to close since I can't reproduce this.

**Comment by ttsirkia** [comment]
I tried this again with Firefox 97.0.1 in Windows 10. I didn't count the exact number but opening the modal and clicking randomly both buttons, something like after 30 clicks it occurred once that `alert` didn't show up.

**Comment by ttsirkia** [comment]
Using Edge 98.0.1108.56 it took just five clicks and I didn't click Cancel at all this time.

**Comment by ttsirkia** [comment]
Here is a way to reproduce: open the dialog, place the mouse inside the dialog immediately (this is important), wait a few seconds and click. Occurs every time.

![Headless](https://user-images.githubusercontent.com/2797729/155598341-a5c2790a-6b54-47be-9f78-10b22600f1e9.gif)

**Comment by ttsirkia** [comment]
In the video above I didn't put mouse inside the dialog immediately but doing that makes it occur every time.

**Comment by brennop** [comment]
Having similar problems with a Modal nested on a Menu component. Can't interact with the Modal content. I believe trying to click on the modal triggers the menu closing handler.

**Comment by ttsirkia** [comment]
Hmm, this is more interesting. If you place mouse above the "Are you sure?" the bug does not occur but if you place mouse in the left side of the Confirm button and wait, that is the trick
![Headless2](https://user-images.githubusercontent.com/2797729/155599100-f66c948d-72a6-4de8-911c-30201b193271.gif)
.

**Comment by ttsirkia** [comment]
And it seems that the delay is not important. If you approach the button from down to up, it also occurs almost every time.

![Headless3](https://user-images.githubusercontent.com/2797729/155600171-209aabd9-23b4-4e95-b19f-3c0a49044b6b.gif)

**Comment by ttsirkia** [comment]
It is easier to see this with Firefox although it occurs with Edge, too.

**Comment by ttsirkia** [comment]
You can do this with Edge: open the dialog with mouse, then just press Tab end Enter.

![Headless4](https://user-images.githubusercontent.com/2797729/155601989-578e5c13-a761-4a3e-b495-2bb5111854a8.gif)

**Comment by RobinMalfait** [comment]
Aha, ok I see what's happening. A few things to be exact:
- Currently you are rendering the `Confirm` as the `Menu.Item` but you are not forwarding all of the props to the lower level button (missing out on accessibility features, but also keyboard features. E.g.: we can't press `enter` while the "Delete" button is focused because the onClick is not forwarded).
- Another issue is that even if you forward the props correctly, that the `onClick` of the Button will be triggered (which opens the Dialog). But we will also close the `Menu.Item` which will **unmount** the `Menu.Items` and thus unmounts the `Confirm` dialog.

Here is a codesandbox with some modifications on how you can modify it while keeping most of your code. Basically, don't put the `Dialog` inside of the `Menu.Item`, instead use it as a sibling and only set the Dialog state from the `Menu.Item`. This allows you to keep the Dialog open even if the Menu already closed again.

https://codesandbox.io/s/confirm-dialog-in-context-menu-forked-ickr0z?file=/pages/index.js

**Comment by RobinMalfait** [comment]
@bollingerdorian not sure, but that doesn't sound like an ideal solution to me 🤔. I wonder if it makes more sense to only have 1 Dialog per kind (e.g.: confirmation dialog) and swap out the contents with the correct data based on the item you want to remove.
