### ISSUE TITLE
Next.js completely breaks with 1.5

### ISSUE THREAD

**Issue by OmerWow** [tailwindlabs/headlessui#1115]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome (Brave), Safari

**Reproduction URL**

I don't have one, all I know is I simply updated this simple package from v1.4.2 which worked fine to 1.5.0 and now I can't use my app any more (obviously a simple version rollback fixes everything so I'm fine).

**Describe your issue**

So really all I did was running yarn upgrade, and the ONLY change was headlessui/react 1.4.2 -> 1.5.0.
Now when I try running the dev server I get this error: 
![image](https://user-images.githubusercontent.com/12970637/154627575-5931c20b-e048-4012-be05-270d663c3164.png)

And when trying to build (yarn build):
![image](https://user-images.githubusercontent.com/12970637/154627747-2272d140-ba66-4481-b4f7-b4ad435a296c.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I just updated a personal project and it worked fine for me. Can you try to delete the `.next` folder and restart the server to see if that fixes things?
If not, can you create a minimal reproduction repo so that I can take a look? Thanks!

**Comment by jtomaszewski** [comment]
> Seems to be related to preact

Maybe; I'm using preact and I also have troubles with SSR and `Combobox` on headlessui 1.5.0 version (although we don't use next.js). We get an error like this:

![image](https://user-images.githubusercontent.com/1862580/154971559-58871080-96b8-47dd-b33d-f9a1c859b82e.png)

**Comment by RobinMalfait** [comment]
Then this is definitely a preact (interop) issue. We are currently only focusing on React / Vue implementations. By default the `Combobox` is rendering a fragment, but it looks like something (preact?) is also adding `__self` and `__source` to the fragment. Not sure if this is correct or not. The `as="div"` solves this but also not really because now those 2 props will be passed to the actual `div` not sure if you want this.
