### ISSUE TITLE
Combobox should show full list after selecting item

### ISSUE THREAD

**Issue by paustint** [tailwindlabs/headlessui#1145]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

Reporting from example https://headlessui.dev/react/combobox

**What browser are you using?**

Chrome

**Reproduction URL**

https://headlessui.dev/react/combobox
click "code"

**Describe your issue**

After typing in some text to filter the result, after I click on an item, then click away, then click again to open the dropdown.
EXPECTED: all results should be shown
ACTUAL: only the filtered items are shown

example:
type in `co`, which shows two results
click on any result
click away
click back to expand, notice the same two results are shown

<img width="344" alt="image" src="https://user-images.githubusercontent.com/5461649/155432316-f1c0eedd-7f5e-4f74-a311-05ba7f193954.png">

Another undesired result that is the same issue as above
open combobox
pick an item
select all text, and type in some invalid text like `woo`
click away from combobox, the text will update to the selected item
click the dropdown again, notice no results are shown even though the filter text shows a valid selection (but ideally all options would be shown)

<img width="362" alt="image" src="https://user-images.githubusercontent.com/5461649/155432424-8e21d33d-8ab5-40d1-9287-bafa2075bf92.png">

**Comment by adamwathan** [comment]
Hey thanks! I can reproduce this, definitely a bug.

For anyone on the team who gets a chance to look at this, here's a little video showing the issue and explaining it a bit more:

https://user-images.githubusercontent.com/4323180/155436168-89d2ca0a-f84c-4250-b4aa-663998f1de19.mov

**Comment by simonswiss** [comment]
Hey @paustint – thank you for reporting this issue! 

And thanks @adamwathan for the quick screen capture 👍

I had a look and opened a PR to fix it (it happens in both React and Vue examples).

https://github.com/tailwindlabs/headlessui.dev/pull/97

Basically, we were using a "query" piece of state for the search string, but this state was never reset after selecting a person, resulting in only the person names matching that state showing up.

It's funny because I cover this _exact same bug_ at the end of my latest video on building command palettes with the Combobox component:

https://youtu.be/-jix4KyxLuQ?t=2059

That gave me a pretty good idea of where to look to fix this bug in the demo 😅

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Also @adamwathan thanks for the video. I looked at the code that @simonswiss provided and I think this is a valid option. Right now when you select a value or close the combobox we will reset the query for the documentation examples. This allows you to always start from the full list.

If we want to, we can also implement that the query is set to the selected person as you described, but that means that we open the list with only a single value and have to change the query anyway to make _a_ change. The good part is that this is an implementation detail and you can choose how to handle it in your own apps if you use our `Combobox`.

**Comment by RobinMalfait** [comment]
The main issue is that the `query` which is used to filter results doesn't immediately know how to clear itself once we select a value or once we close the Combobox. To fix this, once the Combobox closes completely (which it does once you select a value, click outside or press `esc`) then we will reset the query. This in turn will make sure that the `filteredPeople` is the full list again and the moment you re-open the combobox all options are there.

The important part here is that we do it in the `afterLeave` of the transition. This is done so that it happens _after_ the transition is complete. If we don't do this (and you don't have to if you don't use our Transition component) then you will see a flash from a small filtered list to the big unfiltered list while it is transitioning which looks a bit strange.

The actual diff looks like this:

```diff
  import { Fragment, useState } from 'react'
  import { Combobox, Transition } from '@headlessui/react'
  import { CheckIcon, SelectorIcon } from '@heroicons/react/solid'

  const people = [
    { id: 1, name: 'Wade Cooper' },
    { id: 2, name: 'Arlene Mccoy' },
    { id: 3, name: 'Devon Webb' },
    { id: 4, name: 'Tom Cook' },
    { id: 5, name: 'Tanya Fox' },
    { id: 6, name: 'Hellen Schmidt' },
  ]

  export default function Example() {
    const [selected, setSelected] = useState(people[0])
    const [query, setQuery] = useState('')

    const filteredPeople =
      query === ''
        ? people
        : people.filter((person) =>
            person.name
              .toLowerCase()
              .replace(/\s+/g, '')
              .includes(query.toLowerCase().replace(/\s+/g, ''))
          )

    return (
      <div className="w-72 fixed top-16">
        <Combobox value={selected} onChange={setSelected}>
          <div className="relative mt-1">
            <div className="relative w-full text-left bg-white rounded-lg shadow-md cursor-default focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75 focus-visible:ring-white focus-visible:ring-offset-teal-300 focus-visible:ring-offset-2 sm:text-sm overflow-hidden">
              <Combobox.Input
                className="w-full border-none focus:ring-0 py-2 pl-3 pr-10 text-sm leading-5 text-gray-900"
                displayValue={(person) => person.name}
                onChange={(event) => setQuery(event.target.value)}
              />
              <Combobox.Button className="absolute inset-y-0 right-0 flex items-center pr-2">
                <SelectorIcon
                  className="w-5 h-5 text-gray-400"
                  aria-hidden="true"
                />
              </Combobox.Button>
            </div>
            <Transition
              as={Fragment}
              leave="transition ease-in duration-100"
              leaveFrom="opacity-100"
              leaveTo="opacity-0"
+             afterLeave={() => setQuery('')}
            >
              <Combobox.Options className="absolute w-full py-1 mt-1 overflow-auto text-base bg-white rounded-md shadow-lg max-h-60 ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                {filteredPeople.length === 0 && query !== '' ? (
                  <div className="cursor-default select-none relative py-2 px-4 text-gray-700">
                    Nothing found.
                  </div>
                ) : (
                  filteredPeople.map((person) => (
                    <Combobox.Option
                      key={person.id}
                      className={({ active }) =>
                        `cursor-default select-none relative py-2 pl-10 pr-4 ${
                          active ? 'text-white bg-teal-600' : 'text-gray-900'
                        }`
                      }
                      value={person}
                    >
                      {({ selected, active }) => (
                        <>
                          <span
                            className={`block truncate ${
                              selected ? 'font-medium' : 'font-normal'
                            }`}
                          >
                            {person.name}
                          </span>
                          {selected ? (
                            <span
                              className={`absolute inset-y-0 left-0 flex items-center pl-3 ${
                                active ? 'text-white' : 'text-teal-600'
                              }`}
                            >
                              <CheckIcon className="w-5 h-5" aria-hidden="true" />
                            </span>
                          ) : null}
                        </>
                      )}
                    </Combobox.Option>
                  ))
                )}
              </Combobox.Options>
            </Transition>
          </div>
        </Combobox>
      </div>
    )
  }
```

The code for both Vue and React is available on the main examples on the docs if you are interested in that code.
![image](https://user-images.githubusercontent.com/1834413/155514091-2efe1eae-247e-4437-9ee4-8c0135b2cc59.png)

- https://headlessui.dev/react/combobox
- https://headlessui.dev/vue/combobox



---
