### ISSUE TITLE
  Property 'value' is missing in type ComboBox

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/headlessui#1154]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/combobox-bug-ypm9g6?file=/src/Search.tsx

**Describe your issue**

See line no. 68 & 71 in `Search.tsx`, it gives a TS error on `ComboBox` & `item`:

>   Property 'value' is missing in type '{ children: (false | Element)[]; as: "div"; className: string; onChange: (item: any) => any; }' but required in type '{ value: string; onChange(value: string): void; disabled?: boolean | undefined; }'.ts(2322)

I get this error in VSCode but you can also see it in Codesandbox.

How to fix it?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The Combobox is a component with a `value` and an `onChange`. This means that there is a selected value. You can read more about it here: https://headlessui.dev/react/combobox#basic-example

If you don't need a selected value, then you can set the `value` to `null`. E.g.: use `<Combobox value={null} ... />`

**Comment by deadcoder0904** [comment]
@RobinMalfait that `null` trick works but i think when `as="div"` is set, it shouldn't require me to use `value` or `onChange` since that doesn't make sense on a `div` so i'm pretty sure it should be a bug.

any reason to not loosen the type definition for that? just curious :)

**Comment by RobinMalfait** [comment]
It's definitely not a bug. The idea is that the Combobox consists of multiple components to create a Combobox experience. By default it even renders a `Fragment` so in that regard a `value` also doesn't make sense but that's not how you should look at those components, it's more like 1 big component if that makes sense.

We can potentially loosen the type definition, but it doesn't hurt to be explicit in this case. If we loosen the type and in the future we want to make it possible to be both controlled and uncontrolled (currently it is a controlled component) then we don't have that option anymore and we will introduce a backwards compatibility issue in that case. This is because typically you differentiate between controlled and uncontrolled via "a value" and "value is undefined" (at least in React that's the case).

**Comment by edmbn** [comment]
Just so the team is aware, TailwindUI command palette components don't have value on combobox so when using the code directly from the web we get an error telling that "property value is missing".
