### ISSUE TITLE
[DOCS]: add custom port root doc

### ISSUE THREAD

**Issue by skimmilk6877** [tailwindlabs/headlessui#1187]
When there are a dom with id = 'headlessui-portal-root ',port will create root under that dom. In some scenario, it is a good feature.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This is more a coincidence and considered private API. You can use it, but since we consider it private API, it is subject to change without following proper semver.

Because of this, I'm not going to document and close this issue. We might have a supported API in the future to change the portal root.
