### ISSUE TITLE
ComboBox onChange Event Types

### ISSUE THREAD

**Issue by pieperz** [tailwindlabs/headlessui#1258]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.5.0

**What browser are you using?**
N/A

**Reproduction URL**
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/combobox/combobox.tsx#L290

**Describe your issue**

The ComboBox's onChange value type set to String. All examples on [HeadlessUI](https://headlessui.dev/react/combobox#combobox-option) and TailwindUI are setting the ComboBox.Option value to an object with several properties.

When using typescript this causes issues with the compiler and extra complexity to work around.

Here is how I am expecting to be able to use Types in the onChange value "event".

```
type Item = {
  id: number;
  url: string;
  name: string;
}
const item: Item = { id: 1, url: "/something", name: "Something"};
<Combobox
  value={null}
  as="div"
  onChange={(item:Item) => (window.location = item.url)}
>
  <Combobox.Option value={item} >
    {item.name}
  </Combobox.Option>
</Combobox>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is not that the type is set to `string`, it is **defaulting** to a string. It is a generic type based on the `value` prop.

In your case, you are setting the value to `null`, therefore the item in the `onChange` will also be `null`.

You can set the value to `item` for example:
```tsx
import { Combobox } from "@headlessui/react";

type Item = {
  id: number;
  url: string;
  name: string;
};

const item: Item = { id: 1, url: "/something", name: "Something" };

export default function App() {
  return (
    <Combobox
      value={item}
      onChange={(item) => { /* This will now be of type `Item` */
        console.log(item);
      }}
    >
      <Combobox.Option value={item}>{item.name}</Combobox.Option>
    </Combobox>
  );
}
```

This is because as far as I know, you can't get the type of `item` from a child `<Combobox.Option value={/* type from here */} />` into the parent `<Combobox />`.

That said, even if you keep it `null`, then what you are doing should work just fine:
```tsx
import { Combobox } from "@headlessui/react";

type Item = {
  id: number;
  url: string;
  name: string;
};

const item: Item = { id: 1, url: "/something", name: "Something" };

export default function App() {
  return (
    <Combobox
      value={null}
      onChange={(item: Item) => {
        console.log(item);
      }}
    >
      <Combobox.Option value={item}>{item.name}</Combobox.Option>
    </Combobox>
  );
}
```

*(screenshot from my editor)*
<img width="790" alt="image" src="https://user-images.githubusercontent.com/1834413/159115145-9b44ad53-1e95-4937-8b06-7eb6b17884e1.png">
