### ISSUE TITLE
🤯 Popover.Button can not stop propagation

### ISSUE THREAD

**Issue by chioio** [tailwindlabs/headlessui#1260]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Describe your issue**

When I define a click event on parent container, the inner popover button click not stop propagation.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1263, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.

**Comment by toantran201** [comment]
Hi @RobinMalfait , I think the same problem with Listbox.Button.
