### ISSUE TITLE
Bug in Menu when input inside dropdown

### ISSUE THREAD

**Issue by joshmanders** [tailwindlabs/headlessui#127]
If you create a menu component and put an input in the dropdown when you open it and click the input to create focus it removes the focus and you cannot type in the input.

https://codesandbox.io/s/headlessuireact-menu-example-forked-xhqpr?file=/src/App.js

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is not the intended behaviour for a Menu component. I have a bit more information on this here: https://github.com/tailwindlabs/headlessui/issues/130#issuecomment-717172240

**Comment by lauridskern** [comment]
Hi, sorry for reopening, but is there a way to work around this?
I wanna make my Listbox/Menu searchable but can't focus the search-input

**Comment by RobinMalfait** [comment]
Hey @lauridskern 

While I see the use case for it. Attaching an actual input to your Listbox is a separate component (Combobox: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox) which we don't support yet.
For a Menu it's a little strange to have a search, since it is not data related.

That said, you can already start "typing" and it will move the focus to closest match.

But for now, there is no real good workaround, sorry.

**Comment by lauridskern** [comment]
Hi, @RobinMalfait thanks for the response. I see that it doesn't make sense for the Menu. Where it would make sense, I think, is the Listbox, wouldn't it?
