### ISSUE TITLE
Combobox fails to "mark" exisiting value in options list until selection made

### ISSUE THREAD

**Issue by okbytes** [tailwindlabs/headlessui#1322]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**

For example: v1.5.0

**What browser are you using?**
Chrome

**Reproduction URL**
https://codesandbox.io/s/summer-feather-yzn8ti?file=/src/Dropdown.tsx

**Describe your issue**
When mounting a Combobox for the first time, the default value does not get marked in the options list until a selection is made by the user.

To reproduce in the codesandbox:
* Click/Focus the combobox
* Press the down arrow key to open the combobox menu
* Observe the "Admin" option has not been given a ✔️ mark (which should be there as it is the selected option)
* Pick an options from the list (it doesn't matter which one)
* Open the combobox menu again (focus ›› down arrow key)
* Observe your selection marked appropriately with the ✔️

I would expect a Combobox instantiated with a value to show that value marked as "selected" in the options list whether or not the user has gone in and selected it during the Combobox's lifecycle in the given view.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because the object in your `value` does not exist in the list of options you provide to the `options` prop.

Headless UI uses a `===` check to make sure the identity is the same.

```jsx
<Dropdown
  value={{ label: "Admin", value: "admin" }} // It looks like this one exists in the array but it doesn't because it's a different object
  options={[
    { label: "User", value: "user" },
    { label: "Admin", value: "admin" }
  ]}
  onChange={(option) => console.log(option)}
/>
```

Here is a test you can do yourself, try to run this in your console:

```js
[
  { label: "User", value: "user" },
  { label: "Admin", value: "admin" }
].includes({ label: "Admin", value: "admin" }) // false
```

Here is an updated version where we guarantee a stable reference: https://codesandbox.io/s/nervous-dew-quzcxz?file=/src/App.tsx

Another solution would be to add an `id` to your objects and use the id in the `value` prop.
