### ISSUE TITLE
Bug: Tailwind "disabled:" class not working on combobox disabled options

### ISSUE THREAD

**Issue by lveillard** [tailwindlabs/headlessui#1362]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

    "@headlessui/react": "^0.0.0-insiders.591b328",
    but happens also in stable ones

**What browser are you using?**

Chrome

**Describe your issue**

Hello all!,
As the title explains, styling `Combobox.Option` with for example `className="disabled:bg-red-500"` does not seem to work, the class has to be set up programatically using a `disabled` boolean

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is because the `disabled:` state in Tailwind uses the native `disabled` attribute, but this can't always be guaranteed in Headless UI because it depends on the `Combobox.Option`. By default the `Combobox.Options` renders a `ul` and `Combobox.Option` renders an `li`. These elements don't use the `disabled` attribute. E.g.: https://play.tailwindcss.com/b0vb09RrJa

Instead, you can use the exposed `disabled` state.

Similar to this: https://headlessui.dev/react/combobox#styling-the-active-and-selected-option
But using `disabled`, all exposed information can be found here: https://headlessui.dev/react/combobox#combobox-option

**Comment by 0Chan-smc** [comment]
Or you can just use 'ui-disabled:' variant in @headlessui/tailwindcss plugin.
