### ISSUE TITLE
Listbox as="div" is still a fragment

### ISSUE THREAD

**Issue by bodograumann** [tailwindlabs/headlessui#1369]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.0

**What browser are you using?**

Firefox

**Reproduction URL**

[Listbox example in vue playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBpbXBvcnQge1xuICAgIExpc3Rib3gsXG4gICAgTGlzdGJveEJ1dHRvbixcbiAgICBMaXN0Ym94T3B0aW9ucyxcbiAgICBMaXN0Ym94T3B0aW9uLFxuICB9IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0BoZWFkbGVzc3VpL3Z1ZUAxLjYuMC9kaXN0L2luZGV4LmpzJ1xuXG5cbiAgY29uc3QgcGVvcGxlID0gW1xuICAgIHsgaWQ6IDEsIG5hbWU6ICdEdXJ3YXJkIFJleW5vbGRzJywgdW5hdmFpbGFibGU6IGZhbHNlIH0sXG4gICAgeyBpZDogMiwgbmFtZTogJ0tlbnRvbiBUb3duZScsIHVuYXZhaWxhYmxlOiBmYWxzZSB9LFxuICAgIHsgaWQ6IDMsIG5hbWU6ICdUaGVyZXNlIFd1bnNjaCcsIHVuYXZhaWxhYmxlOiBmYWxzZSB9LFxuICAgIHsgaWQ6IDQsIG5hbWU6ICdCZW5lZGljdCBLZXNzbGVyJywgdW5hdmFpbGFibGU6IHRydWUgfSxcbiAgICB7IGlkOiA1LCBuYW1lOiAnS2F0ZWx5biBSb2hhbicsIHVuYXZhaWxhYmxlOiBmYWxzZSB9LFxuICBdXG4gIGNvbnN0IHNlbGVjdGVkUGVyc29uID0gcmVmKHBlb3BsZVswXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxMaXN0Ym94IGFzPVwiZGl2XCIgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiAjODg4XCIgdi1tb2RlbD1cInNlbGVjdGVkUGVyc29uXCI+XG4gICAgPExpc3Rib3hCdXR0b24+e3sgc2VsZWN0ZWRQZXJzb24ubmFtZSB9fTwvTGlzdGJveEJ1dHRvbj5cbiAgICA8TGlzdGJveE9wdGlvbnM+XG4gICAgICA8TGlzdGJveE9wdGlvblxuICAgICAgICB2LWZvcj1cInBlcnNvbiBpbiBwZW9wbGVcIlxuICAgICAgICA6a2V5PVwicGVyc29uXCJcbiAgICAgICAgOnZhbHVlPVwicGVyc29uXCJcbiAgICAgICAgOmRpc2FibGVkPVwicGVyc29uLnVuYXZhaWxhYmxlXCJcbiAgICAgID5cbiAgICAgICAge3sgcGVyc29uLm5hbWUgfX1cbiAgICAgIDwvTGlzdGJveE9wdGlvbj5cbiAgICA8L0xpc3Rib3hPcHRpb25zPlxuICA8L0xpc3Rib3g+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==)

**Describe your issue**

When using `as="div"` and attributes meant for the `div` on the `<Listbox>`, these can not be rendered correctly. E.g.:
> Extraneous non-props attributes (style) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

**Comment by DrJume** [comment]
Happens to `Combobox`es with `class` attribute aswell since v1.6.0. The `class` is not applied in the DOM.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1372, and will be available in the next release.

You can already try it using `npm install @headlessui/vue@insiders`.

I've also updated your [Vue playground example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuICBpbXBvcnQge1xuICAgIExpc3Rib3gsXG4gICAgTGlzdGJveEJ1dHRvbixcbiAgICBMaXN0Ym94T3B0aW9ucyxcbiAgICBMaXN0Ym94T3B0aW9uLFxuICB9IGZyb20gJ2h0dHBzOi8vdW5wa2cuY29tL0BoZWFkbGVzc3VpL3Z1ZUAwLjAuMC1pbnNpZGVycy44MDdhZTY2L2Rpc3QvaW5kZXguanMnXG5cblxuICBjb25zdCBwZW9wbGUgPSBbXG4gICAgeyBpZDogMSwgbmFtZTogJ0R1cndhcmQgUmV5bm9sZHMnLCB1bmF2YWlsYWJsZTogZmFsc2UgfSxcbiAgICB7IGlkOiAyLCBuYW1lOiAnS2VudG9uIFRvd25lJywgdW5hdmFpbGFibGU6IGZhbHNlIH0sXG4gICAgeyBpZDogMywgbmFtZTogJ1RoZXJlc2UgV3Vuc2NoJywgdW5hdmFpbGFibGU6IGZhbHNlIH0sXG4gICAgeyBpZDogNCwgbmFtZTogJ0JlbmVkaWN0IEtlc3NsZXInLCB1bmF2YWlsYWJsZTogdHJ1ZSB9LFxuICAgIHsgaWQ6IDUsIG5hbWU6ICdLYXRlbHluIFJvaGFuJywgdW5hdmFpbGFibGU6IGZhbHNlIH0sXG4gIF1cbiAgY29uc3Qgc2VsZWN0ZWRQZXJzb24gPSByZWYocGVvcGxlWzBdKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPExpc3Rib3ggYXM9XCJkaXZcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6ICM4ODhcIiB2LW1vZGVsPVwic2VsZWN0ZWRQZXJzb25cIj5cbiAgICA8TGlzdGJveEJ1dHRvbj57eyBzZWxlY3RlZFBlcnNvbi5uYW1lIH19PC9MaXN0Ym94QnV0dG9uPlxuICAgIDxMaXN0Ym94T3B0aW9ucz5cbiAgICAgIDxMaXN0Ym94T3B0aW9uXG4gICAgICAgIHYtZm9yPVwicGVyc29uIGluIHBlb3BsZVwiXG4gICAgICAgIDprZXk9XCJwZXJzb25cIlxuICAgICAgICA6dmFsdWU9XCJwZXJzb25cIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJwZXJzb24udW5hdmFpbGFibGVcIlxuICAgICAgPlxuICAgICAgICB7eyBwZXJzb24ubmFtZSB9fVxuICAgICAgPC9MaXN0Ym94T3B0aW9uPlxuICAgIDwvTGlzdGJveE9wdGlvbnM+XG4gIDwvTGlzdGJveD5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9) with the latest insiders build.
