### ISSUE TITLE
Popover Panel wrongly appears behind components after updating @headlessui/react to version 1.6.0

### ISSUE THREAD

**Issue by RichSchulz** [tailwindlabs/headlessui#1377]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**

v.1.6.0

**What browser are you using?**

Reproduced the bug on Safari, Firefox and Chrome

**Reproduction URL**

[Codesandbox Example](https://codesandbox.io/s/bug-demo-qbg5u5?file=/src/App.js)

**Describe your issue**

In the above example, the Popover Panel should appear in front of the Vega Chart and the Menu (or Dropdown), due to its z-score being set to 50. However, the Popover Panel appears behind these two other components. When bumping @headlessui/react to version 1.5.0, it works as intended and the Popover Panel appears in front of the Chart and the Menu.

For reference:
v.1.6.0 [Buggy]
![Screenshot 2022-04-29 at 10 52 09](https://user-images.githubusercontent.com/49609334/165913832-acf12143-7f6f-4ed4-a334-cb4ae744ade4.png)

vs.

v.1.5.0 [Working]
![Screenshot 2022-04-29 at 10 52 28](https://user-images.githubusercontent.com/49609334/165913921-3b98ac6d-9488-4022-a77c-bd9aa0dc21cf.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We made some improvements to the Transition component to work with React 18 and made it more stable in general. Because of this, the `enterTo` and `leaveTo` will stay on the elements to prevent strange layout jumps once the Transition is done.

To fix your particular issue, you can add a `relative z-10` for example to guarantee that it sits on top, instead of relying on it by accident.

Here is an updated CodeSandbox: https://codesandbox.io/s/bug-demo-forked-h1smye?file=/src/App.js:662-700

Hope this helps!

**Comment by RichSchulz** [comment]
Thanks, @RobinMalfait this solved my Issue and apologies for assume there was something wrong with your code, when indeed I had made a mistake ;)
