### ISSUE TITLE
Menu documentation for integrating with Nextjs does not work

### ISSUE THREAD

**Issue by michaelcais** [tailwindlabs/headlessui#1408]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.1

**What browser are you using?**

Chrome

**Reproduction URL**
https://codesandbox.io/s/headlessui-menu-7klocc?file=/pages/index.js

**Describe your issue**

Clickin on the menu button will trigger a warning on the console.
_Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?_

Navigating with keyboard to select menu item by pressing the enter key also does not work.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'm a bit confused which page on the Headless UI documentation are you referring to? Can you share the link?

The reason I ask is because this morning somebody reported this and I've fixed it immediately but that's but a while already so I wonder that you may have some stale link instead of using https://headlessui.dev?

That said, the docs can be found here: https://headlessui.dev/react/menu#integrating-with-next-js

And the `MyLink` component should be implemented, as the warning states, with a `forwardRef`:

```js
import { forwardRef } from 'react'
import Link from 'next/link'
import { Menu } from '@headlessui/react'

const MyLink = forwardRef((props, ref) => {
  let { href, children, ...rest } = props
  return (
    <Link href={href}>
      <a ref={ref} {...rest}>
        {children}
      </a>
    </Link>
  )
})

function Example() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          <MyLink href="/profile">Profile</MyLink>
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}
```
Here is an updated CodeSandbox: https://codesandbox.io/s/headlessui-menu-forked-hbijjf?file=/pages/index.js

**Comment by darrylmorley** [comment]
Hi, I get an error that the component is missing the display name when using the example for NextJS Link.

**Comment by therealgilles** [comment]
@darrylmorley Is it an error or is it an eslint warning?
