### ISSUE TITLE
Feat request: open Listbox when typing

### ISSUE THREAD

**Issue by robbevp** [tailwindlabs/headlessui#141]
Hi there,

While using the Listbox, I notice that I often start typing when I have the ListboxButton focused ut not yet opened.
At the moment I first need to press enter and then type to find the option I want.

Is it possible to open the Listbox when the user presses any key? (Except a few special cases like esc, tab ...)

**Comment by drusellers** [comment]
I would love to see something like this.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I like this suggestion, but it is a little bit tricky to get right, let me explain:

We currently have 2 "rendering" strategies, you can use the `unmount={true}` (default) on the `Listbox.Options` so that the `Listbox.Options` get unmounted when the `Listbox` is not open anymore. The other approach is to use `unmount={false}`, which doesn't unmount, but hides the `Listbox.Options`. Why is this important?

If you look at the native `<select>`, then you can start "typing" while the select is focused and still closed. This will also "select" the best match already (it will call your change handlers). You also have to notice that the native `select` will never open in this case. We can implement this when the `unmount={false}` is used, because all the items are rendered in the DOM. However, we cannot implement this (in a straightforward way) when the `unmount={true}` strategy is used, in this case we have to open the `Listbox` first and then start searching (your suggestion).

However this results in 2 different behaviours. We could normalize it to always open, so that it is consistent. But this results in different behaviour between the `Listbox` and the native `select` element, which is a little unfortunate.

In short, while it is possible and a good idea, we have to play with the usability and define what our expectations are.
I am not going to implement it immediately, but I will mark it as a feature request and come back to it later.

Thanks!

**Comment by mk-94** [comment]
Hi, i would try to solve it. It is my first issue in an open source project. Can you tell me what I need to pay special attention to and how to start?
