### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by jiblett1000** [tailwindlabs/headlessui#1411]
**What package within Headless UI are you using?**

vue

**What version of that package are you using?**

0.0.0-insiders.6667fac

**What browser are you using?**

N/A

**Reproduction URL**

https://github.com/jiblett1000/headless-ref-test

**Describe your issue**

I"m getting errors such as:

`Module '"@headlessui/vue"' has no exported member 'TransitionRoot'.`

This is happening when using `<script setup lang="ts">`. Removing `lang="ts"` gets rid of the errors.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I cloned the repo and ran `yarn`, opened the file and everything seems fine:
![image](https://user-images.githubusercontent.com/1834413/167035622-0203fb09-13b0-4636-8668-15f6a7bc5dd7.png)

My guess / recommendation would be to first try and restart your VS Code and/or restart your TypeScript server. If that doesn't work, try to remove `node_modules`, reinstall everything and just to be sure, restart VS Code again.

Here is a link to the types for the latest `insiders` build: https://unpkg.com/browse/@headlessui/vue@0.0.0-insiders.c4e35f3/dist/components/transitions/transition.d.ts
Here is a link to the types entry point: https://unpkg.com/browse/@headlessui/vue@0.0.0-insiders.c4e35f3/dist/index.d.ts where transition is definitely listed.

Hope restarting / reinstalling does the trick for you, since I don't think there is anything we can do.
