### ISSUE TITLE
Opening or closing Dialogs with scrollbar-gutter: stable results in underlying page shifts

### ISSUE THREAD

**Issue by youssefm** [tailwindlabs/headlessui#1436]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.6.1

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/headless-ui-dialog-with-scrollbar-gutter-stable-tkkjib

**Describe your issue**

When you use `scrollbar-gutter: stable` and you open a HeadlessUI Dialog, the entire background shifts unnecessarily. This appears to be caused by the padding-right that's applied to the document element.  scrollbar-gutter is an important CSS property for avoiding layout shifts during page load and it's unfortunate that its use results in a jarring visual experience alongside headlessui's Dialog.

**Comment by adamwathan** [comment]
Hey! We've deprecated `Dialog.Overlay` due to some scroll-related challenges like what you've noticed here and solved by introducing `Dialog.Panel`. Check the migration guide here and see if you still have any issues:

https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v1.6.0

**Comment by youssefm** [comment]
Thanks @adamwathan . I updated the repro to use `Dialog.Panel` but the same problem still appears.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1457, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

Here is an updated CodeSandbox with the latest insiders build that fixes this issue: https://codesandbox.io/s/headless-ui-dialog-with-scrollbar-gutter-stable-forked-5o0y6z?file=/src/App.js

**Comment by youssefm** [comment]
Thanks for the speedy fix @RobinMalfait! I really appreciate it.

**Comment by HIT2022** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> This should be fixed by #1457, and will be available in the next release.
> 
> You can already try it using:
> 
> * `npm install @headlessui/react@insiders`.
> * `npm install @headlessui/vue@insiders`.
> 
> Here is an updated CodeSandbox with the latest insiders build that fixes this issue: https://codesandbox.io/s/headless-ui-dialog-with-scrollbar-gutter-stable-forked-5o0y6z?file=/src/App.js


Just in case it throws others off....

![image](https://user-images.githubusercontent.com/34664460/193195395-dda89cb7-93c9-4512-b68d-5461a0d3e166.png)

The background shift youssefm described is resolved (above pic, from his repo), but at first I didn't realize that the space where the scrollbar was (_before_ `overflow: hidden`) inherits `background-color: #fff` from `html` -

![image](https://user-images.githubusercontent.com/34664460/193195711-70653df8-4b9e-4160-bc91-700932f0e22c.png)

Which of course makes sense, but prior to realizing that, I thought the shift issue was still a problem because no color was set on `html`, and it was instead inheriting `background-color` from `body` - 

![image](https://user-images.githubusercontent.com/34664460/193195911-c56e51cd-bfff-46cd-8d05-01b0f6997859.png)

**Comment by Junah-Park** [comment]
Hello, is there a way to apply background shading to the gutter also so that there isn't a bright white strip at the right of the page?
