### ISSUE TITLE
[react menu] possible code oddity in menu.tsx re: disposables()

### ISSUE THREAD

**Issue by tshinnic** [tailwindlabs/headlessui#149]
This query is only from reading code, with no observation of a runtime problem, but it looks worthy of a check.

menu.tsx `Item()` `handleClick()` [menu.tsx#L418-L426](https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/src/components/menu/menu.tsx#L418-L426)

In menu.tsx `Item()` function `handleClick()` there seems to be a leftover reference to `disposables()` when `d` has been allocated, or else if `d` is not really available *at event time*, then why is `d` included in list of dependencies for the `.useCallback()`?

I do see this pattern of using `disposables().nextFrame()` within events in two other places within menu.tsx, so maybe it is the mention of `d` in dependencies that is stray above?

BTW: is `d` unneeded as yet in menu.tsx `Menu()` ?  [menu.tsx#L140](https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/src/components/menu/menu.tsx#L140)  [menu.tsx#L166](https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/src/components/menu/menu.tsx#L166)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your questions!
Much appreciated! 🙏

You are correct that the `d` in the 2 dependency arrays are not needed anymore, because they got switched to `disposables()` directly.
Let me clarify what those things do:

The `disposables` utility is a small utility that allows us to dispose certain actions when you call the `.dispose()` method. For example, we implement `setTimeout` or `requestAnimationFrame` and when you call dispose we call `clearTimeout` and `cancelAnimationFrame` respectively.

The `const d = useDisposables()` is a hook implementation that wraps this, and when the component "unmounts" then we call the dispose method. This also means that when we close the menu for example, that we dispose all `d.disposables` from menu items. However we still want to refocus the button in the next frame for example, therefore we use the `disposables().nextFrame()` directly. I must admit that this is a little bit of a hack (because those calls are never cancelled/disposed deliberately), but I didn't want to create or use some sort of `useReducerWithAlgebraicEffects` so that I could run some code *after* the state has changed.

I will remove the unnecessary `d` dependencies!

Hope this answered your question!
