### ISSUE TITLE
Menu (Warning: Function components cannot be given refs)

### ISSUE THREAD

**Issue by ARkrOSClou** [tailwindlabs/headlessui#1512]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`v1.6.3`

**What browser are you using?**

Chrome

**Reproduction URL**

code: https://github.com/ARkrOSClou/headlessui_ref_issue/blob/main/src/App.js

**Describe your issue**

when using a simple combination in the `Menu`, an unpleasant warning appears in `dev mode`, is it possible to do something with it?

![image](https://user-images.githubusercontent.com/46116126/170769725-c71c2833-19cc-4f3c-ae5a-d676e47940cf.png)
![image](https://user-images.githubusercontent.com/46116126/170769809-a01c58c6-12f6-44db-9c15-f7e5408d18e5.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI gives a bunch of props (and a ref in some cases) to the components it is rendering. Usually people just use a button or a link, but since you are using a custom component, you have to make sure to passthrough the props and as the error mentions use the forwardRef as well.

In your case you can replace your custom item:
```diff
- const Item = () => <div>Item</div>
+ const Item = React.forwardRef((props, ref) => <button ref={ref} {...props}>Item</button >)
```

Hope this helps!

**Comment by tordans** [comment]
@RobinMalfait I just finished debugging a forwardRef error. I now wonder, if there is a better way to do this. Or at least explain it. I still don't fully understand whats going on (`*`)…, but to me it looks like, that whenever I use a Gatsby Link ([Gatsby Link Docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/), [Reach Router Link Docs](https://reach.tech/router/api/Link)) inside a `Menu.Item`, this issue will come up. If that is true, I think this would warrant some special note in the Docs (eg with an explicit example in the Docs) or maybe even some way to change the Headless UI behavior with a "do not forward ref in this case" (disclaimer: see `*`).

My workaround now is https://github.com/FixMyBerlin/fixmy.safetycheck/commit/a9d2e1a8fdfa038b7b5b6919f16ddfbdfcfd8538, which wraps my custom component with forwardRef. However, I cannot (due to typescript errors that I did not fully investigate) and apparently do not need to use the given ref. Does Headless UI need this ref to be on the children?

**Comment by zenzen-sol** [comment]
Typescript users may receive an error along the lines of `Type 'ForwardedRef<unknown>' is not assignable to type...`

To fix, you may be able to cast the ref type inline. Using the example from above:

```diff
- const Item = React.forwardRef((props, ref) => <button ref={ref} {...props}>Item</button >)
+ const Item = React.forwardRef((props, ref) => <button ref={ref as React.Ref<HTMLButtonElement>} {...props}>Item</button >) 
```
