### ISSUE TITLE
Typescript error with <Menu>

### ISSUE THREAD

**Issue by Robin-w151** [tailwindlabs/headlessui#1523]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.3

**What browser are you using?**

Firefox@100.0.2

**Reproduction URL**

https://github.com/Robin-w151/headlessui-bug-reproduction

**Describe your issue**

The following typescript error is displayed, when the @headlessui/react Menu component is used:

`TS2590: Expression produces a union type that is too complex to represent.`

I found 2 similar issues (#233, #330), however, `jsxImportSource: @emotion/react` is still required for the other styling to work.

**Comment by anamdiazs** [comment]
I think the issue is on the css prop, maybe you need to add the array data type to pass it as a prop.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As far as I can tell we unfortunately can't do anything about this in Headless UI itself. It looks like the `"jsxImportSource": "@emotion/react"` extends/overrides the JSX TypeScript types.

We do have an open issue #1394 where we want to simplify and export the types. Hopefully that fixes something, but I'm afraid that for now you might want to annotate that those errors are expected `// @ts-expect-error`

**Comment by davidtkramer** [comment]
Apologies for reviving a closed issue, but I've found two potential approaches for fixing the error that I figured would be worth sharing.

### Approach 1: Simplify `CleanProps` from Headless UI

The first fix simplifies the `CleanProps` type from the Headless UI [helper types](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/types.ts) by removing the conditional type and relying on TS dropping `never` from union types. 

```typescript
// original definition
declare let __: "1D45E01E-AF44-47C4-988A-19A94EBAF55C";
export declare type __ = typeof __;
type CleanProps<
  TTag extends ReactTag,
  TOmitableProps extends PropertyKey = __
> = TOmitableProps extends __
  ? Omit<PropsOf<TTag>, PropsWeControl>
  : Omit<PropsOf<TTag>, TOmitableProps | PropsWeControl>

// simplified definition
type CleanProps<
  TTag extends ReactTag,
  TOmitableProps extends PropertyKey = never
> = Omit<PropsOf<TTag>, TOmitableProps | PropsWeControl>
```

[This code comment](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/types.ts#L5) explains the use of `__` over `never`. I'm admittedly missing a lot of context here, but it seems it would be safe to default to `never` in this instance since never will always be dropped from the union type, regardless of whether it's actual data or just the default.

@RobinMalfait would you be open to accepting a PR with this change? No worries if you're not, I totally understand that it's debatable whether this should be fixed in @headlessui or in @emotion/react.

### Approach 2: Simplify `WithConditionalCSSProp` from Emotion

The `WithConditionalCSSProp` type used in emotion's [JSX type definitions](https://github.com/emotion-js/emotion/blob/main/packages/react/types/jsx-namespace.d.ts) has nested conditional types. I found that removing the nested conditional in this type also fixes the error. Unfortunately, I haven't yet found a way to simplify this type without introducing subtle bugs in the `className` prop detection. For example, the simple version below allows `className` on a component with no props.

```typescript
// original definition
type WithConditionalCSSProp<P> = 'className' extends keyof P
  ? string extends P['className' & keyof P]
    ? { css?: Interpolation<Theme> }
    : {}
  : {}

// simplified, buggy definition
type WithConditionalCSSProp<P extends { className?: any }> = string extends P['className']
    ? { css?: Interpolation<Theme> }
    : {};
```

**Comment by pedrosimao** [comment]
Any news on that?

**Comment by paolostyle** [comment]
This is still an issue...
