### ISSUE TITLE
Can not open nested dialog

### ISSUE THREAD

**Issue by tianyingchun** [tailwindlabs/headlessui#1536]
**What package within Headless UI are you using?**

@headlessui/react@1.6.4

**What browser are you using?**
 Chrome

**Reproduction URL**

 https://github.com/tianyingchun/headlessui
```
yarn install
yarn dev.
```

**Describe your issue**
Open one dialog , and then click button try to open dialog Two, all dialog was closed now.

**Comment by tianyingchun** [comment]
BTW the nested dialog if we use `Dialog.panel` replace `Dialog.Overlay` it alwasy break .

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you look at your code here:
https://github.com/tianyingchun/headlessui/blob/452bf41a715ba634e503c141e374544c917b30ac/src/pages/dialog-one.tsx#L57-L64

What you will notice is that you have a form and a button, the default behaviour of a button is to submit.

What actually happens when you click the "Open Dialog Two" is that the form submits and your page refreshes (you will notice the `?` in your url). Because of this refresh your dialogs close.

If you add a `type="button"` to that button, that will prevent your form from submitting and everything should work.

---

For your comment about the `Dialog.Panel` if that is still an issue for you then please open a new issue with a reproduction attached so that we can keep the issues dedicated to a single topic.

Hope this helps!
