### ISSUE TITLE
[BUG] Tabgroup emits number as an Event type

### ISSUE THREAD

**Issue by mkbctrl** [tailwindlabs/headlessui#1540]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

For example: v1.6.4

**What browser are you using?**

For example: Chrome, latest

**Reproduction URL**

I think it's not required

**Describe your issue**

I import the component directly from the package
![Screenshot 2022-06-01 at 12 32 50](https://user-images.githubusercontent.com/10107362/171385092-08f0d94b-189a-4d43-97bc-94c24c2a1208.png)

Use it in regular manner:
![Screenshot 2022-06-01 at 12 32 43](https://user-images.githubusercontent.com/10107362/171385138-53efec52-00ae-4d2f-87c6-bad0216027fe.png)

My issue is, the TabGroup emits payload as `Event` instead of number (like it happens in React version of this component)
![Screenshot 2022-06-01 at 12 30 11](https://user-images.githubusercontent.com/10107362/171384993-4beb6846-4c55-4205-a374-db138f4cd103.png)

so I endup guarding against wrong type like this:
```
const setDefaultIndex = (payload: unknown) => {
    if (typeof payload === 'number') {
      setHistoryStateByKey('tabsSectionDefaultIndex', payload)
    }
  }
```

From what I understand, the `payload` will always be of type `number` since it's current tab index. Shouldn't we have it defined with the `defineEmits` on the component lvl? Like so:

```
const emit = defineEmits<{
  (event: 'change', payload: number): void
}>()
```
?

**Comment by thecrypticace** [comment]
Hey! Could you provide some more details about your editor and setup? This is super strange because we definitely type this as taking a number — not `Event`:

This is me doing a bit of work to pull the type out from the component definition:
<img width="430" alt="Screen Shot 2022-06-02 at 14 27 31" src="https://user-images.githubusercontent.com/614993/171700708-eb0eb667-41ac-4ae1-a5fa-a1d0d24d14d5.png">

This is me using Vue's built-in inference for `h` (aka `createElement`):
<img width="528" alt="Screen Shot 2022-06-02 at 14 29 44" src="https://user-images.githubusercontent.com/614993/171701492-505a144d-3f10-4238-89e3-a06e51e24fe6.png">

Now, I will say that Volar, even in a fresh install of vscode, isn't working for me for some reason. It thinks `TabGroup` is of type `any` and that any of its properties are of type `any`. But the emit types are definitely there:

https://github.com/tailwindlabs/headlessui/blob/4e13a0ea4f098ad4657e3f9932903470b4269309/packages/%40headlessui-vue/src/components/tabs/tabs.ts#L60-L64

**Comment by MRoc** [comment]
Is VSCode when I press F12 on `@change` like this

![image](https://user-images.githubusercontent.com/4061644/172136974-f297febf-b152-4869-ba61-6cdd7789c60b.png)

it gets me to 

![image](https://user-images.githubusercontent.com/4061644/172137049-028f5033-b4bb-40fd-a1d2-71a54edc53a0.png)

I'm on same codebase as OG. My setup is VSCode. I can confirm the typing is actually right. Just VCCode leads to wrong location when pressing F12.

**Comment by smashercosmo** [comment]
Still happens in HeadlessUI@1.7.12
<img width="1005" alt="Screenshot 2023-04-11 at 13 30 17" src="https://user-images.githubusercontent.com/273283/231134102-2d99d0ae-72a7-451d-9105-fff4a93d347b.png">

**Comment by smashercosmo** [comment]
@RobinMalfait yes, the argument is of type `number`. But how would you explain this type error?

<img width="825" alt="Screenshot 2023-04-17 at 16 07 02" src="https://user-images.githubusercontent.com/273283/232492994-1ade0d42-5aa8-43c1-95e8-b5ce90c248ed.png">
<img width="349" alt="Screenshot 2023-04-17 at 16 07 18" src="https://user-images.githubusercontent.com/273283/232493049-3f12e1c6-7426-4eb6-8de3-c5fea4386408.png">

**Comment by thecrypticace** [comment]
@smashercosmo I don't see this error in a fresh Vite+Vue project with Headless UI. Can you provide a reproduction? Also what editor are you using? Looks maybe like PHPStorm or WebStorm?

**Comment by smashercosmo** [comment]
@thecrypticace yeah, might be a bug with webstorm's vue plugin
