### ISSUE TITLE
[DOCS]: Combobox#multiple example has error on displayValue

### ISSUE THREAD

**Issue by FezVrasta** [tailwindlabs/headlessui#1563]
https://headlessui.dev/react/combobox#selecting-multiple-values

In this example `displayValue` is set to `(person) => person.name`, but when `multiple` is set to `true` the first argument of the `displayValue` callback will be an array of options, not a single one.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We've updated the docs and pushed a fix.
- You can do 2 things in this case, you can completely omit the `displayValue`, in this example this is fine since we list the selected values in the `ul` above.
- You can implement a `displayValue` that indeed accepts an array of values and return a single string e.g.:
```js
displayValue={(people) =>
  people.map((person) => person.name).join(', ')
}
```
