### ISSUE TITLE
Dropdown throws errors after update

### ISSUE THREAD

**Issue by zdarin** [tailwindlabs/headlessui#1582]
Im today installed latest package @headlessui/vue@v1.6.4 
Before im used @headlessui/vue@v1.5.0
Checked on Safari Chrome
Using Vue 3 Composition API SFC

<img width="1437" alt="Screenshot 2022-06-12 at 17 48 36" src="https://user-images.githubusercontent.com/42121280/173243251-0f3c5760-ebe6-41ef-9aaf-a591a48ca9ee.png">

When click on dropdown button on some of my component opens on some do not open at all but when hover on MenuItem its throws errors every time on hover. For now rolled back to older version

**Comment by zdarin** [comment]
Founded where problem MenuItem should be as="div" and then working

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Ideally your `MenuItem` is a `button` or an `a` tag and not a div, because you either want to go somewhere (`a`) or you want to perform an action like logout (`button`).

More info: https://headlessui.dev/react/menu#rendering-a-different-element-for-a-component
