### ISSUE TITLE
[DOCS]: react Combobox static code sample is confusing

### ISSUE THREAD

**Issue by stephenmcm** [tailwindlabs/headlessui#1597]
https://headlessui.dev/react/combobox#showing-hiding-the-combobox. 
The example for using the `static` prop on `Combobox.Options` is confusing when blindly cut and paste as the visual effect is the same. The `open` value is still controlling the display of the content including the wrapping div making the code function the same as the example given above but without the extra div wrapper.
While writing up this issue I built this as a demo: https://codesandbox.io/s/headless-ui-tailwind-css-combobox-component-forked-r98ut1?file=/src/App.js. 
It's not great but it does capture what `static` and `open` are doing more clearly.

**Comment by adamwathan** [comment]
Hey! Yeah they are intended to look the same, the code sample is showing how to achieve the same thing but using `static` + the `open` render prop vs. letting it be handled for you automatically 👍 Going to leave this as is for now, those code samples aren't really meant to be copied and pasted (especially since they are devoid of styling), they are really just there to be read which is why we deliberately highlight certain lines in the code and stuff.

Appreciate the feedback though, if it turns out this is a major point of confusion for lots of people we can definitely explore other ways of explaining it.
