### ISSUE TITLE
using onClick instead of onPointerUp if not supported?

### ISSUE THREAD

**Issue by ebuckthal** [tailwindlabs/headlessui#167]
Hi 👋. I really appreciate the work you've put into this library!

Is there a particular reason to use `onPointerUp` instead of `onClick`? I've noticed that pointer-events are not at all supported on iOS 12 and earlier. If I use `onClick` instead, it appears to fix the issue, but I'm not sure if I'm missing something about the benefits of pointer-events.

So far, I can get around this by polyfilling pointer-events, but those solutions feel like overkill for this issue. Would you support falling back to `onClick` where pointer events are not supported?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Pointer events (once supported everywhere) are a bit nicer, because they give you additional information about mouse, pen, ... It is also a bit nicer on mobile (if it is implemented).

But, I currently use `onClick`, and the other pointer related events have fallbacks to mouse events.

This should be fixed, and will be available in the next release.

- You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
- You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
