### ISSUE TITLE
Dialog won't work as a child of MenuItem

### ISSUE THREAD

**Issue by valgeirb** [tailwindlabs/headlessui#1672]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-2sjm22?file=src/App.vue

**Describe your issue**

Using a `Dialog` inside a `MenuItem` won't show the `Dialog`, instead it gives a warning:

```
There are no focusable elements inside the <FocusTrap />
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This won't work because the moment you click a menu item the menu will close and unmount all of its children (including the Dialog).

Instead, move the Dialog as a sibling of the Menu instead of nested, and set the `open` state from within the menu item instead.
