### ISSUE TITLE
Transition.Child renders a <div> with no classes in Next JS

### ISSUE THREAD

**Issue by BigWhale** [tailwindlabs/headlessui#169]
This is somewhat related to #80 and after fiddling around with my code, I came to the similar solution as described in [this comment](https://github.com/tailwindlabs/headlessui/issues/80#issuecomment-706112244).

The code below:

```
<Transition.Child
enter="transition ease-in-out duration-300 transform"
enterFrom="-translate-x-full"
enterTo="translate-x-0"
leave="transition ease-in-out duration-300 transform"
leaveFrom="translate-x-0"
leaveTo="-translate-x-full"
>
  <div className="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-cyan-700">
  </div>
</Transition.Child>

```
Will render this:
```
<div>
  <div  class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-cyan-700">
  </div>
</div>

```
Adding `className="flex w-full"` to Translation.Child solves my issue, but this should probably be default?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is done by design because we need access to a DOM element to make everything as smooth as possible. We can forward a ref but that doesn't always ensure that everything works as expected, and the API will be a bit more annoying.

We will not add `flex w-full` classes by default, because you can use this library without Tailwind if you want.
As an alternative approach, I would suggest to use this instead:

```jsx
<Transition.Child
  enter="transition ease-in-out duration-300 transform"
  enterFrom="-translate-x-full"
  enterTo="translate-x-0"
  leave="transition ease-in-out duration-300 transform"
  leaveFrom="translate-x-0"
  leaveTo="-translate-x-full"
  className="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-cyan-700"
>
  {/* Children..., notice that we removed the div and moved the className to the `Transition` component. */}
</Transition.Child>
```

All props that are on the `Transition.Child` component that are not part of the API (`enter`, `enterFrom`, ...), will be forwarded to the underlying DOM node.
