### ISSUE TITLE
Opened dialog through Popover bugs out when closed

### ISSUE THREAD

**Issue by dukesteen** [tailwindlabs/headlessui#1701]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
1.6.7

**What browser are you using?**
Tested in Firefox, Edge, Chrome

**Reproduction URL**
https://github.com/dukesteen/headless-ui-dialog-bug

**Describe your issue**

Opening a dialog through a popover bugs out the dialog when closing it again. Video: https://youtu.be/hoce8KI9usI

**Comment by thecrypticace** [comment]
Hey thanks for the report! We uhh… forgot something… and it resulted in this breaking. Sorry!

I merged the fix for this and it'll be available in our next tagged release. If you want to try it before then you can test it using our insiders build (`npm install @headlessui/vue@insiders`) which should be published in a few minutes (if not already).

Thanks for the repro that helped narrow down the issue quite well! 🙌

**Comment by dukesteen** [comment]
No problem! Glad it's fixed
