### ISSUE TITLE
Runtime directives can no longer be applied to some Vue elements

### ISSUE THREAD

**Issue by henribru** [tailwindlabs/headlessui#1709]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.7

**What browser are you using?**

Chromium 103

**Reproduction URL**
https://stackblitz.com/edit/vitejs-vite-ovm1xe?file=src/components/HelloWorld.vue

**Describe your issue**
In a recent version multiple elements of the Vue package now apparently render a fragment/template as the root element instead of an actual tag. This has broken any code that applied runtime directives such as v-show to those elements. In the linked reproduction, notice that the checkbox can't be used to hide the radio group. In the console you will see the following warning: "Runtime directive used on component with non-element root node. The directives will not function as intended."

You can work around this by adding your own tag in the slot with the runtime directive, but it's a bit annoying. If it's unavoidable then a warning in the documentation would be good.

**Comment by thecrypticace** [comment]
Hey, appreciate you opening the issue.

We utilize fragments in a handful of places to help handle focus trapping (mainly to defer to the browser in places so it can handle things where possible), and more recently, to render native, hidden form inputs. However, with Vue, even if a `Fragment` contains only a single element node, certain runtime directives do not get applied (like `v-show` AND any custom directives). At least in this case, you could likely use `v-if` instead of `v-show` which works with components regardless of whether they render a `Fragment` or not. It would be really cool if there was a way to make runtime directives work but there's no way to detect directives on a component and move them to a child element or component. Vue explicitly prevents invoking the element-oriented functions of runtime directives on a component unless it directly renders an HTML element, another component (that must eventually render an element), or a comment but this does not include fragments. (If you're curious you can see this behavior here: https://github.com/vuejs/core/blob/a95554d35c65e5bfd0bf9d1c5b908ae789345a6d/packages/runtime-core/src/renderer.ts#L2093)

This may be something we revisit in the future but, for now, it's not something that is likely to change. We'll work on adding information to the documentation regarding the use of directives. Thanks!
