### ISSUE TITLE
Select (Listbox) not working with pre-selected integer values

### ISSUE THREAD

**Issue by kskrlinnorth2** [tailwindlabs/headlessui#1710]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.6.7

**What browser are you using?**

Not important for this issue

**Describe your issue**

I am using Simple Custom Select component https://tailwindui.com/components/application-ui/forms/select-menus#component-8298198b136afab3bb19391ae716077f

For model editing purpose: When I pass IDs (integers) to the component, items are selected in object, but they are missing check icon (selected prop of ListboxOption is false). When I select other option from the component, then all checkmark appear, but values are converted to strings, not integers.
Is this bug or component doesn't work with integers on purpose so I am required to re-map my IDs to strings before passing data to v-model?

Same issue when using single and multiple selections.

You can see that items exist in object, but they are missing checkmark:
![image](https://user-images.githubusercontent.com/61736280/180752926-eb677e40-80a7-4b91-8e7e-60afa42425bd.png)
Note: labes `false false` / `true false` are ListboxOption props `active` and `selected` (you can see it is false on Manager, but should be true)
![image](https://user-images.githubusercontent.com/61736280/180753017-a8ef2c8d-351d-4ba4-8fa4-983fded41374.png)
Multiple selection is also missing checkmarks:
![image](https://user-images.githubusercontent.com/61736280/180753358-b40e48dc-5b6c-4ad0-9943-0a5e825bebc7.png)
Form props contain values, but integers (I know I can cast IDs to strings or map collection to convert to strings, but I prefer to work with my IDs as integers, not strings):
![image](https://user-images.githubusercontent.com/61736280/180753609-b40f9497-edce-4bac-b522-0058f78987b7.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I feel like a lot of important data is missing here so a reproduction repo would be really handy. I have a simple example with a list of ID's here, which seems to work fine, so please provide a reproduction so that we can take a look.

https://stackblitz.com/edit/vue-ser62j?file=src/App.vue

---

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
