### ISSUE TITLE
[React v1.6.6] Transition appear not working with nextjs

### ISSUE THREAD

**Issue by Talent30** [tailwindlabs/headlessui#1729]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome v103

**Reproduction URL**

[Without Next.js](https://codesandbox.io/s/headlessui-react-transition-menu-popper-example-forked-ilveqj?file=/src/App.js:90-295)

[Next.js](https://codesandbox.io/s/happy-fire-4rjpxp?file=/pages/index.js)

**Describe your issue**

No transition on initial load

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

There are 2 things going on in your Next.js example:
1. You aren't loading Tailwind CSS, therefore the classes don't exist and therefore no transitions are happening.
2. Because of the `show={true}` by default, the contents is server side rendered by Next.js and therefore you will see a little glitch of the server side rendered code.

Here is an updated example which includes Tailwind CSS: https://codesandbox.io/s/muddy-wave-ws0y1k?file=/pages/index.js
