### ISSUE TITLE
HeadlessUI modal scrollbar bug, cannot scroll after modal is closed.

### ISSUE THREAD

**Issue by joschan21** [tailwindlabs/headlessui#1744]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/joschan21/tailwind-scrollbar-bug

**Describe your issue**

When opening a modal from a slideover, the scrollbar disappears after closing the modal. You cannot scroll anymore until you refresh the page.

**Steps to reproduce:** 

1. Open the slideover
2. Open the modal from inside the Slideover
3. Close the modal, for example through clicking somewhere else
4. The scrollbar disappears and you cannot scroll anymore.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This problem exists because currently we don't support simultaneous Dialogs, only nested Dialogs. Now I know that you are flipping a toggle and opening the Dialog and closing the Slideover at the same time. However, due to transitions those still exists together at the same time. 

Until we support nested Dialogs, there are 2 things you can do:
1. Nesting, you can nest the Modal inside the Slideover but that would mean that you have to keep the Slideover open while the Dialog is open and that might not be ideal.

   The Slideover usage could look like this:
   ```js
   <Slideover open={slideover} setOpen={setSlideover} setModal={setModal}>
      <Modal open={modal} setOpen={setModal} />
   </Slideover>
   ```

   The `button` would just be this:
   ```js
   <button
      type="button"
      onClick={() => {
         setModal(true);
      }}
   >
      open modal
   </button>
   ```
  
   I opened a PR with these changes: https://github.com/joschan21/tailwind-scrollbar-bug/pull/1

3. Delay the opening of the Modal so that it only opens the moment the Slideover is closed.

   While I know that this is a very stupid solution, because we don't support simultaneous Dialogs yet, this is one way of solving it:

   ```js
   <button
     type='button'
     onClick={() => {
       setOpen(false)
       setTimeout(() => {
         // A "nextFrame" implementation. Double rAF to ensure all transitions
         // are complete.
         requestAnimationFrame(() => {
           requestAnimationFrame(() => {
             setModal(true)
           })
         })
       }, 700 /* Duration of Transition (sm:duration-700) */)
     }}>
     open modal
   </button>
   ```

   I opened a PR with these changes: https://github.com/joschan21/tailwind-scrollbar-bug/pull/2


Again, I know these workarounds are less than ideal but I hope this can help you out in the meantime.
