### ISSUE TITLE
Headless UI Switch Going Out of Flow on RTL

### ISSUE THREAD

**Issue by rafayrty** [tailwindlabs/headlessui#1756]
Headless UI Switch Behaves Weirdly and moves out of the flow on RTL Sites, a Following Screenshot is attatched.
![image-screenshot](https://i.ibb.co/C17s1Lh/Screenshot-2022-08-11-at-4-31-41-AM.png)

**Steps To Reproduce**
Add dir="rtl" to the parent element to see the issue.

**Headles UI Being Used:**
@headlessui/react

**Package Of The Version Being Used?**
v1.6.6

**What browser are you using?**
Chrome

**An Alternative Fix**
Just add direction:ltr to the parent element.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI itself is Headless and therefore unstyled. The examples on the documentation page are a styled example on how you can implement a beautiful styled switch.
Currently those examples don't work in RTL mode, just because we didn't add the styles for it.

If you need to implement RTL mode for your own projects, than these docs should help you out: https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support
