### ISSUE TITLE
Vue - Popover does not open when clicked in Cypress

### ISSUE THREAD

**Issue by greyvugrin** [tailwindlabs/headlessui#1778]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

For example: v1.6.7

**What browser are you using?**

Chrome (within Cypress)

**Reproduction URL**

https://github.com/greyvugrin/headlessui

**Describe your issue**

When running Cypress, the popover element intermittently fails to open. The Popover button shows a focus state in these cases, but the panel itself does not open. Waiting longer within the tests prior to clicking has no effect either.

To repro:

```
yarn install
yarn vue playground

# 2nd terminal
cd packages/playground-vue
npx cypress open
```

Once cypress is open, run the `vue-popover.cy.ts` spec file. You'll see that the test intermittently fails, and when it does, there is a "focus away" event that gets logged from the component. I'm unable to repro in a normal browser when clicking, so I'm wondering if it has to do with how Cypress triggers clicks.

I started to look into the focus handling in `isFocusWithinPopoverGroup` but lost the trail. It seems that the activeElement is the `body` when that function is triggered.

### Screenshots:
<img width="1605" alt="Screen Shot 2022-08-20 at 2 25 10 PM" src="https://user-images.githubusercontent.com/3294460/185766717-cab97347-f111-4a72-9c53-c1fc5db474a7.png">
<img width="555" alt="Screen Shot 2022-08-20 at 2 19 32 PM" src="https://user-images.githubusercontent.com/3294460/185766718-76816f3b-a5f9-4cf7-af3d-dbef56ad1692.png">

**Comment by thecrypticace** [comment]
Leaving some notes here:
- It's feels like cypress is running things at the wrong time (but I'm not certain). 
- When saving the test file it runs again and passes 100% of the time.
- Just re-running without saving the file _always_ fails.

**Comment by thecrypticace** [comment]
I _think_ I know what the issue is. Given that cypress runs entirely in the browser _inside an iframe_ it has to do some fancy stuff around simulating clicks and focus events. When the iframe isn't already focused, firing a click event causes the iframe's contentWindow to be focused. However, the `document.activeElement` inside the iframe is temporarily incorrect. Cypress does restore it but I believe this happens at the wrong time. We end up picking up on the focus change (because the button is supposed to focus) and the active element is `document.body` instead of the button thus being treated as an outside click. This also explains why saving the test file produces a passing test — because the focus never changes from the iframe so there's no oddities around what's focused and when.

As far as I can tell this ultimately has more to do with Cypress' set up for running tests than Headless UI. I'm not sure we can fix this on our side without breaking the existing outside-click behavior or introducing cypress specific code into Headless UI. I'm fairly certain that if the test runner used a full page instead of nesting inside an iframe the test would pass.

I'd suggest maybe opening an issue with Cypress to see if they can come up with a solution for this.

An example of something that has different behavior depending on whether or not you run the test from saving a file or from clicking the re-run button in the test runner:
```html
<div id="popover" style="position: absolute; top: 100px; left: 100px">
  <button id="button">Click me</button>
  <div id="menu">closed</div>
</div>

<script>
let isOpened = false
function open() {
  console.log('Opening')
  document.querySelector('#menu').innerHTML = 'opened'
  isOpened = true
}
function close() {
  console.log('Closing')
  document.querySelector('#menu').innerHTML = 'closed'
  isOpened = false
}
function toggle() {
  if (isOpened) {
    close()
  } else {
    open()
  }
}

window.addEventListener(
  'focus',
  () => {
    if (document.querySelector('#popover').contains(document.activeElement)) {
      return
    }

    console.log(document.activeElement)
    close()
  },
  true
)

document.querySelector('#button').addEventListener('mousedown', () => toggle())
</script>
```

```js
describe('popover click', () => {
  it('passes', () => {
    cy.visit('http://localhost:9000/my-test-name')
    cy.get('#button').click()
  })
})
```

(technically in testing I tweaked the popover test to basically ignore Vue and mutate the DOM directly but this code is basically the same).

**Comment by thecrypticace** [comment]
And, also wanted to say that I really appreciate the report and reproduction! Hopefully Cypress can come up with something that works. 🤞
