### ISSUE TITLE
Dialog closes onMouseUp?

### ISSUE THREAD

**Issue by aouahib** [tailwindlabs/headlessui#1780]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

^1.6.6

**What browser are you using?**

Chrome

**Describe your issue**

- Click inside `Dialog.Panel`
- While holding the click, move the mouse outside of `Dialog.Panel`
- Dialog will close

You can try it  on the example dialog from the official docs : https://headlessui.com/react/dialog

I have a dialog with a slider, and if I try to select the max value by sliding all the way, the mouse ends up outside the dialog and it closes.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed already, and will be available in the next release. The live documentation side is running on the latest version and not the insiders version which is why the issue still exists over there.

You can already try it using `npm install @headlessui/react@insiders`.
