### ISSUE TITLE
With Fixed Header you still see the jumps of the UI

### ISSUE THREAD

**Issue by simirka** [tailwindlabs/headlessui#1804]
**What package within Headless UI are you using?**

I have used @headlessui/react in the reproduction example, but it`s the same in the Vue package.

**What version of that package are you using?**

v1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/headless-ui-dialog-with-scrollbar-gutter-stable-forked-j29lur?file=/src/App.js

**Describe your issue**

If you have fixed the Header you still see the jumps of the UI because padding should be added to the body instead of the HTML tag. I think there should be a possibility to switch between these tags.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Since you are using `position: fixed;` adding the `padding-right` to counteract the now missing scrollbar, won't help if we move that value to the body.

Could you tell me a bit more about the real-life use case you have for this? Because I don't see a lot of use cases where the navbar is fixed, instead typically a `position: sticky;` is used. If a `position: sticky` is usable for you, then you will get the desired effect: https://codesandbox.io/s/headless-ui-dialog-with-scrollbar-gutter-stable-forked-jyekp5?file=/src/App.js

**Comment by simirka** [comment]
@RobinMalfait yep, you are right, my bad missed that point

**Comment by KarKarbI4** [comment]
@RobinMalfait I think that problem is more complex than this particular case : )
Setting padding right on `<html>` tag means any fixed element jumps on modal opening.
I suggest not only setting `padding-right` style property, but also provide special css custom property, which one can use in client scope CSS to position fixed elements.

Also, for anyone struggling with issue, I use `MutationObserver` on `document.documentElement` to sync value of `padding-right` provided by Headless UI Dialog component with css custom property `--scroll-lock-safe-area` 

**Workaround code:**
```ts
// syncScrollLockSafeArea.ts
const SСROLL_LOCK_SAFE_AREA = '--scroll-lock-safe-area';

// When opening, Dialog component sets `padding-right` value of scrollbar width to <html /> element 
// `syncScrollLockSafeAreaCallback` function syncs this value with 
// css custom property `SСROLL_LOCK_SAFE_AREA`
// for using the value in client code
// Issue: https://github.com/tailwindlabs/headlessui/issues/1804
export function syncScrollLockSafeArea() {
  const htmlElement = document.documentElement;

  const observer = new MutationObserver(() => {
    const htmlStyle = document.documentElement.style;

    if (
      htmlStyle.getPropertyValue(SСROLL_LOCK_SAFE_AREA) !==
      htmlStyle.paddingRight
    )
      htmlStyle.setProperty(SСROLL_LOCK_SAFE_AREA, htmlStyle.paddingRight);
  });

  observer.observe(htmlElement, {
    attributes: true,
    attributeOldValue: false,
    attributeFilter: ['style'],
  });

  return () => observer.disconnect();
}
```

**Call this in useEffect of custom Dialog component**
```tsx
// MyDialog.tsx
function MyDialog({ isOpened, ...pass }) {
    useEffect(syncScrollLockSafeArea, [isOpened])
    return <Dialog open={isOpened} {...pass}>{children}</Dialog>
}
```

**Usage in client code**
```tsx
function AppHeader() {
    return <div className="fixed pr-[var(--scroll-lock-safe-area)]">{children}</div>
}
```
