### ISSUE TITLE
Modal Opens Scrolled to The End

### ISSUE THREAD

**Issue by tomitrescak** [tailwindlabs/headlessui#1808]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

1.6.6

**What browser are you using?**

Chrome, Safari, Firefox

**Reproduction URL**

https://codesandbox.io/s/tailwind-css-and-react-forked-er28u0?file=/src/App.js

Click on the Open to open the modal

**Describe your issue**

When a long modal is opened it is scrolled all the way to the bottom. Tried to fix it, but no idea why this happens

**Comment by tomitrescak** [comment]
Got it from the docs in "Managing initial focus"

**Comment by adamwathan** [comment]
Hey! This is because when you open a dialog, the first focusable element is automatically focused, and the first focusable element in your dialog is the "go back" button at the very bottom, so focusing that element causes the browser to scroll.

This is definitely a bit annoying, will discuss with the team if there is anything we could do here.

**Comment by tomitrescak** [comment]
Adam, for now I added invisible div at the top and made it ref to focus :/
I would just add a possibility to pass "false" value, which would eliminate the auto focus
