### ISSUE TITLE
`Dialog` animates incorrectly with `Transition`

### ISSUE THREAD

**Issue by shannonrothe** [tailwindlabs/headlessui#1819]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

For example: v1.6.6

**What browser are you using?**

For example: Firefox

**Reproduction URL**

https://codesandbox.io/s/nostalgic-yalow-ibp7iq

**Describe your issue**

When the `Dialog` transitions in, it seemingly gets interrupted. We can observe that the wrapping `Transition` component is at fault because by commenting it out, the `Dialog` is correctly positioned in the center of the viewport.

I have followed the "Transitions" section of the `Dialog` component [here](https://headlessui.com/react/dialog#transitions) pretty much exactly the same in both my real-world app and the MRE I've provided on this issue, but I can't seem to find a workaround to the issue I'm facing.

Also, I've tried both Chrome and Firefox with the same result.

I suspect it's some kind of focus bug?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is not really a bug with the `Transition` component, one thing we do is we keep the final `enterTo` classes so that if you transition from `red` to `blue` that you don't loose the `blue` once it is done transitioning.

What's happening here is that the `transform` class stays on the parent Dialog, and funnily enough this messes with the `fixed` of the child. Here is a reproduction of that without Headless UI:

https://play.tailwindcss.com/FIHlpbfwIq

What you can do instead, which is also what we do in Tailwind UI, is not transitioning the Dialog itself, but only the Panel and the Backdrop. This allows you to get a bit more control over both items and might even fix a bug (e.g. the backdrop you have currently also scales in a bit).

Next, we did a bunch of improvements to the `Transition` component, so if you use the `insiders` build you will get even better results. (We will release Headless UI v1.7 today or early this week).

One thing I also noticed is that you have the `open` prop on the `Dialog` component. If you are using the Dialog together with a Transition then you should not add this `open` prop otherwise leave transitions will be instant instead of fading out. (Behind the scenes, the Dialog will receive the `open` value from the Transition which will be set to `false` once the Transition is complete).

Putting this all together should result in the behaviour you want: https://codesandbox.io/s/relaxed-kate-tm6cmy?file=/src/App.tsx

**Comment by shannonrothe** [comment]
@RobinMalfait thank you!

In that case should the [example in the docs](https://headlessui.com/react/dialog#transitions) be updated as it suggests transitioning the whole `Dialog` rather than the backdrop/panel individually? If not, feel free to ignore me, and thanks again for the help!
