### ISSUE TITLE
Switch - `TypeError: Cannot read properties of undefined (reading 'switchRef')`

### ISSUE THREAD

**Issue by oceaann** [tailwindlabs/headlessui#1827]
Libraries versions
`@headlessui/vue` - 1.7.0
`nuxt` - 3.0.0-rc.9

Reproduction/example: https://codesandbox.io/s/gracious-williamson-tjkrci?file=/pages/index.vue

Vue 3/Nuxt 3

Code:
```vue
<template>
  <Switch
      v-model="modelValue" @update:modelValue="$emit(`update:modelValue`, $event)"
      :class="modelValue ? `bg-[#456E4DFF] left 0.15s ease-out` : `bg-[#555762FF]`"
      class="relative inline-flex items-center h-[28px] rounded-full transition-colors w-[52px] border-white border-[1px]"
  >
    <span :class="modelValue ? `translate-x-[26px]` : `translate-x-[4px]`"
          class="inline-block transform h-[20px] w-[20px] rounded-full bg-white transition-transform transform"
    />
  </Switch>
</template>

<script setup>
import { Switch } from "@headlessui/vue"
let { modelValue } = defineProps(["modelValue"])
</script>
```

Error:
```js
[Vue warn]: Unhandled error during execution of setup function
  at <Switch modelValue=true onUpdate:modelValue= [
  [Function (anonymous)],
  [Function (anonymous)],
  [Function: onUpdate:modelValue]
] class="bg-[#456E4DFF] left 0.15s ease-out relative inline-flex items-center h-[28px] rounded-full transition-colors w-[52px] border-white border-[1px]" >
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'switchRef')
    at setup (file:///d:/custom-frontend/node_modules/@headlessui/vue/dist/components/switch/switch.js:1:1393)
    at callWithErrorHandling (D:\custom-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at setupStatefulComponent (D:\custom-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7107:29)
    at setupComponent (D:\custom-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7062:11)
    at renderComponentVNode (D:\custom-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (D:\custom-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:608:12)    at _sfc_ssrRender (D:/custom-frontend/components/SwitchLR.vu
e:27:31)
    at renderComponentSubTree (D:\custom-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:253:13)
    at renderComponentVNode (D:\custom-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (D:\custom-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:608:12)
```

**Comment by thecrypticace** [comment]
@RobinMalfait I did a bit of poking around:
- This is an SSR only issue
- `inject` gets called twice to provide the `GroupContext` (I guess once for SSR and once during hydration?)
- In the first instance `currentInstance` and `currentRenderingInstance` are both `undefined`.
- This causes `inject` to return `undefined` instead of `null` (the default value). This situation would throw a warning in a dev build — but it's been stripped from the prod build.
- This seems like a Vue bug _maybe_. It could be we're doing something weird during SSR that's causing this too. Maybe it has something to do with microtasks? Not sure.

The code sandbox, for me, never loads. It's always stuck on "installing packages". So, I created a SSR-enabled [Vue SFC explorer reproduction](https://sfc.vuejs.org/#__SSR__eNqNVG1v2jAQ/iunrB9aqU6AAq0i2jFp6+dJm/aFIBGSC3h1Yst2AAnlv++cFyBFrfYlsu/lee45X+7ofVPK35Xohd7MYq5EbPElKgBmKd/VB4DjEbCI1wJTqKrG1HwvYujyW242AmHHcpmieI68NinyIGijZkGX0Z1mwQUrXU2iubJg0JaKLDxXUltooTMtc4g8P2juru7IOwUdQWMGVRfVOgXaU/XPLuI2i4XBO0fdkL14914DwfJY+X+NLKgbR1dl1DpM5IVQW5ytRg7psLVWmTAIykK9bfxE5sGcfIEuC8tzZKnM5w/+yH94IrHGXtp9NDlba7k3qIkx8u4vwAMy7lAzjUWKGvWnZO9ie4TvfB+TzrcYpwKNKXnwmbp+2HzoP/qDhooTxaEGdZg0JRV19fxM1+P1a89tsqU3t5EN64n5E4sSaWzOlwYMYF6qlBL7YTeYc3u7unKt7uEGd1jYuy49TERsTA8ZvsJqvWGLL+PJ9Mf4++vrEgRmFgb+cGIAY4NMlnYFYRs2mUwepyMKW3WgHaZG0sR3CLwQvECWCTwAJ62GJVQEatiyxehJHZagZUldSllWCgFWx4XhlsuCJVJIbWDPFpORi1tLTe/F9luC6S6LIXkcd2Tdj0JNmxkV0x9TP6D9QGJN4nrODlTElCBqST3z2Fk7VWddrZy1kMlbU2wmdV6LGbgiqdrm0FNFzWrKvpB3Tj6dOrrT8qAVc1F5VYHtFoZT2W6MZmT+e2kcoUk4r4SrMY+o8oxk/tRSmdtFf/aWvR1R/QORWMQg) if that helps.

**Comment by sprattek** [comment]
This issue comes with the `nuxt - 3.0.0.rc9`, everything was working nicely with `rc8`.

**Comment by sprattek** [comment]
Found a working solution for me [here](https://github.com/tailwindlabs/headlessui/issues/982#issuecomment-1069530706)

**Comment by thecrypticace** [comment]
Hey, appreciate you providing a reproduction for this! We looked into this further and it appears to be not a Headless UI issue.

Looks like the bundler build of the server render doesn't have this problem but the browser build does. Likely for the same reason that Nuxt has an issue — like @sprattek pointed out. The fix here would be to add Headless UI to your `build.transpile` array in your config. Nuxt did make changes though to treat Vue as an external. It may be worth reporting this issue here (regardless of if adding it to `build.transpile` works): https://github.com/nuxt/framework/issues/4084

Ultimately this isn't a Headless UI issue but either a Vue internals problem or a Nuxt problem or both.

**Comment by oceaann** [comment]
> Found a working solution for me https://github.com/tailwindlabs/headlessui/issues/982#issuecomment-1069530706
also works for me
