### ISSUE TITLE
Nested Headless UI Components inherit parent's state with Tailwind modifiers

### ISSUE THREAD

**Issue by jgmcelwain** [tailwindlabs/headlessui#1857]
**What package within Headless UI are you using?**

- `@headlessui/react`
- `@headlessui/tailwindcss`

**What version of that package are you using?**

- `@headlessui/react` @ 1.7.2
- `@headlessui/tailwindcss` @ 0.1.1

**What browser are you using?**

Tested in Chrome 105.0.5195.102, Firefox 105.0b6, Safari 12.5.1

**Reproduction URL**

https://github.com/jgmcelwain/headlessui-tailwind-nested-component

**Describe your issue**

When nesting a Headless UI `Disclosure` inside of a `Dialog`, the `ui-open:` modifier on a `Disclosure`'s children will be triggered by the `Dialog` it is part of. This means it is impossible to use the modifiers when nested inside another component that shares similar "state".

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently a known limitation because as far as I know there is no good way of telling css to only look at the nearest `x`. Maybe this will change in the future once we can use `:has` reliable everywhere.

However, one thing you can do is define both `ui-open:` and `ui-not-open:` variants explicitly which should result in the expected behaviour: https://codesandbox.io/s/quiet-resonance-yic9ty?file=/src/App.js
