### ISSUE TITLE
Usage with Preact and Typescript

### ISSUE THREAD

**Issue by umar-abdullahi** [tailwindlabs/headlessui#186]
Transition' cannot be used as a JSX component.
Its return type 'JSX.Element' is not a valid JSX element.
Type 'Element' is missing the following properties from type 'Element': nodeName, attributes, children

'Transition.Child' cannot be used as a JSX component.
Its return type 'JSX.Element | null' is not a valid JSX element.
Type 'JSX.Element' is not assignable to type 'preact.JSX.Element'.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We are focusing on React, and we are using `@types/react` and `@types/react-dom`.
So if your types don't match then I think that you somehow have to replace those with preact compatibility ones.

I am not sure on how to do this, but since you can replace react/react-dom with some preact and webpack magic, I believe that it should be possible for the types as well.

**Comment by Schlumpf9** [comment]
+1 for Preact Support. 
It's normally not that big step to support Preact in conjunction with React. But it saves up to 30% package size in my projects...

**Comment by uriafranko** [comment]
Definitely +1 for Preact support.

It's a super useful and popular tool as a replacement.

**Comment by abrhim** [comment]
+1 - support for this would be great :D

**Comment by pedrodesu** [comment]
+1

**Comment by roj1512** [comment]
Need this.
