### ISSUE TITLE
Using tab key to move focus with tabs component is confusing

### ISSUE THREAD

**Issue by mitar** [tailwindlabs/headlessui#1881]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

For example: v1.7.2

**What browser are you using?**

Chrome

**Reproduction URL**

This is observable on the first example at https://headlessui.com/vue/tabs

**Describe your issue**

The way how Tabs component deals with focus changing is confusing. The issue is that the `Tab` components get focus and not `TabList` component. So, the issue is that when the focus outline for focused element is drawn it is only drawn around `Tab` component and not around the whole `TabList` component. So I would suggest that:

* Or focus is configured on the `TabList` component (`tabindex=0`) so that the user sees that focus is on the whole list of tabs and that pressing tab again would move focus away from list of tabs. So they might then try to use arrow keys to move between tabs.
* Or focus is kept on `Tab` but it is allowed that tab key moves to the next `Tab` component (so no `tabindex=-1` on other components). Then the user gets the usual experience of seeing outline around the first `Tab` component and moving focus to the next one is done using tab key. Otherwise there is no indication that they should switch to arrow keys.

I do wonder why is user required to use arrow keys to switch between tabs at all, and it is not done on tab/focus key. So I worry that users will not realize that they have to use arrow keys instead of the tab key to change between tabs. And focus outline which is drawn only around one `Tab` is contributing to this confusion.

In `manual` mode I would expect that I can move using tab between `Tab` components (so the second option above). In regular mode, I would expect that outline is over whole `TabList` (so the first option above).

Workaround I am currently using is to suppress browser's outline and to draw outline on `TabList` myself using `:focus-within`.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are following the implementation of native tabs (e.g. in macOS) and also the Tab implementation described in https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1834413/192997814-7c5f938d-cac3-40b6-88e6-5b51a5fed204.png">

The short answer to all your questions is: because accessibility reasons.

The longer answer:

Imagine that you have 50 tabs, and you are a keyboard user, if you now want to go from your active tab to the content after the tabs you can press the <kbd>tab</kbd> key twice on your keyboard, first to focus the `Tab.Panel` and a second time to go past it.
If we implemented tabs so that pressing <kbd>tab</kbd> goes to the _next_ tab, then you are required to tab 49 more times so that you can finally reach the last Tab, then press <kbd>tab</kbd> to go to the panel, then one more time to go past it.

The same pattern is found in many other (native) components, for example the `<input type="radio"/>` you will only be able to focus the very first radio input (or the selected one), pressing <kbd>tab</kbd> again would jump to the next field (or focusable element). Once you are focused on a `<input type="radio"/>` you can use your arrow keys to change the selection of the selected radio input.

The idea behind tabs is the moment you change a `Tab` then the content (inside the `Tab.Panel`) loads immediately. However there are scenario's where your `Tab.Panel` contains expensive components to render and then just using arrow keys would give you a non-ideal user experience because the UI could be blocked while you are simply trying to navigate. The `manual` prop then allows you to _not_ render those `Tab.Panel` components until you are ready to activate a `Tab`.

We have no plans of changing all of this behaviour right now since this is already following best practices from both native OS implementations and from the WAI-ARIA best practices recommendations. 

But I hope the reasoning explained here makes sense to you. 

You also could indeed apply a `:focus-within` on the `Tab.List` if you want to change the styles of the `Tab.List` when a `Tab` is focused.

**Comment by mitar** [comment]
Thank you for taking time for such a detailed explanation. I think I agree with you that when user knows that they just focused a tab, then they might know to move around with arrow keys. But native implementations have an advantage that user is familiar how they look. On the web, tabs can have much diverse design and user might not realize that they are in tab selection.

I hope that standard is really made in a way that people are familiar with this behavior. To me it was surprising (but maybe because I have only 2-3 tabs).

I still think that in `manual` mode there should be some visual hint that it is in manual mode and that you have to press enter to select, otherwise user might wait thinking something is loading but then realizing it is not and is waiting for them to do an action.

Anyway, I learned something new today. Thanks.

**Comment by demir10x** [comment]
I didn't wanted to add the outline with `tab` keyboard key. So, I ended up changing the behaviour by adding ` className="focus-within:outline-none"` to the `tab` elements being render. 
Here is the code if someone wants to get rid of this behaviour. 
`<Tab key={list} className="focus-within:outline-none">
								{({ selected }) => (
									<div className="flex flex-col ">
										<span className="py-1.5 px-2">{list}</span>
										{selected && <span className="border-t-1 rounded-t-lg border-primary"></span>}
									</div>
								)}
							</Tab>`
