### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/@headlessui_vue.js?v=6461a12c' does not provide an export named 'DialogPanel'

### ISSUE THREAD

**Issue by tylerprimmer** [tailwindlabs/headlessui#1902]
**What package within Headless UI are you using?**

@headlessui/vue dialogpanel

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Chrome

**Describe your issue**

Getting an error in the console for the dialog panel with version 1.7.3 
Uncaught SyntaxError: The requested module '/node_modules/.vite/@headlessui_vue.js?v=6461a12c' does not provide an export named 'DialogPanel'

I have pulled the code directly from https://headlessui.com/vue/dialog into my new project.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

It is definitely exposed, but my guess is that you recently updated to a newer version but that vite has a stale cache.

Some things to try:
- Clear all (local) caches 
- remove `node_modules`
- re-install
- restart server

If none of that worked, then please open a new issue with a minimal reproduction repo attached so that we can debug it and see what's going on.
