### ISSUE TITLE
Modal: hitting escape does a refocus

### ISSUE THREAD

**Issue by Zerebokep** [tailwindlabs/headlessui#1903]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.3

**What browser are you using?**

Chrome

**Describe your issue**

When hitting the escape button to close a modal the first available button on the page gets focused, I don't think this is intended. If it is intended, could you please add an option to disable this focus? Thank you.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It should re-focus the button that initially opened the Dialog.
Can you provide a minimal reproduction repo that showcases the issue?

**Comment by Zerebokep** [comment]
Ahh, that makes sense, it's indeed the button which opened the dialog. Is there a way to disable that behaviour? Or should I go the ref/blur way?

**Comment by RobinMalfait** [comment]
We do that for accessibility reasons. So imagine you are tabbing through the page, use the button, a dialog opens and you can do whatever you need to do. Once done we restore the focus so that you can continue where you left off.

We don't have a built-in way to turn it off, but you should be able to move the focus yourself if you want something else to be focused.

Hope that helps!
