### ISSUE TITLE
Dialog Content is not scrollable on mobile

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [tailwindlabs/headlessui#1911]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.0

**What browser are you using?**

iOS Safari, Responsive Mode on Chrome (emulating an iPhone 12

**Reproduction URL**

n/A

**Describe your issue**

Hey Guys,
i use the Dialog Module to create preview from a cooking-recipe. On Desktop all works fine. If i browse and open the Dialog on mobile or over the Chrome responsive Emulator, i cant scroll in the Dialog. I also created a test HTML element that says "overflow:scroll". Unfortunately, scrolling doesn't work there either. Want can i do? I use Tailwind for CSS.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Not being able to scroll was fixed in 1.7.1 so please update to at least that version. If that doesn't work for you then please create a minimal reproduction repo and open a new issue with that information attached.

Also please let us know which version of iOS you are using. E.g.: iOS 12.4 and below don't have proper `transitionend` event support and won't work properly with the `Transition` component.
