### ISSUE TITLE
Closing Dialog cause the app to be freezed in iOS 12.4

### ISSUE THREAD

**Issue by nguyend-nam** [tailwindlabs/headlessui#1912]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

^1.6.6

**What browser are you using?**

Safari

**My issue**

I tested both [issue 1517](https://github.com/tailwindlabs/headlessui/issues/1517)'s [dialog](https://headlessui-react-git-fix-issue-1517-tailwindlabs.vercel.app/dialog/dialog) and [modal](https://headlessui-react-git-fix-issue-1517-tailwindlabs.vercel.app/transitions/component-examples/modal) on Xcode simulator's iPhone 6 with **iOS 12.4**, and they both cause the app to be freezed **after** I close the modal. With the [headlessui document site](https://headlessui.com/vue/dialog), when I open the sidebar and then close it, I cannot interact the the site's elements anymore. I think that the `<div>` element covering the whole screen when the modal is opened is still there when I close the modal.

**Comment by thecrypticace** [comment]
Hey! So this one happens because, while iOS 12.4 supports transitions, it doesn't support transition _events_ which our Transition component relies on. This means that when a transition starts we have no way of knowing when it ends (or even _if_ it ended correctly or was cancelled — which can be caused by things like phone calls).

Given that the last update to iOS 12.4 — for devices that can't go to iOS 13 — was a little over 3 years ago (and iOS 12 was just over 4 years ago) — it is extremely unlikely that we'll spend time on any kind of workaround for this when it is supported in all other browsers (including iOS 13). Sorry we can't be of more help here.
