### ISSUE TITLE
Typecheck performance issue with React

### ISSUE THREAD

**Issue by ArnaudBarre** [tailwindlabs/headlessui#1923]
**What package within Headless UI are you using?**

`@headlessui/react@1.7.3`

**Reproduction**

One project file with code from https://headlessui.com/react/combobox#basic-example.

<details>
  <summary>tsconfig.json</summary>

  ```json
  {
    "include": ["combobox.ts"],
    "compilerOptions": {
      "noEmit": true,
      "lib": ["ESNext", "DOM", "DOM.Iterable"],
      "module": "esnext",
      "target": "esnext",
      "jsx": "react-jsx",
      "skipLibCheck": true,
      "moduleResolution": "node",
      "allowSyntheticDefaultImports": true,
      "strict": true
    }
}
  ```
</details>

**Describe your issue**

The following screenshot are generated by using `tsc --generateTrace traces` and loading them into `about://tracing/` in Chrome

<img width="1637" alt="Screenshot 2022-10-15 at 16 28 29" src="https://user-images.githubusercontent.com/14235743/195991799-5627bd1e-eadb-447f-9653-0fcffd8ac2de.png">

You can see a `Wall time` of 1.4s, which is a lot for one component.

I was able to identify one core problem: `PropsOf`.
Changing: `export declare type PropsOf<TTag extends ReactTag> = TTag extends React.ElementType ? React.ComponentProps<TTag> : never;` by `JSX.IntrinsicElements[TTag]` gives this:

<img width="1792" alt="Screenshot 2022-10-15 at 16 39 50" src="https://user-images.githubusercontent.com/14235743/195992416-bdc7b2b2-4924-4ad3-8b41-b552d63f084b.png">

I'm not totally sure if it's totally safe, but it worth investigating into changing some internal types to avoid TS completely resolving all the attributes of all raw tags. I'm still new to the subject, (got into it via this [Twitter thread](https://twitter.com/s4chinraja/status/1570658634039984128)) but I'm pretty sure there is another pattern in the types that breaks the lazy resolution of HTML attributes types, because 600ms is still a lot, most components are in the order of tens of ms in my codebase)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The problem with replacing `export declare type PropsOf<TTag extends ReactTag> = TTag extends React.ElementType ? React.ComponentProps<TTag> : never;` with `JSX.IntrinsicElements[TTag]` is that you loose the available props from other React components.

We want to be able to support this:
```js
<Menu as={MyStyledMenu} somePropThatExistOnTheMyStyledMenuComponent="123" />
```

While these numbers aren't ideal, the good part is that this doesn't slowdown the actual production code, this is mainly in development. 

One question I have is, are you actually seeing issues while developing your app(s) with Headless UI or were you just interested in optimizing it (because of that Twitter thread)?
Because I personally never ran into it because all these typechecks and what not are executed in the background.

I'm not 100% sure what _we_ can do specifically to make these types faster. One thing we can do is not provide any props from the native html elements or passed in component via the `as` prop, but I think that I would personally prefer having (slow) code completion and typechecks than none at all. 

As a side note: with the latest release of TypeScript 4.9 they did some performance improvements as well: https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#performance-improvements

We also have some open issues where some users want to see our types being exposed, so there is a chance that we will revisit some (most?) of these types anyway and hopefully we improve the performance with those PRs in the future as well. But for now I think I'm going to close this one as a won't fix — unless you are running into actual development issues then feel free to comment here or open a new issue (I'm more likely to see new issues)!
