### ISSUE TITLE
Vue listbox(Select) defaultValue not working

### ISSUE THREAD

**Issue by livoist** [tailwindlabs/headlessui#1931]
What package within Headless UI are you using?

@headlessui/vue

What version of that package are you using?

v1.6.4

What browser are you using?

Chrome

Describe your issue

My problem is that when I use listbox in tabs, when I switch tabs, the selected value of listbox will switch back to the default value, which is index = 0, and I hope he can remember the last selected content, And when I try to use `@updatede`, `:modelValue`, `:defaultValue`, it doesn't work and not find listboxButton `slot value name`.

![image](https://user-images.githubusercontent.com/37343447/194482384-5a9d8741-fa1b-4684-a041-2bed88a2d9bd.png)

![image](https://user-images.githubusercontent.com/37343447/194482069-c590f373-362b-46c6-a7dc-22b8d42d4d97.png)

thanks.

_Originally posted by @livoist in https://github.com/tailwindlabs/headlessui/discussions/1906_

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

One of the problems is potentially that `modelValue` becomes `undefined` and therefore the `value.name` results in `undefined.name` giving you that error.

It's hard to debug problems like this without looking at the actual code, so please create a minimal reproduction repo so that we can look at what's going wrong.
