### ISSUE TITLE
Dialog onClose not triggering from correct mouse event

### ISSUE THREAD

**Issue by bekworks** [tailwindlabs/headlessui#1932]
From the documentation (https://headlessui.com/react/dialog#dialog-panel)

**Dialog.Panel**
"... **Clicking** outside of this component will trigger the `onClose` of the Dialog component."

The dialog does not adhere to what is written here, and is not closing on the `click` event, but rather the `mouseup`  event.
This becomes problematic since you can close the dialog by clicking (and holding) the mousebutton inside the dialog, then drag the cursor outside of the dialog and let go of the button.

Imagine having a dialog where you have text that you need to highlight and copy, or maybe you have a drag and drop solution inside your dialog.

Could we please either get better control over events, or have this fixed?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We did switch back to `click` behaviour, so this should work in the latest version: 
- React: https://github.com/tailwindlabs/headlessui/blob/f66f4926c489fc15289d528294c23a3dc2aee7b1/packages/%40headlessui-react/src/hooks/use-outside-click.ts#L105-L124
- Vue: https://github.com/tailwindlabs/headlessui/blob/f66f4926c489fc15289d528294c23a3dc2aee7b1/packages/%40headlessui-vue/src/hooks/use-outside-click.ts#L91-L110

I tried to reproduce what you mean (https://038kum.csb.app/) but I can't figure out what you mean exactly. Seems to work as expected in Safari, Chrome and Firefox.

If this is still an issue for you, then:
1. Make sure you are on the latest version of Headless UI
2. You are actually using the latest version, and not a cached version (e.g.: remove `.next` or similar caches)
3. Open a new issue with a minimal reproduction repo attached so that we can take a look.

Hope this helps!
