### ISSUE TITLE
Transition + Dialog integration bug; UI does not rerender as expected

### ISSUE THREAD

**Issue by coryasilva** [tailwindlabs/headlessui#1933]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/headless-ui-dialog-react-hook-form-bug-fnuqp5

**Describe your issue**

TL'DR: React hook forms + `dialog` work fine.  Add in `transition` and UI and data misbehave.

1. Navigate to **[Reproduction URL](https://codesandbox.io/s/headless-ui-dialog-react-hook-form-bug-fnuqp5)**
2. Click "**Open Modal with Transition**"
3. Under the section titled "Bug: Form in Modal with Transition"
   1. Click one or more **checkboxes**
   2. Click "**Submit**"
4. Observe that the submitted **data and UI is not expected**
5. _Contrast results with the correctly functioning "Form not in modal" and "Form in Modal" forms._

Any help, guidance, or advise would greatly be appreciated -- this is a weird one and after reviewing the source code nothing screamed at me.  Perhaps a useMemo somewhere is not diffing deep enough?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Not 100% sure what's going on in react-hook-form, but it seems like it works fine with raw forms (so without react-hook-form). That makes me think that the issues exists in `react-hook-form` itself. 

After you select the first 3 only the last one is still selected, after that if you select them it seems to work fine and is consistent. My guess is that there is some syncing bug going on in react-hook-form.

Here is another test I did, if you do the following:
```diff
-  const { register, handleSubmit } = useForm();
+  const { register, handleSubmit, ...f } = useForm();
+  console.log(f.getValues());
```

Once you open it, the result looks like this:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1834413/196475029-79f6cf2c-22da-4933-b039-acf0553e6388.png">

So somehow it feels like it is unregistering.

Another thing I read in the docs is this part:

> To produce an array of fields, input names should be followed by a dot and number. For example: `test.0.data`
>
> - https://react-hook-form.com/api/useform/register

<img width="959" alt="image" src="https://user-images.githubusercontent.com/1834413/196475837-8369e7fc-ff1f-4040-ad55-8e8f6e67c5a0.png">

When you apply this rule, it does work~ish:
```html
<section>
  <input {...register("array.0")} type="checkbox" value="1" />
  <input {...register("array.1")} type="checkbox" value="2" />
  <input {...register("array.2")} type="checkbox" value="3" />
</section>
```

Because this is the result:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1834413/196476108-e72cfd7b-8da7-41f0-bf19-411ea803a2e4.png">


---

This is without react-hook-form: https://codesandbox.io/s/headless-ui-dialog-react-hook-form-bug-forked-tqsvpq?file=/src/App.js


Hope this helps!

**Comment by coryasilva** [comment]
@RobinMalfait I have a workaround for this but the [discussion on the react-hook-forms repo](https://github.com/react-hook-form/react-hook-form/discussions/9250#discussioncomment-3922607) is interesting. I will do some learning and try to report back if I can definitely find the issue.

**Comment by simontaisne** [comment]
I'm having the exact same issue with `react-hook-form` in `Dialog` + `Transition` 🤔 Any finding @coryasilva?
