### ISSUE TITLE
SSR error with <Menu.Button>: Prop `id` did not match.

### ISSUE THREAD

**Issue by ShaunDychko** [tailwindlabs/headlessui#1961]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.3

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/ShaunDychko/headlessui-reproduce-menu-button-error

To reproduce
1. clone the repo
2. `npm run develop`
3. visit `http://localhost:8000`
4. inspect the browser console.

**Describe your issue**

The console logs the error:
```
Warning: Prop `id` did not match. Server: "headlessui-menu-button-:Rkp:" Client: "headlessui-menu-button-:R2j5:"
    at button
    at eval (webpack-internal:///./node_modules/@headlessui/react/dist/components/menu/menu.js:23:3867)
    at C (webpack-internal:///./node_modules/@headlessui/react/dist/internal/open-closed.js:8:255)
    at eval (webpack-internal:///./node_modules/@headlessui/react/dist/components/menu/menu.js:23:2487)
    at MyDropdown
```
This occurs when Gatsby's `DEV_SSR` flag is enabled in `gatsby-config.js`, which causes server side rendering when the page is refreshed. It occurs with `react@^18`, but **not** with `react@^17`. It's probably related to https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/hooks/use-id.ts

I believe this causes React to re-render the page, which is consequential since it clears the cache from [RTK Query](https://redux-toolkit.js.org/rtk-query/overview) and causes dynamic UI elements to flash between states while they're waiting for server data.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

When you are using React 18, then we are using the native `useId` hook exposed by React. I believe that this is a Gatsby bug with React 18 or it is part of your setup somehow (I'm not too familiar with Gatsby itself).

For example, if you replace the `MyDropdown` component with:

```js
function MyComponent() {
  let id = `my-id-${React.useId()}`
  return <div>{id}</div>
}

// ...

<MyComponent />
```

Just doing this without any Headless UI at all will run into the same issue:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1834413/198902401-dd768b4b-a118-4f90-8630-dc46ff487b2a.png">

Which means that I'm afraid that there is nothing we can do in Headless UI to solve this, since we _do_ want to keep using the native `useId` hook whenever possible.

**Comment by CSFlorin** [comment]
same in Remix

**Comment by dmexs** [comment]
It looks like this was fixed in react here: https://github.com/facebook/react/pull/25713

It doesn't look like there are any major react releases following this fix. Can anybody give guidance on how to work around this using canary or other releases of react?

**Comment by CSFlorin** [comment]
Nice find @dmexs Looks like you can do something like `npm update react@canary react-dom@canary` per https://react.dev/blog/2023/05/03/react-canaries and https://react.dev/community/versioning-policy#canary-channel
