### ISSUE TITLE
Loss of the ability to scroll when returning to the old page when the modal is active

### ISSUE THREAD

**Issue by mirzobedil** [tailwindlabs/headlessui#1985]
When the dialog is active and I press the back button from the browser, `overflow:hidden;` remains for the `html` element on the opened page, and it loses the ability to scroll. This is happening to me when two modals are active at the same time. In Vue3

**Comment by mirzobedil** [comment]
![image](https://user-images.githubusercontent.com/45965774/199979490-22672b83-6b15-4b60-8494-b9ecf1f93d51.png)
In this situation, when I click **Confirm**, I get a redirect on the router and I am returned to the signin page, in this situation, in the `html` element, `overflow:hidden;` the style is stuck.

**Comment by adamwathan** [comment]
Hey! Can you provide a reproduction? Without one unfortunately we can't help.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It looks like you are using multiple modals, if you are please make sure that you either nest one modal in the other modal (so that there is a hierarchy), or make sure that only 1 modal is open at the same time. Right now multiple open modals are not supported.

If something else is happening, then please open a new issue with a minimal reproduction repo attached that shows the issue.

**Comment by mirzobedil** [comment]
Of course, thanks for answer 🤝.
