### ISSUE TITLE
Transition afterLeave not being called

### ISSUE THREAD

**Issue by ashlimx** [tailwindlabs/headlessui#1986]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.4 (w/ React v17.0.2)

**What browser are you using?**

Brave | FireFox | Edge
Happens on all 3 for me

**Reproduction URL**

https://github.com/ashlimx/headlessui-bug
for css:
```
npx tailwindcss -i ./src/index.css -o ./public/app.css --watch
```

and react:
```
npm start
```

**Describe your issue**

Scroll to the bottom and on the right there should be an unstyled "Open Modal" button
Clicking it opens the modal, and pressing the x button should close the modal. However after closing the modal the page is broken. You can't click on the button again for example to re-open the modal.

This issue I had resolved a few months ago when I developed this by using the `afterLeave` hook on the component's Transition. See Modal.js
However it looks like `afterLeave` is no longer being called. I don't know why.

**Comment by ashlimx** [comment]
@RobinMalfait I'm also aware that the way I'm accomplishing what I want is probably not the best so if you want to suggest an alternative the accomplishes the exact same thing and looks exactly the same to the end user, that would be much appreciated 😅

I figure that I probably shouldn't *need* beforeEnter/afterLeave for what I actually want...

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `afterLeave` callback will be called if all transitions are done. But create react app isn't playing nicely with Tailwind just because they don't want you to touch / change the postcss.config.js file. They also do a lot of things behind the scenes.

Instead of using create react app, I would recommend to use vite instead.
If you don't want to switch immediately, then you can also apply this diff that ensures that the correct css is generated outside of create react app:

```diff
- <link href="app.css" rel="stylesheet">
+ <script src="https://cdn.tailwindcss.com"></script>
```

This will use our CDN and bypasses all the odd things in CRA.

**Comment by ashlimx** [comment]
@RobinMalfait I just used create react app for the min reproduction code. The actual app I am working on is a Laravel 9 + Jetstream + Inertia w/react app using Vite. It happens there as well.
