### ISSUE TITLE
Listbox (Select) renders invalid hidden inputs by adding an unnecessary `readonly`

### ISSUE THREAD

**Issue by dgolosov** [tailwindlabs/headlessui#1990]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.3

**Describe your issue**

Listbox (Select) renders invalid hidden inputs by adding an [unnecessary](https://html.spec.whatwg.org/multipage/input.html#do-not-apply) `readonly` attribute.

<img width="1205" alt="Screen Shot 2022-11-08 at 14 22 56" src="https://user-images.githubusercontent.com/14894850/200565925-bed7ea35-41ec-4eb2-b5ad-c28569780b49.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I believe that in the real world all of these components work fine as-is and that some tools are just very loud about some "rules" around this.

If this is an actual problem for you (meaning, your application doesn't work), then please provide a minimal reproduction repo that proves that this is an actual issue.

When you remove these `readOnly` values, then you will get some React warnings (and we want to keep the React & Vue versions similar as possible). An example warning of React looks like this:

> Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

- We won't be able to use `defaultChecked` because then it will only be set initially, even though it should reflect the actual value.
- We don't want to use `onChange` because we already know the value and don't want to change it from within the checkbox (aka, it is not the source of truth).

Hope this helps!

**Comment by dgolosov** [comment]
Thanks @RobinMalfait. Yes, this is definitely not a blocker. It is quite enough for us to know that there are some reasons for this and we can just ignore it in our tests.
