### ISSUE TITLE
`Listbox` does not trigger a form's `onChange` when using React Hook Form's `Controller` (but native `select` does)

### ISSUE THREAD

**Issue by bennettdams** [tailwindlabs/headlessui#2003]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

v1.7.4

**Reproduction URL**

https://codesandbox.io/s/rhf-onchange-with-headlessuis-listbox-ce917d?file=/src/App.tsx

**Describe your issue**

I am not sure if this is a Headless UI issue, but this is my best guess.

Using the `Listbox` together with React Hook Form does not fire the form's `onChange`.

Using a native `select` with the same setup does fire the `onChange` though, that's why I created the issue here and not in the RHF repo.

---

In my reproduction you can see that the form is supposed to submit when the selection changes. Here, it logs to console, e.g.:

![image](https://user-images.githubusercontent.com/29319414/200953926-e1e0a209-6235-4da6-bbe6-e83fd9dfb1d9.png)

In the UI there are two selects: The first is via `Listbox`, the second is with a native `select`.
When selecting an entry via `Listbox`, the value changes, but the form is not submitted (unexpected).
When selecting an entry via the native `select`, the value changes and the form is submitted (as expected).

Code for reference, see CodeSandbox for full code:

```tsx
function SelectNative({
  selected,
  onChange,
  name
}: {
  selected: string;
  onChange: (newSelected: string) => void;
  name: string;
}) {
  return (
    <select
      value={selected}
      onChange={(newSelected) => onChange(newSelected.currentTarget.value)}
      name={name}
    >
      {people.map((person) => (
        <option key={person.id} value={person.id}>
          {person.name}
        </option>
      ))}
    </select>
  );
}

function SelectWithListbox({
  selected,
  onChange,
  name
}: {
  selected: string;
  onChange: (newSelected: string) => void;
  name: string;
}) {
  return (
    <Listbox value={selected} onChange={onChange} name={name}>
      <Listbox.Button>
        {people.find((person) => person.id === selected)?.name}
      </Listbox.Button>
      <Listbox.Options>
        {people.map((person) => (
          <Listbox.Option key={person.id} value={person.id}>
            {person.name}
          </Listbox.Option>
        ))}
      </Listbox.Options>
    </Listbox>
  );
}
```

**Comment by alex-page** [comment]
I have the same problem with `ComboBox`

**Comment by bennettdams** [comment]
The user @leapful [came up with a solution](https://github.com/react-hook-form/react-hook-form/discussions/9359#discussioncomment-4131515) where the native `onChange` even is dispatched manually as a workaround.
Should this maybe be part of the `Listbox` (and other?) components?

```tsx
  const ref = React.useRef<HTMLSelectElement | null>(null);

  return (
    <>
      <select style={{ display: "none" }} ref={ref} />

      <Listbox
        value={selected}
        onChange={(newSelected) => {
          console.log("Listbox onChange internal: ", newSelected);
          onChange(newSelected);
          if (ref.current) {
            ref.current.dispatchEvent(new Event("change", { bubbles: true }));
          }
        }}
        name={name}
      >
```

**Comment by adriand** [comment]
@alex-page the solution posted by @leapful works for the Combobox too.

`const ref = useRef<HTMLSelectElement | null>(null);

  return (
    <>
      <select style={{ display: "none" }} ref={ref} />
      <Combobox
        as="div"
        value={selectedOption}
        onChange={(selected: any) => {
          setSelectedOption(selected);
          if (ref.current) {
            ref.current.dispatchEvent(new Event("change", { bubbles: true }));
          }
        }}
        name={props.name}
        id={props.id}
      >`

**Comment by thecrypticace** [comment]
Hey, so the reason this works with native selects is because the browser-native select is bubbling it's native `input` and `change` events which is then firing the form's `onChange` handler because React is honoring the event bubbling.

Headless UI is not alone is not firing change events for non-native-form controls. You can see an example I've added here that adds React Select to your code sandbox which works the same way as Headless UI: https://codesandbox.io/s/rhf-onchange-with-headlessuis-listbox-forked-416j84?file=/src/App.tsx

Headless UI does use hidden form elements when you provide a `name` prop but changing the values of these do not trigger change events in any browser and we think it's best to preserve that behavior. Firing the change event ourselves would also be a bit complicated because:
1. You can't dispatch a `change` event from a hidden input directly — at least not in all browsers. Admittedly this could also just be a React limitation because it does effectively re-implement the event handling system itself but I'm not sure.
2. We would need to make sure `event.target.value` worked and made sense. For instance, should `value` ever allowed to be an object in that case or would that cause problems? You can't in normal HTML so it probably shouldn't. But then how would we know what value to put there if the `Listbox.Option`'s value was an object?

Ultimately I think that it's either the job of React Hook Form to dispatch these events to the nearest form (if it even can) or to use the workaround's like have been provided in this issue.

**Comment by adriand** [comment]
Thanks for the update @thecrypticace.

One thing I'll note for anyone who reads this thread in the future: if you use the workaround that I used and mentioned above (the hidden `select`) note that for whatever reason, the hidden elements that this component creates when you supply a `name` prop will no longer be submitted as part of form data. At least, that's what happened to me. So if you try this workaround, be advised that if this component is inside a `<form>` tag (or in my case, a Remix `Form` tag), you may find that your submitted data no longer includes what you expect.

**Comment by StevenBendell** [comment]
> Thanks for the update @thecrypticace.
> 
> One thing I'll note for anyone who reads this thread in the future: if you use the workaround that I used and mentioned above (the hidden `select`) note that for whatever reason, the hidden elements that this component creates when you supply a `name` prop will no longer be submitted as part of form data. At least, that's what happened to me. So if you try this workaround, be advised that if this component is inside a `<form>` tag (or in my case, a Remix `Form` tag), you may find that your submitted data no longer includes what you expect.

How do you get this to be included in a remix form?
I've tried like this:

`export const AdvancedListbox = ({
  onChange: controlledOnChange,
  value: controlledValue,
  defaultValue,
  children,
  name,
  ...rest
}) => {
  const ref = useRef(null);
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);

  return (
    <>
     <select name={name} style={{ display: "none" }} ref={ref} />
      <Listbox
        onChange={
          controlledOnChange ||
          ((value) => {
            console.log(ref.current)
            console.log(value)
            setUncontrolledValue(value);
            if (ref.current) {
              ref.current.dispatchEvent(new Event("change", { bubbles: true }));
            }
          })
        }
        name={name}
        value={controlledValue || uncontrolledValue}
        {...rest}
      >
        <div className="relative">{children}</div>
      </Listbox>
    </>
  );
};
`
