### ISSUE TITLE
Pressing tab on combobox unexpected behavior

### ISSUE THREAD

**Issue by KevinBatdorf** [tailwindlabs/headlessui#2017]
**What package within Headless UI are you using?**

@headlessui/react the Combobox

**What version of that package are you using?**

Bug is visible on demo page

**What browser are you using?**

Chrome Version 107.0.5304.87 (Official Build) (arm64)

**Reproduction URL**

https://headlessui.com/react/combobox

**Describe your issue**

When hovering over an item and pressing the tab key, the item hovered is selected. I would expect it to not select anything and instead lose focus, keeping the previous item selected. The same happens when using the arrow keys then pressing tab

I referenced a few places and couldn't find anything to indicate the tab key should have this behavior e.g. https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

**Comment by mangej** [comment]
Maybe it's not standard, but I think it's kind of neat to have that behavior. I'm building a time-reporting application where the users need to fill in values in two comboboxes (project and activity). The users prioritise speed when reporting time and now they can confirm a selection and focus the next combobox with the Tab-key instead of Enter + Tab.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is expected behaviour, you can also see this behaviour on the very first example in the link you shared (https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html)

It's not 100% the same there because it doesn't happen on mouse hover, but it does happen when you use your keyboard to make an item active. In Headless UI we tried to make the mouse and keyboard behaviour as similar as possible (hence why we also explicitly expose `active` information to normalize that behaviour).

More information on the `tab` key: https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html#kbd_label_listbox


> ### Tab
> - **_Sets the value to the content of the focused option in the listbox._**
> - Closes the listbox.
> - Performs the default action, moving focus to the next focusable element. Note: the native <select> element closes the listbox but does not move focus on tab. This pattern matches the behavior of the other comboboxes rather than the native element in this case.


Because we normalize that behaviour, you also get it when you are hovering it because then you make a combobox option active.

A few things to note:

- When you are tabbing through your form inputs, you should never run into this issue because the value doesn't change when the combobox is still closed (and we currently don't open the combobox on focus in the combobox input). 
- You can always press `esc` once the combobox is open or click outside of the combobox (this should be true across all our components).
- This should only happen using your mouse if you are actively hovering on an item, the moment you move your mouse away from the combobox the active item is gone and therefore a tab won't result in setting this new value.

Hope this helps!

**Comment by KevinBatdorf** [comment]
> you can also see this behaviour on the very first example in the link you shared

It's notable that this behavior happens on keyboard navigation only and not on mouse hover (as you pointed out). But I understand your perspective here and appreciate the added context. Thanks

**Comment by afercia** [comment]
> This is expected behaviour, you can also see this behaviour on the very first example in the link you shared (https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html)

@RobinMalfait thanks for your feedback. I'm afraid that's the wrong example. That's the 'select only' combobox, which doesn't have an input field. The correct example is the 'Combobox With List Autocomplete": https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-autocomplete-list.html where the Tab key doesn't do anything. Thanks.
