### ISSUE TITLE
Usage in native ESM node environment

### ISSUE THREAD

**Issue by lannonbr** [tailwindlabs/headlessui#204]
So if I want to use the `@headlessui/react` package in a ESM context without bundling it again using something like webpack, the current settings in the package.json don't work. That said, in a local project of mine, I went into the module's directory in my node modules after installing the package and did two things to make it function as expected.

1) Rename `@headlessui/react/dist/headlessui.esm.js` to `@headlessui/react/dist/headlessui.mjs` as the .mjs extension is needed in Node.
2) add the [exports](https://nodejs.org/api/packages.html#packages_conditional_exports) field into the package.json with at least `import` as such which defines how Node in an ESM context should resolve this module when doing an import like `import { Transition } from "@headlessui/react"`:

```json
{
  "exports": {
    "import": "./dist/headlessui.mjs"
  }
}
```

And then the components would work properly when importing them in an ESM environment in Node. Now that said, my project is fully using ESM now, so I'm unsure on what would a project that bundles this package in with webpack or another bundler when in a CommonJS environment that is using the `import` statement / `import()` function, so I am not confident if my solution would work in all environment / bundlers.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We are currently focusing on the actual components. I would also like to take a look at the final result, but I don't want to start tweaking a bunch of configuration options. Behind the scenes we use `TSDX` which does all the heavy lifting.

For example `.mjs` is something that I don't want to do, because it is _not_ required by Node. It is only required if and only if you want to use the `ESM` build AND you don't have `"type": "module"` in your `package.json`.

If you are in a project that is fully `ESM` based, than I would recommend to use the `"type": "module"` approach over the `.mjs` approach.
