### ISSUE TITLE
KeepAlive component does not work with tabs

### ISSUE THREAD

**Issue by mitar** [tailwindlabs/headlessui#2111]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

Chrome.

**Reproduction URL**

https://stackblitz.com/edit/vue3-tailwind-emtuyt?file=src%2Fcomponents%2FHelloWorld.vue,src%2Fcomponents%2FFoobar.vue

Observe in console, that "mounted" is printed out every time you switch between tabs. Ideally, it would be printed out only once, the first time, and then activated from then on.

**Describe your issue**

One cannot use KeepAlive built-in component to cache tab components. It just does not cache them.

I know there is `unmounted=false` undocumented feature, but that one works slightly differently, namely it leaves DOM node in and just hides content with CSS. KeepAlive on the other hand removes content from DOM but keeps a reference around so that they can be re-inserted. Support for KeepAlive has been asked for few times already (#743, #1048), but I think it is a bug that it does not work with standard KeepAlive.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an interesting one! There are a few things happening here and I don't think we will be able to use the `KeepAlive` for this use case because I think the `KeepAlive` component just doesn't handle this.

Alright so for starters, the default behaviour of the `TabPanel` is that it is unmounted. To guarantee the correct DOM order, we insert a placeholder `span` instead. But as you mentioned the contents of the `TabPanel` is gone and state attached to `input` fields will be blown away.

You can use the `:unmount="false"` (we've updated the docs to include these) but it does indeed behave a little bit different compared to keeping a reference in memory. However, if you store `form` related data, then this will probably be preferred over the `KeepAlive` method because even if the DOM elements still exist in memory, they won't exist in the DOM and won't be submitted when submitting your form.

One thing we do with our components is try to make the API as nice as possible to use. For example you don't have to manually attach the `v-if` directives instead we typically return `null` from within the component if it should not be active while the `unmount` strategy is active. In case of the `TabPanel` we return a `span` so `KeepAlive` won't see this as something that should be cached.

My next idea was to detect the `KeepAlive` component as a parent of the `TabPanel` itself, and if we detect it, then we will just return `null` instead of the `span` placeholder. This is fine to do because the `KeepAlive` component will now act as a placeholder instead of the span. However, the `KeepAlive` component doesn't store/remember the contents if you return `null` and I think that this is where we have a problem because there is no way that I know that we can return "something" from within the `TabPanel` component to make the `KeepAlive` component happy.

So I think the `:unmount="false"` approach is the best thing we can do so far: https://stackblitz.com/edit/vue3-tailwind-jfk2n8?file=src/components/HelloWorld.vue

Hope that makes sense!
