### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by TinsFox** [tailwindlabs/headlessui#2151]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

"@headlessui/react": "^1.7.7",

**What browser are you using?**

Chrome@108.0.5359.124

**Reproduction URL**

https://github.com/CuillerIO/cuiller-admin/tree/%40headlessui/react-feedback

please checkout branch `@headlessui/react-feedback`

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

When accessing http://localhost:5178, the console will report an error `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

I found out that these errors are caused by https://github.com/CuillerIO/cuiller-admin/blob/%40headlessui/react-feedback/src/components/layout/header.tsx#L87~#L109

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/33956589/210782165-cde72ed2-267d-4784-916a-62d02880b915.png">
<img width="1816" alt="image" src="https://user-images.githubusercontent.com/33956589/210782803-b688dd26-00de-4f15-9513-6760ca4e8354.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2164, and will be available in the next release.

You can already try it (in a few minutes once the build is done) using `npm install @headlessui/react@insiders`.

The result now looks like this:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1834413/211294747-fa3d5c76-4f03-45a4-a52e-080ec9199897.png">
