### ISSUE TITLE
False positive warning shown when rendering Popover.Button as a fragment with a button in

### ISSUE THREAD

**Issue by booc0mtaco** [tailwindlabs/headlessui#2154]
**What package within Headless UI are you using?**

- @headlessui/react

**What version of that package are you using?**

- v1.7.5

**What browser are you using?**

Chrome

**Reproduction URL**

See Sandbox: https://codesandbox.io/s/silent-morning-xut942?file=/src/App.js

**Describe your issue**

When using `Popover.Button`'s `as` prop with a fragment, Rendering a simple `button` or any component that results in a renedered `button` will show the following warning.

`You are already using a <Popover.Button /> but only 1 <Popover.Button /> is supported. `

Related to https://github.com/tailwindlabs/headlessui/issues/2143, this seems like a false positive. Possibly related, this appears to happen in react 16.x but may not occur in react 18.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #2163, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders`.

I've updated your CodeSandbox with the latest insiders build: https://codesandbox.io/s/dreamy-euclid-wjbpd2?file=/src/App.js

**Comment by booc0mtaco** [comment]
Thanks for the quick turnaround!
