### ISSUE TITLE
Combobox loses focus when option is selected with mouse click

### ISSUE THREAD

**Issue by AnnaYuS** [tailwindlabs/headlessui#2155]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://user-images.githubusercontent.com/19432263/211062562-4c56cc35-8e83-4198-a8ff-97fed93f1845.mov

**Describe your issue**

Focus behaviour after an option is selected is different for keyboard and mouse interaction. I think when user selects option with mouse click the focus should stay on the input. At the moment the focus seems to go to the first tabbable element in the body.  
There is also a discussion on this problem: https://github.com/tailwindlabs/headlessui/discussions/1984

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We had this behaviour before, but that would trigger the virtual keyboard again once the input got focus on mobile so we removed that in #1732.

The problem is that we can't keep the focus in the input itself because a tap on the option would move the focus so the solution is to re-focus the `input` field but that causes mobile issues as seen in #1732.

Maybe we can further improve it by detecting when somebody is on mobile or not but not 100% sure if it is worth it because there are a lot of false positives in even trying to detect this: laptops with touch screens, iPads with a keyboard attached, ... so going to keep it like this for now because I think that opening the keyboard on mobile and scrolling the page a bit is far more annoying than this issue on desktop.

Hope this makes sense!
