### ISSUE TITLE
Uncontrolled RadioGroup does not trigger form's onChange in React

### ISSUE THREAD

**Issue by CSFlorin** [tailwindlabs/headlessui#2180]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**

https://stackblitz.com/edit/node-mhbppr?file=app%2Froutes%2Findex.tsx

**Describe your issue**

There are two groups of radios in the reproduction example:
* one using RadioGroup
* one using native HTML inputs of type radio.

When you click the RadioGroup options, nothing is logged in the console. When you click the native HTML input options, the event is logged.

**Comment by CSFlorin** [comment]
Here is how Radix handles this case:
https://github.com/radix-ui/primitives/blob/main/packages/react/radio-group/src/Radio.tsx#L147

**Comment by gloomweaver** [comment]
I would like to contribute

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

I'm going to close this as a `won't fix` right now, because it is a bit more complex than it seems to be, let me try to explain this. (We may reconsider this in the future, but not right now)

The short story is that the `RadioGroup` component is not a native component and you aren't interacting with native `input` fields. However we try to make sure that we encode your values in hidden inputs so that they are serializable and will just work when submitting forms using the native `form` element. 

Since we are not interacting with a real input, the only way to make the `onChange` work is by faking it. That's also what Radix does (as you mentioned in one of your comments).

This is also where things get complex. We encode the full `value` in multiple `input` fields so that they are parseable by `FormData` and also by most backend frameworks. This means that in your case an object of `{ id: 1, value: "Startup" }` will be encoded as:

```html
<input type="hidden" name="plan[id]" value="1" />
<input type="hidden" name="plan[name]" value="Startup" />
```

Now the question becomes, what do you want to expect when we fake a "change" event? 

- Do you expect a single dispatch, where the value is a JSON representation of the data (because those values are mainly string-based)? 
  - If we do this, then the "real" world, and this made-up `change` event won't be the same.
- Do you expect multiple dispatches for each "field" with the name & value attached?
  - This would be more correct, but would be confusing to get multiple events for a "single" change that a user made.
- Do you expect a dispatch with just a "checked" value and some identifier that we don't really know about?

Even if we ignore all of this, what if you rely on a property in the `event` that we forgot to set? 
What about all the other events that happen on a real input?

We could simplify this, and only bubble (fake) change events when your data is primitive based, like a simple string, number or a boolean value. But then when you switch to a more complex value all of a suddenly goes away and we have to try and answer the questions from above again.

So for now I think a won't fix is appropriate here since this would require a lot of tinkering to solve this in a proper way.

That of course doesn't really solve your problem right now, so I see a few options here for you:
1. You could use a `pull` based model instead of a `push` based model where you actively query the current state of the form. Since the value is encode in those hidden inputs this should result in the correct results. If this won't work for you, then it would be interesting to know you exact use case so that we can find a more appropriate solution. Here is an example where we query the form, but only on `submit`: https://stackblitz.com/edit/node-twce5j?file=app/routes/index.tsx
2. If you don't care about all the decisions we have to make in Headless UI, then we can give you that control. You can wrap your `RadioGroup` component that manually dispatches a change event in your own application while implementing the `onChange` function.
3. You can use native inputs instead of Headless UI.

Hope this makes sense!

Again, I'm just saying no today, we may revisit this later, but it requires way more thought than it initially seems. ❤️
