### ISSUE TITLE
Dialog component reset scrollY value to 0 on mobile

### ISSUE THREAD

**Issue by matimyrTSH** [tailwindlabs/headlessui#2198]
Hey fellows!

**Background:**
Recently faced with a problem which seems to be caused by the dialogue component. We have navigation on our site which set proper background values based on the scrollY value when we scroll the page and the dialogue component is triggered on the mobile, we got a 0 value which is false. 

Found that on the dialogue component when the isIOS method is truthy you declare a value for `window.scrollTo(0,0)`
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L126

**Steps to reproduce:**
1. Visit the Reproduction URL.
2. Open the page with mocked example.
3. Turn on chrome dev tools and toggle the device debugger.
4. Scroll down and open dialogue. 

To see the difference do the same in normal mode.

**Expected:**
- Don't reset the global value

**Here is a bunch of basic information:**
Used package: @headlessui/react
Used version: v1.7.7
Used OS: macOSMonterey
Used browser: Chrome
Reproduction URL: https://codesandbox.io/s/recursing-taussig-6v2s67?file=/src/App.tsx

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is sadly because iOS doesn't behave the same as normal desktop browsers and Android browsers behave. For accessibility reasons you should not be able to interact with elements behind the Dialog (because you can't escape the Dialog and you can think of it as a "separate" page that just happens to sit on top of the current one). To ensure that you can't scroll the background we add `overflow: hidden` to the `html` element and that works fine in most cases and disables scrolling.

Except for iOS...

On iOS we have to be a bit more clever which has its flaws sadly. The moment we apply the `overflow: hidden` on iOS then the page jumps because the navbar will jump into place and the page will be scrolled a bit. To counter act this we capture the scroll position first, scroll to the top (to counter act the jump) and later we restore the scroll position again once the dialog closes.

That sad, unless you know a very solid way to solve this in most cases, I'm afraid that I'm going to close this as a won't fix for now unless we have a better solution.

But for your use case their might be a better workaround for now. Since you won't be able to scroll once the Dialog is open you can't change the value of the scrollbar either. So what you can do is enable/disable the `useWindowScroll` hook and disable it once the Dialog is open. That will result in the value that is currently there without resetting due to changes applied in the Dialog itself. This will require some changes to the hook, but a quick work around is storing the last `y` value. E.g.: https://codesandbox.io/s/purple-glade-jw0b3o?file=/src/App.tsx

Hope this helps!
