### ISSUE TITLE
2nd Dialog Modal not getting focus to form elements on render.

### ISSUE THREAD

**Issue by gauravkrp** [tailwindlabs/headlessui#2205]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.7

**What browser are you using?**
Chrome on Mac

**Reproduction URL** - 
https://le723j-3000.preview.csb.app/ (Preview URL)
https://codesandbox.io/p/sandbox/youthful-dawn-le723j (CodeSandbox for actual Code)
https://www.loom.com/share/fa258a8273ef4bf5bdcfbc0ac906e456 (Video Recording of Issue)

**Describe your issue**

In my use-case, I need to use 2 modals, so creating them using Dialog and Transition components from the library. The first modal works fine. It has a button that triggers a second modal. Form elements in 2nd modal are not getting focus on render. You can watch the video (with sounds on) to see yourself. In a very weird manner, as soon as I click on any element outside the form element, and then click back on form elements, it gets focus and works. This issues has kept me stuck for a while. 

Please help me debug and find a solution

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We currently don't support multiple open Dialogs at the same time unless they are nested so that we can guarantee the correct order of closing them again when clicking outside or pressing escape. 

Here is an updated version where the second dialog is nested in the first one: https://codesandbox.io/p/sandbox/amazing-goldberg-ikgblp

Hope this helps!

**Comment by gauravkrp** [comment]
> 

Thank you @RobinMalfait for this. I somehow figured out the nesting solution and it works!

**Comment by Emiliano-Bucci** [comment]
@RobinMalfait Hi! But how we suppose to do it with global dialogs and specific dialogs? Can't be done this following the order in the dom tree? Because if I have global dialogs that sometimes must be opened from non global dialogs you're forcing us to add those dialogs inside the other ones, which is not ideal...
