### ISSUE TITLE
[Tabs] Next.js 13 SSR hydration error

### ISSUE THREAD

**Issue by OussamaFadlaoui** [tailwindlabs/headlessui#2220]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.8

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/festive-dubinsky-ffuc7w

**Describe your issue**

The most simple set-up for the Tabs component gives a hydration error when used in Next.js 13. Please refer to the minimal production link above.

**Comment by tangye1234** [comment]
1.7.7 works fine, 1.7.8 gets hydrated error issue

**Comment by MejanH** [comment]
you forgot to downgrade, I think. I upgraded all of my packages today and faced this. using pnpm.

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this!

I've merged in a fix for this which should hopefully resolve the problem. The culprit here is React v18's double rendering when in Strict Mode. It's _impossible_ for our components to be able to register themselves with React's public APIs because there is no preserved state or any stable identity across React's double renders and double rendering effect cleanup fires in a different order than if you were to unmount and remount normally.

We've been incrementally trying to work towards proper SSR support and fixing issues along the way and we made some progress on that in 1.7.7. As a result of this though, React now picked up on the fact that we are getting actual content from the server, tries to hydrate the tree, and it's at that point where the double rendering causes problems for us. In general side-effects during rendering are bad but sometimes that is the only option available to you because effects don't run during SSR. So side-effects are the only way to communicate on the server (and the behavior has to be *identical* on hydration). This hydration problem then manifests as a giant error in Next 13 apps displayed front and center during development.

I'll note that this problem _only_ affects development builds of React because double rendering does not happen in SSR or in production builds. In the end we ended up reaching into React internals that are only available in development builds. Hopefully this will work around these issues.

We'll work on getting a tagged release out soon but in the meantime you can test out the fix in our insiders build: `npm install @headlessui/react@insiders` — if you could give it a test and report back how things are working that would be fantastic!

Thanks again for reporting this. ✨

**Comment by jessereitz** [comment]
@thecrypticace your latest commit solved the issue for me; I haven't run into any problems with it at the moment (still waiting for a tagged release to actual deploy to prod).

It's funny, I was _just_ pulling my hair out trying to figure out what was going on then I saw you just merged your commit. Thanks for your work!
