### ISSUE TITLE
[Vue] <Dialog> and <Transition> causing bug with fixed and sticky elements on iPhone

### ISSUE THREAD

**Issue by vincentdorian** [tailwindlabs/headlessui#2232]
Hi there 👋

I stumbled across this issue using Headlessui in a Laravel-Inertia.js-Vue project of mine. The Dialog and transition components are utilized for a sliding sidebar menu and action modals. 

**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Firefox, Chrome, Safari

**Reproduction URL**

https://github.com/vincentdorian/headlessui-vue-bug-report.git

To reproduce, the project needs to be run on simulated iOS device (~iOS15.3) as seen in video.

**Describe your issue**

https://user-images.githubusercontent.com/60883844/215874463-7f74e531-d334-4acb-8b9b-a9405110f388.mov

I first noticed the bug when using the app on my phone (iOS 15.3). The problem occured on all three browsers I tested (Firefox, Safari and Chrome). Using an Android device, this does not seem to be an issue and using chrome dev tools to test smaller breakpoints also works fine. 

I have rebuilt a minimal Vuejs project which compares using the modal with and without a transition and have attached a screen recording when testing this on iOS simulation device. 

The app has a fixed navbar in the top-most layout layer (App.vue). In the page contents (<RouterView/>), there are a fixed footer and header bar that both are sticky and "stuck" to top and bottom respectively. Between the footer and header, there is list that is overflowing.

When opening a modal and the component gets mounted in the DOM via the portal, it somehow causes the sticky and fixed components to flicker and the contents that should be behind them flash over the layout components. I have tried this with and without using the transition component and it happens in both cases, only less bad. 

Looking forward to your replies.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I see the issue both with and without a Transition on my iPhone. I'm afraid this is just an iOS bug and there is not a lot we can do about it. However, you could structure your page a bit differently instead of using `sticky`, you could use `flex`.

Here is a very minimal example on how you can achieve that: https://play.tailwindcss.com/5kB2WzlJCe

The biggest difference is that you now can only "scroll" the scrollable area instead of the full page.

Hope this helps!
