### ISSUE TITLE
Combobox.Input component throw error if it's children is not a HTML input element

### ISSUE THREAD

**Issue by frozenluo** [tailwindlabs/headlessui#2235]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.8

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/boring-lake-5vo97g?file=/src/App.tsx

**Describe your issue**

1. click the input element
2. type any characters
3. error happens: `xx.setSelectionRange is not a function`
<img width="706" alt="image" src="https://user-images.githubusercontent.com/1532735/216001588-fda6e895-3243-4cb3-8c1a-998f96e9e66d.png">

Seem this issue was brought by #2153, for my project, there are several elements under `Combobox.Input` and the `data.inputRef.current` is not a valid HTML input.

Hopefully we could handle this case as well, thanks a lot.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is not the intended way of using the `Combobox.Input`. The `as` prop is exposed so that it is easier to use existing components you already have, for example:
```js
<Combobox.Input as={MyStyledInput} />
```

Instead of trying to to making the `Input` a div to add a `label`, wrap the input itself with a div and a label: https://codesandbox.io/s/lingering-wildflower-oerdsz?file=/src/App.tsx

```js
<Combobox>
  <label
    style={{
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: 12
    }}
  >
    <span>Input label:</span>
    <Combobox.Input />
  </label>
</Combobox>
```

Hope this helps!
