### ISSUE TITLE
Focus Trap bug not passed to newer dialog on stacked dialogs

### ISSUE THREAD

**Issue by neoighodaro** [tailwindlabs/headlessui#2251]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.7.7 (tested also on v1.7.9, the only version this bug is not present is <= 1.7.5)

**What browser are you using?**
Chrome, Safari & Arc

**Reproduction URL**
https://stackblitz.com/edit/vitejs-vite-xstzxe?file=src/App.vue

**Describe your issue**
Versions after v1.7.5 have this issue. When you have two (or more, i guess) stacked dialogs, the most current dialog does not get focus. 

For example, I have a simple modal category group list, there's a button to immediately open another dialog to create a category group. However, this new modal will not allow you click to update the input field in the new dialog. You have to first click somewhere else in the modal before you can then click the input field.

Hopefully, the example project shows you how this happens.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We do not support multiple Dialogs open at the same time if they are siblings (or further apart in the tree). If you want to have them open at the same time and stack them then they should be nested inside the other Dialog so that we can guarantee the order and how to close Dialog in the correct order.

If it worked on an older version than the behaviour was rather buggy or mere coincidence.

Hope this helps!

**Comment by neoighodaro** [comment]
Hello, unfortunately does not help as the second Dialog is not strictly a part of the first Dialog and there are instances where the second Dialog can be opened on it's own or as part of yet another Dialog. 

A use case would be a budgeting app where there's a modal to Create A Category. It's just a modal that has one input with the name of the category and a save button. This modal can be reached while using a create transaction modal, or from the list categories modal.

However, thanks for clarifying that it's not intended to be supported. Sad that it's a big part of my app and I have already invested heavily in that. I'd likely stick to 1.7.5 forever or until it makes sense to rewrite it to use something else.
