### ISSUE TITLE
Feature: Provide a Breakpoint API

### ISSUE THREAD

**Issue by mpvosseller** [tailwindlabs/headlessui#226]
Would it make sense to add a breakpoint API to headlessui to make it easier to handle breakpoint changes from the React/JS-side?

Was thinking it could offer a breakpoint context / hook to read the current breakpoint and also post an event on breakpoint changes to handle them imperatively as needed. I [implemented something like this here](https://stackoverflow.com/a/66031917/2316115) but I'm new to React and Tailwind CSS so I'm not sure if I'm taking the wrong approach. 

Feel free to just close if you consider this out of scope.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

I don't think it makes much sense to create such a component in the Headless UI codebase. 
Headless UI can be used without Tailwind CSS if you want, which means that a list of `sm, md, lg, xl, ...` breakpoints becomes meaningless for other users.

That said, we could still add such an API which is more generic and listens for all breakpoint changes. But at that point it might be better to implement that in user land since you can use the `matchMedia()` functionality and attach event listeners to it: https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
