### ISSUE TITLE
Listbox/Combobox multiselect: Active option change/navigation via keyboard breaks after one selection using mouse is being done

### ISSUE THREAD

**Issue by RIP21** [tailwindlabs/headlessui#2268]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.10

**What browser are you using?**
Chrome

**Reproduction URL**

[Video recording](https://share.cleanshot.com/5rstRt1D)
[Codesandbox](https://codesandbox.io/s/headless-bugs-ci0fb2?file=/src/index.tsx)

**Describe your issue**

If you have a tag picker meaning for each selection of the option it disappears and appears in selected items and you will do a selection using a mouse, after the first selection via mouse keyboard navigation of the options list is breaking. Both combobox and listbox.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We used to re-focus the `Combobox.Input` after you used your mouse to click on a `Combobox.Option` because technically you are blurring the `Combobox.Input` when you click on the `Combobox.Option`.

Later we got a bug report that this was very annoying on mobile, and it is! Because every time you re-focus the `Combobox.Input` the Virtual Keyboard would re-open. So we got rid of that part.

So now I re-added that feature, but only for non-mobile devices. Making some assumptions in the implementation (because I don't know a bullet proof way of detecting whether a Virtual Keyboard would pop up if we focus the `Combobox.Input`). This means that right now this won't happen on Android and iOS devices.

This should be fixed by #2272, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.

**Comment by RIP21** [comment]
That's beautiful! Thanks a lot!

**Comment by himynameisphil** [comment]
is it possible to make this optional? We don't always want the input refocusing.
