### ISSUE TITLE
Font error with Nextjs next/font and tailwindcss

### ISSUE THREAD

**Issue by ehsmsh** [tailwindlabs/headlessui#2287]
**What package within Headless UI are you using?**

@headlessui/react and @headlessui/tailwindcss

**What version of that package are you using?**

^1.7.11 and ^0.1.2

**What browser are you using?**

Mozilla Firefox

**Describe your issue**

Using new feature of nextjs for optimizing font load (next/font) with tailwindcss as it is described in nextjs docs, doesn't load the custom font on headlessui Dialog(Modal) as it seems to load the modal out of __next div.

If load the font in old fashion it could be solved by mentioning the custom font defined in tailwindcss config explicit in the modal, but with the new font feature it doesnt work too.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because you are scoping the font to the `__next` div, and the `Dialog` is rendered as a sibling (directly in the `body`).

You can inject it in the head itself so that all parts of the DOM are covered. More info: https://github.com/tailwindlabs/headlessui/issues/2225#issuecomment-1408460305
