### ISSUE TITLE
<RadioGroup> is not detecting the checked

### ISSUE THREAD

**Issue by amoralesdesign** [tailwindlabs/headlessui#2302]
Package: @headlessui/vue
Version: ^1.6.7
Reproduction URL: https://stackblitz.com/edit/nuxt-starter-kkita4?file=app.vue

As you can see in the link, the <RadioGroup> component for Vue does not work because it does not detect well the checked of the component itself.

However, if you remove from the code these two lines:
**:modelValue="selectedPaymentMethod"
@update:modelValue=""(value) => clickPaymentMethod(value)"**

It will work, what am I doing wrong?
As far as I see in [the documentation](https://headlessui.com/vue/radio-group) it is correct to use modelValue and update:modelValue.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you don't use the `:modelValue` / `@update:modelValue` on the component, then _we_ control the component so therefore it works fine. The moment you add these then _you_ are controlling the component.

What's happening here is that _you_ are controlling the component and you are emitting the changed value (up the tree). You can see that the change is detected because the log `clickPaymentMethod` will be logged in the console. The issue is that you are not doing anything with the value, you are just emitting it up the tree, however, there is no parent of the `App.vue` that's controlling that value and therefore nothing is happening. 

So you either have to:

- Make sure there is a parent that controls the value and listens for these event listeners
- Don't emit up the tree, and control it in the App.vue itself

For the last example, you can do this:

```diff
 const clickPaymentMethod = (paymentMethod: any) => {
    console.log('clickPaymentMethod');
-   emits('selectPaymentMethod', paymentMethod);
+   selectedPaymentMethod.value = paymentMethod;
 };
```

Hope this makes sense!
