### ISSUE TITLE
jest - console error when using transitions in 1.7.12

### ISSUE THREAD

**Issue by szamanr** [tailwindlabs/headlessui#2314]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.12

worked without issues on v1.7.8

**What browser are you using?**

jest = test runner which renders content using jsdom

**Reproduction URL**

i cannot provide a reproduction. it's not realistic to require someone spend hours on providing a repro, especially if something breaks following a patch upgrade. here's the simplified version of the code i'm using:

Modal.tsx:
```
export const Modal = () => {

const [showModal, setShowModal] = useState(true);

return (
<Transition afterLeave={onClose} appear show={showModal}>
  <Transition.Child
    as={Fragment}
    leave="transition-all duration-300"
    leaveFrom="transform opacity-100 translate-y-0"
    leaveTo="transform opacity-0 -translate-y-16"
  >
    <span>hi!</span>
    <button onClick={() => setShowModal(false))}>close</button>
  </Transition.Child>
</Transition>
);
}
```

Component.tsx:
```
const [showModal, setShowModal] = useState(false);

return (
  <div data-testid="modalContent">
    <button onClick={() => setShowModal(true)}>view more</button>
    {showModal && <Modal />}
  </div>
);
```

test code:

```
import { screen, render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

render(<Component />);

const viewMore = screen.getByRole("button", {
  name: /view more/i,
});
userEvent.click(viewMore);

expect(screen.getByTestId("modalContent")).toBeInTheDocument();
```

**Describe your issue**

when i run my test in v1.7.12, i get an error (not appearing when using v1.7.8):

```
Expected test not to call console.error().

    If the error is expected, test for it explicitly by mocking it out using jest.spyOn(console, 'error').mockImplementation() and test that the warning occurs.

    Warning: An update to TransitionChildFn inside a test was not wrapped in act(...).

at TransitionChildFn (/my-project/node_modules/@headlessui/react/dist/headlessui.dev.cjs:6604:5)
at TransitionRootFn (/my-project/node_modules/@headlessui/react/dist/headlessui.dev.cjs:6758:9)
at dataCy (/my-project/src/MyComponent.tsx:56:14)
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We made some internal changes and now you get this `act(...)` warning. Unfortunately the end user itself is not clicking a button or anything (because typically you have to wrap those in `act`), but it is an internal `setState` call happening in the `beforeEnter` callback.

You probably have to use `act` yourself as well. Here is how we did it in our test: https://github.com/tailwindlabs/headlessui/commit/d1ca3a9797bce9e8677051ecd73bb34a4f4969aa?diff=split&w=1

I would also recommend to _not_ run Transition related tests in Jest because we are using native transition related events that are not implemented in JSDOM. Instead I would recommend to test them in a real browser using something like Playwright.

Hope this helps!

**Comment by hco** [comment]
@RobinMalfait My understanding of the current best practices for writing tests with react-testing-library tries to avoid the usage of act in your test code. There are of course exceptions, but I am not really sure if this needs to be one. I checked with https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning, and none of the exceptions listed there applies here, if I am not mistaken. 

I also think that `render()` from react-testing-library already wraps the component in `act()`. 

I also disagree with "not running transition related tests in jest", if that implies "not running tests that use components that use transitions", because that kind of means that you cannot test most of your components using jest, because most components will contain a popover, menu, dialog, …, and all of them will probably have a fade-in/out transition, right? 

I'd really wish we could re-discuss the suggestion of "adding act to the test code of every component that uses the transition from headless-ui". Are you open for that? :)

**Comment by hco** [comment]
@RobinMalfait Apparently I misunderstood something. The issue I ran into was fixed in 1.7.13. :)

**Comment by mmirus** [comment]
@RobinMalfait I'm hitting this when I update from 1.7.10 to 1.7.14, unfortunately.

Recognizing that I could certainly be wrong, I think the OP was correct that:

1. This is most likely not a case that should need an extra `act()` wrapper.
2. Excluding any component that uses `Transition` from Jest / react-testing-library tests is not a good workaround.

Would it be possible to consider reopening this issue?

**Comment by szamanr** [comment]
i am also experiencing this in v1.7.14 and also think this should be reopened. it's an issue in headless UI.

not using transitions inside tests is not really an option. we have components which use transitions under the hood. they should not throw errors inside tests.

wrapping click with `act` is not a solution, because `userEvent` from testing-library already uses `act` under the hood, yet the error still persists.

**Comment by mmirus** [comment]
Following up: updating to react-testing-library v14 seems to resolve this problem (though it came with its own set of challenges).

**Comment by smbkr** [comment]
Problem persists for me with RTL 14:

```
├─ @headlessui/react@1.7.17
├─ @testing-library/react@14.1.2
└─ jest@27.5.1
```

**Comment by az-nextsec** [comment]
We have this occasionally in 1.7.19 still :(
