### ISSUE TITLE
Dialogs used for Slide-overs no longer allow clicking outside

### ISSUE THREAD

**Issue by vgeary96** [tailwindlabs/headlessui#2336]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

^1.7.10 (appears to be introduced by 1.7.12)

**What browser are you using?**

Chrome (but doubt it matters)

**Reproduction URL**

Using the publicly available Slide-overs example from tailwindui. I modified it to allow for interacting with the page (i.e. removed overlay, added pointer-events-none): https://tailwindui.com/components/application-ui/overlays/slide-overs 

Codesandbox example (notice how the page's content is not interact-able, and if you downgrade headless to <= 1.7.11 you can interact with the other content again):
https://codesandbox.io/s/suspicious-golick-gse2eg

**Describe your issue**

When using the tailwindui recommended implementation of a slide-over/drawer, all content outside of the slide over is now marked as inert. I understand why [this change](https://github.com/tailwindlabs/headlessui/commit/10efaa921d1c22be084edd79013f8fc9bc051824) was made as it's supposedly intended behavior, but it breaks any slide-overs that don't want to disable the rest of the screen (i.e. a more info panel that can be expanded/collapsed but shouldn't block the user from doing other things, or a shopping cart that stays with the user throughout a workflow). 

So I guess my question is, does tailwindui need an update? Should this inert behavior be configurable? Is something else broken?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

You mention in your title that you can no longer click outside, but you don't mean that clicking outside doesn't close anymore right? (Because that would definitely be a bug, but I can't seem to reproduce that).

I don't think we want to make the `inert` part optional / configurable because it is an important accessibility feature and the goal of the `Dialog` is that you can _only_ interact with the `Dialog` itself and not with elements outside of it. For example if we allow the `inert` prop to be configured so that you can still interact with the "outside world" when clicking on items there, then the keyboard users are still "stuck" in the `Dialog` itself because the focus is locked in the `Dialog` component. We also lock the "scroll" of the page so that you can't accidentally scroll the the page in the background while you are working _inside_ the `Dialog`. If we want to make the `inert` configurable then we probably need to find a new prop name that also handles the other use cases the `Dialog` is concerned with. Once you tackle them all, then we completely lost the behaviour and intentions of the `Dialog` component.

The intention of the slide-overs in Tailwind UI had the same purpose, a slide over component that provides you some additional information or where you can apply quick actions for, instead of opening a new page. You can also think of them as "normal" modals, but styled differently. E.g.: your page contains a list of users, a slide-over can be shown to quickly create a new user.

We also try to provide common use cases and patterns in our components and try to choose the "right" component, but if you have different use cases it is totally fine to change them. 

(Random example, but if we are using links for our tabs, you can swap it with a tabs component from Headless UI and the other way around).

All that to say that I don't think that Tailwind UI needs changing or that we need to make these features configurable in Headless UI. I think your use case just happens to be a bit different compared to what we originally intended and that you want to have the same visual look of the slide-over components and that's totally fine of course! 

I've updated your CodeSandbox with a `Disclosure` instead of a `Dialog`. This still provides you with the same visual UI, but you are also able to interact with the main content. This also doesn't require you to "undo" some outside click behaviour: https://codesandbox.io/s/stupefied-hellman-1jg2j3?file=/src/Sideover.tsx


Hope this helps!
