### ISSUE TITLE
`Combobox` component automatically scrolls to the top when there is large set of data

### ISSUE THREAD

**Issue by meruyert93** [tailwindlabs/headlessui#2343]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.2 (v1.7.13 it is the same)

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/combobox-wk319b?file=/src/App.js

**Describe your issue**

We are using Combobox component and since we have large set of data we are also using [react-window](https://github.com/bvaughn/react-window). When I scroll fast to the bottom of the list, it automatically scrolls to the top. I feel like there is some kinda focus on selected or active item, which forces to scroll to the top. It is also not consistent, but very frequent :( You need to scroll several times or refresh the page so you can see this bug. I expect that it should not be scrolled to the top.
I have also attached the video and put the minimal reproduction link. 

Can you please look at this if this is a bug and please give any kinda feedback?
Thanks a lot in advance.

https://user-images.githubusercontent.com/61665812/223225795-356fc47a-d028-493f-9e92-aeb064682d84.mov

**Comment by thecrypticace** [comment]
Hey! The reason you're seeing this behavior is because Headless UI uses direct DOM crawling and manipulation to work out what items are before/after what other items — including which ones are first or last. Using a virtual scroller makes this far more complicated because those calculations can no longer be based on the DOM but the virtual scroller's view of the DOM. This is because they limit the number of DOM elements on the page and "reuse" and move them around as scrolling occurs.

I fiddled around a bit with `react-window` and I couldn't come up with a good solution to wrapping it as it doesn't provide the necessary windowing information such that we could introduce dummy elements in an attempt to work around this — which I'm not even sure is possible generally because of info Headless UI has to keep around for bookkeeping.

The only solution here would be for Headless UI to introduce it's own virtual scroller or some component which would let you use a virtual scroller while somehow retaining the behavior we need. We've discussed this some in the past but it would be a significant undertaking and not one we're ready to commit to right now.

For now the only supported way to use these components is directly without a virtual scroller. I understand this isn't ideal for some situations and we may very well revisit this in the future.

Hope that helps! ✨
