### ISSUE TITLE
Menu reacts to key events even if it's not focused.

### ISSUE THREAD

**Issue by TN1ck** [tailwindlabs/headlessui#2346]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

1.7.12
 (1.7.3 also had this issue, upgraded to check if it's fixed)

**What browser are you using?**

Chrome, Firefox

**Reproduction URL**

The headlessui example page exhibits this issue: 
https://headlessui.com/react/menu

**Describe your issue**

The Menu reacts to keyboard events (space, enter, arrow) even though it is not focused. Reproduce:

1. Open https://headlessui.com/react/menu
2. Click the "Options" button
3. Close it by clicking on the background. The button is not focused anymore now.
4. Press space and see the button open again. This should not happen.

This problem is especially problematic when a modal is opened through the menu that is in another HTML tree, nothing will remove the focus from the Menu.

To me this seems like a bug, but if not, is there a way to disable the behavior? Nothing I tried worked (blur the focus etc).

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

For example:
- The button is not focused anymore now.
  - It still is focused, so there is likely another problem going on. (On the website there is a white border/ring when the button is focused)
- This problem is especially problematic when a modal is opened through the menu that is in another HTML tree, nothing will remove the focus from the Menu.
  - Can you provide a minimal reproduction repo / CodeSandbox for this? 

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by TN1ck** [comment]
Fair enough @RobinMalfait,

Sorry for not providing one, I thought the demo page was good enough, as it showed the odd behavior - which isn't as important though as moving the focus normally works fine (one could argue that clicking the background and pressing space should scroll and not open the menu again). I should have spent more time building a minimal example.

The bug I am seeing is _basically_ a duplicate of https://github.com/tailwindlabs/headlessui/issues/1758

I created a minimal case here: https://codesandbox.io/s/headless-ui-menu-space-behaviour-zr5ig2

The problem arises when one puts an element inside the `<Menu>` component that also reacts to key events, in this example it's quite visible as the input of the modal is directly focused, but pressing space will lead to the menu opening/closing.

Here is a video of it:
[headless-ui-bug.webm](https://user-images.githubusercontent.com/2116347/224123442-9dc1420b-b8cb-4e1c-8c06-f1ec0bb8b551.webm)


A fix is to move these elements outside of the component, if not fixed, it should probably be mentioned somewhere.
