### ISSUE TITLE
Custom "as" component provided to Combobox.Input trow error

### ISSUE THREAD

**Issue by solodukhin-e** [tailwindlabs/headlessui#2370]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.12

**What browser are you using?**

 Chrome

**Reproduction URL**

https://codesandbox.io/s/sharp-ishizaka-3p638r?file=/src/App.vue

**Describe your issue**
Combobox.Input trowwith error `input.setSelectionRange` when input value to custom input component specified in the property `as`.
![image](https://user-images.githubusercontent.com/125455592/225509904-03fa50c6-3bdd-4a1e-b4ba-31ae682f8b8d.png)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The `as` prop can be used to provide your own custom element. The main reason is so that you can use your own pre-styled components already. However, you also have to make sure that the component is compatible. In this case, the `Combobox.Input` is an `input` component. Your custom component is not an `input`, but a `div` with a `label` and an `input`.

This in itself is not a problem, but then you have to make sure that all the props and the ref are forwarded to the `input` within that custom component.

Here is an updated CodeSandbox that forwards the `$el` ref: https://codesandbox.io/s/stupefied-tdd-xk6ern

Hope this helps!
