### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/headlessui#238]
Hi, i really love to use this package. But when i use this performance will be slow down pretty much. Google speed soccer low down about 10 point. I must remove headless ui from my code and didn’t use animations in front end. I hope you have a solution for performance. Thank you.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

I will need a bit more information from you, because when I do tests, for example a lighthouse score on this page (https://headlessui-react-git-multiple-components.tailwindlabs.vercel.app/menu/menu) I get a 94 performance out of the box without me doing anything special performance related.

My questions to you are:

- What do you mean by "performance issue", only the points you get?
- Do you see any performance issues while using this?
- Are you sure it is related to this package, and eliminated other factors?
- Are you doing these tests in development mode or production mode?
- Can you create a reproduction repository that showcases the performance issues?

**Comment by IRediTOTO** [comment]
Hi, thank you for replying me. 
1) yes, only points. The UI still smooth i think. But this relate to the SEO - the google points 
2) no i dont
3) pretty sure, google soccers is ok if i remove the code of animation.
4) i use in production, when google soccer down, i removed the animation codes.
5) i think this hard, project must big enough. I will try again in next project.

In your example, its small so you will get high point. I will take some screenshot when i do next project. I would love simple animation but it should be supper small and run fast :D
