### ISSUE TITLE
[BUG] UI bug

### ISSUE THREAD

**Issue by himanshu1221** [tailwindlabs/headlessui#2392]
**What browser are you using?**

Chrome

**Reproduction URL**

https://headlessui.com/react/transition

**Describe your issue**

Copy button overlapping the scrollbar 

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.
go to headlessui.com
click on transition 
click on the code for the same 

here are the screenshot 
![Screenshot from 2023-03-22 19-42-55](https://user-images.githubusercontent.com/32031706/226932511-98e908c8-345d-4b4a-9ce1-cff46839fc33.png)

**Comment by reinink** [comment]
Hey! Thanks for bringing this to our attention. While not perfect, I've tweaked the site a bit this morning to push these buttons to the left slightly so that they don't interfere with the scrollbar, and added `pointer-events-none` to the blurred background so that you can click through to the scrollbar. Hope that helps! 👍
