### ISSUE TITLE
Adding "placeholder" prop to ComboBox causes "multiple" to be true / wrong types

### ISSUE THREAD

**Issue by heggemsnes** [tailwindlabs/headlessui#2407]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Arc 0.95.1

**Reproduction URL**

Created a quick Stackblitz, it doesn't build but it shows the error in the editor.

https://stackblitz.com/edit/react-ts-mzm58m?file=App.tsx

**Describe your issue**

Adding `placeholder` to the `ComboBox` element causes the inferred type from onChange callback to be arrays:

```
(parameter) e: {
    id: number;
    name: string;
}[]
```

Since I'm not using `multiple:true` I am expecting this to be the regular value without being an array

```
(parameter) e: {
    id: number;
    name: string;
}
```

Removing the placeholder makes it work again but I just spent way too much time trying to debug this :)

Edit: I might be going insane but the shared Stackblitz might not even show the error:

<img width="551" alt="CleanShot 2023-03-31 at 17 31 12@2x" src="https://user-images.githubusercontent.com/36757859/229164736-389dafb2-1583-4886-8ec7-5a7e4b1cf977.png">

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I don't see the issue on StackBlitz itself
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1834413/229169083-c9d8f4eb-c7d7-455e-919e-b3fe3fa73e4f.png">
.

But that said, you don't want to put the `placeholder` on the `Combobox` itself, you probably want it to be on the `Combobox.Input`.

So while this could result in strange TypeScript types, I don't (currently) consider this an an actual issue.

Does moving the prop to `Combobox.Input` solve the issue for you while also resulting in the expected behaviour?

**Comment by heggemsnes** [comment]
Of course, I realised this was the wrong place to put this prop, but my thinking in flagging this is that unused props shouldn't affect the component.

Thanks for the quick feedback, I managed to get it back by playing around in the stackblitz but maybe a TS bug anyways.

**Comment by heggemsnes** [comment]
Hey @RobinMalfait really appreciate you taking the time here. Hopefully this will save some poor souls in the future :)

Thank you!

**Comment by dheerajsinghnagdali** [comment]
It's a pretty common functionality, and I would appreciate if you could fix this type error.
