### ISSUE TITLE
Scrolling big virtual lists in combobox has problems

### ISSUE THREAD

**Issue by AnnaYuS** [tailwindlabs/headlessui#2431]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Chrome, Safari, FF

**Reproduction URL**

https://stackblitz.com/edit/vue-jlumic?file=src/components/HelloWorld.vue

Chrome:

https://user-images.githubusercontent.com/19432263/231744411-a8c9d603-321f-481f-810b-0b0bf25412c5.mov

Firefox:

https://user-images.githubusercontent.com/19432263/231744516-4c977920-8ad0-48a2-a8da-a9d4530d52c5.mov

**Describe your issue**
This seems to be the same issue as described here https://github.com/tailwindlabs/headlessui/issues/1872
We are using virtual list from vueuse, scrolling big lists of data has problems. It seems like the active element is trying to stay in focus when scrolling 

I've also tried it with vue-virtual-scroller, but the scroll has similar problems: https://stackblitz.com/edit/vue-tfukma?file=src/components/HelloWorld.vue

**Comment by thecrypticace** [comment]
Hey! The short version is that Headless UI doesn't currently work with virtual scrollers because of implementation details and information needed to ensure comboboxes, listboxes, etc… behave properly even in the face of some DOM manipulations. A virtual scroller makes implementing things significantly more difficult; and, generally, they don't expose the necessary APIs for us to use. My suggestion, at least for now, is to use it without a virtual scroller.

You can take a look at https://github.com/tailwindlabs/headlessui/issues/2343#issuecomment-1476265510 for a slightly more detailed explanation.

I know this isn't ideal but it's the state of things currently. Let me know if you have more questions.

**Comment by AnnaYuS** [comment]
I've noticed that something made the problem worse starting from v.1.7.5. In [this reproduction]([stackblitz.com/edit/vue-jlumic?file=src/components/HelloWorld.vue](https://stackblitz.com/edit/vue-jlumic?file=src/components/HelloWorld.vue))  in Firefox i cannot scroll past the active item

https://user-images.githubusercontent.com/19432263/232466732-e1b97f58-4400-468b-afbf-94e6850d949b.mov

But if i change the dependency to v1.7.4 i can scroll normally, and the problem only happens if the first visible item is active


https://user-images.githubusercontent.com/19432263/232467059-d087dea8-e8ed-44af-b085-4b908e313d11.mov

@thecrypticace Maybe it's something that can be fixed without serious changes like implementing a virtual scroller etc? at least it would make the combobox more usable with large lists
