### ISSUE TITLE
Unable to use the `by` prop with the `multiple` prop in a Combobox

### ISSUE THREAD

**Issue by jaithirani** [tailwindlabs/headlessui#2434]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v^1.7.7

**What browser are you using?**

Chrome

**Reproduction URL**
https://codesandbox.io/s/hidden-star-k5jq1y?file=/src/ComboboxMultiple.tsx
Note: In the file ComboboxMultiple.tsx, Codesandbox changes <T, > to <T> in the component declaration which causes an error. Just make sure it is <T, > in case it autosaves it and changes it to <T>

**Describe your issue**

Unable to use the `by` prop with the `multiple` prop. 
- Gives an error on the `value`, `onChange` and `by` props when using the `by` prop but no there's no error without it. 
- Resulting in being able to select an option that is already selected. In the example, you can select a person multiple times (value is shown by the name outside the combobox)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The API is a little awkward right now to use the exposed ComboboxProps, but one way of solving your issue is by making sure you are using the exposed `ComboboxProps` this will ensure that expected types are correct internally. 

I've updated the CodeSandbox link with the required changes: https://codesandbox.io/s/festive-curran-ic7y9n?file=/src/ComboboxMultiple.tsx

Note: I also, also updated your component to use a `function` instead of an arrow function to work around the `<T,>` auto save issue.

(@thecrypticace do you think we can improve the public API for this such that the `nullable` and `multiple` generic field is something end users don't have to worry about?) 

Hope this helps!
