### ISSUE TITLE
Values outside of predefined list replaced by first element from the list

### ISSUE THREAD

**Issue by KubaLorenc** [tailwindlabs/headlessui#2439]
What package within Headless UI are you using?

I'm using @headlessui/react

What version of that package are you using?

I'm using v1.7.11

What browser are you using?
Chrome

When using combobx and provide values outside of the list the behaviour is weird.
For example, when you click cancel, and then save again it will default to the first element on the list instead of custom value provided before.
Also just clicking save will work fine for the first time, and for the second, but on the third save it will again default to first value from the list and therefore change your input.

And one last issue with custom typed values is that when you click tab, it focuses on "reset changes" but also it automatically replaces value to the first element on the list
If you need any further informations or steps to reproduce please respond. 
@[axelsz](https://github.com/axelio)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

It could be that you are dealing with objects and once you save you end up with a new object. To solve that take a look at the binding objects documentation: https://headlessui.com/react/combobox#binding-objects-as-values

The `tab` is expected behaviour, if the Combobox is open and you press `tab` then the currently visible selected option will be selected and the focus will move to the next item (or the previous if you hold `shift`). If the Combobox is closed, then this won't happen and the focus switches to the new element.

That said, unfortunately I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
