### ISSUE TITLE
Dialog wrapper not getting cleared on redirect

### ISSUE THREAD

**Issue by lazer-hybiz** [tailwindlabs/headlessui#2443]
**What package within Headless UI are you using?**
@headlessui/vue

**What version of that package are you using?**
v1.7.13

**What browser are you using?**
Chrome, Firefox

**Reproduction URL**
I'm using Inertia with laravel, I'm not really sure I can make a _minimal_ reproduction. I'm attaching a screen capture of the issue

https://user-images.githubusercontent.com/100562257/232985085-36feed19-1769-4f76-91a6-85ab08ca7b88.mov

**Describe your issue**
I am using Inertiajs with layouts, when I redirect from a page with an open dialog to a page with a different layout the dialog `div` is still there over the entire page (the inner content of the dialog is not there), I have to reload the page in order to remove it.

this is the code for my dialog
```vue
<template>
  <TransitionRoot
    appear
    :show="asPage ? showPage: show"
    as="template"
  >
    <Dialog
      as="div"
      class="fixed inset-0 z-10 min-h-screen overflow-y-auto px-4 text-center"
      @close="close"
    >
      <TransitionChild...>
      
      <TransitionChild...>
    </Dialog>
  </TransitionRoot>
</template>
```

This started happening with version 1.7.13 and was caused by [this commit](https://github.com/tailwindlabs/headlessui/pull/2422/commits/1970d9b8f0b4f46152465f750544661b8305b560)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I know you mentioned that it could be hard to create a minimum reproduction repo, but unfortunately without one we can't help you because there could be a lot of things happening that could cause this issue.

That said, the Dialog component doesn't really know about routing and there are a lot of libraries out there that do routing in different ways (even in memory based routers) so it is rather impossible to know that a redirect happened from the Dialogs perspective. We also don't want to build in support for all of the routers used in Next.js, Nuxt.js, Inertia, ... to know when a redirect happened or not.

My guess here is that the page is still "mounted" and therefore the Dialog itself is also still mounted. If the page was unmounted, then the Dialog itself should be unmounted as well.

The Dialog itself is a controlled component, meaning that you can control its state which you are doing already using the `:show` prop. This also means that you _should_ be able to set the `show` state to `false` right before you redirect. If this is not the case than a minimal reproduction repo would be necessary to further debug what's going on.

Hopefully setting the `show` to false before the redirect is enough.

Going to keep the issue open for now and hopefully we can figure out what's going on.

**Comment by lazer-hybiz** [comment]
Thanks @RobinMalfait that helped, I was using two separate layouts and each layout had its own modal, just wondering why it *did* work in v1.7.12
