### ISSUE TITLE
Elements always receiving focus & outline on Safari

### ISSUE THREAD

**Issue by sgrund14** [tailwindlabs/headlessui#2459]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

@headlessui/react: v1.7.14
@headlessui/tailwindcss: v0.1.3

**What browser are you using?**

Safari

**Describe your issue**

In safari, desktop and mobile, my headless ui elements are receiving focus-visible and the associated styling (outline) whenever i trigger them. This doesn't happen on chrome. Here's an example:

**on safari**

https://user-images.githubusercontent.com/14083701/234920073-b30435ed-7792-4ee0-8de5-ca3c1b32b26b.mov

**on chrome (desired behavior)**

https://user-images.githubusercontent.com/14083701/234920463-b8675b1b-bb79-4c4f-bec8-9e6278facef0.mov

any help / thoughts ? The same is happening with modal components (first focusable elements gets outline) and tabs (tab list items get an outline)

**Comment by sgrund14** [comment]
or do I just have to add focus:outline-none wherever i don't want this behavior.. but wouldn't that mess with accessibility?

**Comment by pushchris** [comment]
Also experiencing this and would be curious what others are doing

**Comment by adamwathan** [comment]
Hey! This has been discussed previously in https://github.com/tailwindlabs/headlessui/issues/1694, and you can learn about the solution we ended up going with in https://github.com/tailwindlabs/headlessui/pull/2347 👍 

Basically because we need to imperatively handle focus in a lot of cases for accessibility reasons, `focus-visible` styles are triggered by the browser when you might not want them and there's just literally zero we can do to stop the browser from doing it. So instead we've exposed our own internal state that tracks whether _we_ believe focus should be visible using a `data` attribute we add to the document that you can use to style focus visible states instead of relying on the actual `:focus-visible` pseudo class. Not the solution I really want but the best option at the moment I'm afraid, and is at least very reliable and gives you a lot of control.

Hope that helps!

**Comment by sgrund14** [comment]
hey @adamwathan, thanks for the reply here

I think I'm now running into an issue similar to the one here https://github.com/tailwindlabs/tailwindcss/issues/3842#issuecomment-810362604

I have `important: 'html` set on my tailwind config file, which is preventing the data-headlessui-focus-visible attribute from being detected. generated rule comes out like this

```
html :where([data-headlessui-focus-visible]) .ui-focus-visible\:ring-black:focus {
    --tw-ring-opacity: 1;
    --tw-ring-color: rgb(0 0 0 / var(--tw-ring-opacity));
}
```

is there a way to set the attribute lower down the component tree? or do I just need not use the important setting 🤔 but then the thing is that it's really useful for overriding default styles in react native components (which I'm using [nativewind](https://www.nativewind.dev/) for)
