### ISSUE TITLE
The `hold` prop on `ComboboxOptions` no longer works

### ISSUE THREAD

**Issue by yakobe** [tailwindlabs/headlessui#2490]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

1.7.13

**What browser are you using?**

Firefox

**Reproduction URL**

https://stackblitz.com/edit/vue3-tailwind-zqqbnp?file=src%2Fcomponents%2FHelloWorld.vue%3AL91

**Describe your issue**

The above link has an example with the `hold` prop explicitly set to `false`. This should mean that the active option should not stay active when the mouse leaves the active option. However, the option always stay active.

In version 1.7.4 it still worked:
https://stackblitz.com/edit/vue3-tailwind-81tvam?file=src%2Fcomponents%2FHelloWorld.vue%3AL91

Here the active option is deactivated when the user leaves the option while scrolling. 

The problem is that if the option is not deactivated, then if any options are added/removed then headless ui tries to scroll to the active option. This means we cannot scroll away from the active option.

**Comment by yakobe** [comment]
I think this is similar to #2441 since i am also using some sort of virtual list.

The problem is that if the option stays active, then we cannot scroll away from it and change the filtered options. Any change to the options causes an immediate "scroll" to the active option again.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I don't see the behaviour your are describing. The `active` state is removed correctly in both links you provided.

In your example there are 2 "states" going on:
- Selected: The checkmark on the `Combobox.Option`
- Active: The green background when you use your arrow keys or hover over an item. It's this state that can be toggled using the `hold` prop.

That said, the `hold` prop is a prop on the `Combobox.Options` (wrapper) component, nota prop of the `Combobox.Option` (individual item) component. The default value of this prop is `false` already so setting it to `false` explicitly doesn't change the behaviour. 

If you set the value to `true`, then the active state of each `Combobox.Option` is maintained even if your mouse is away from the Combobox component.

If you set it to `false` (or omit it since it is the default) then moving your mouse outside of the `Combobox` will immediately remove the active state.

### Example with `<ComboboxOptions :hold="false">` or `<ComboboxOptions>`:

https://github.com/tailwindlabs/headlessui/assets/1834413/0d23d882-ac23-4e81-9d03-11f103d94dfe

### Example with `<ComboboxOptions :hold="true">`:

https://github.com/tailwindlabs/headlessui/assets/1834413/555e5d6a-bb69-4818-85bf-3e46baa8ce2d


Hope this helps!

**Comment by yakobe** [comment]
Hi @RobinMalfait 

I think I described it badly 😅. The problem is only while scrolling with the mouse over the open combobox options. 

In the old version I could put my mouse in the middle of the options and it would highlight (activate) the option under the pointer. Then as I scroll up the active option would deactivate as it moved out from under the mouse pointer. When `hold` was set to true it would not deactivate (this is the reason I thought it was this setting that was broken). 

In the new version the option stays active as I scroll. Even when the mouse pointer is no longer over it. Even as it starts to scroll out of view. 

It might seem superficial, but this causes a problem because the combobox will auto-scroll to the active element when the filtered options change. This means we cannot scroll away. Therefore, using virtual lists or doing any complex tasks with the new versions is not possible. And comboboxes often have lots of data to filter through, so many real world usages are broken 😕. 

I hope you understand what I mean. If not, would a video help to clarify? Many thanks!
