### ISSUE TITLE
[Bug]: Transition applied on content instead of Disclosure panel 

### ISSUE THREAD

**Issue by nicolasgomeztoua** [tailwindlabs/headlessui#2505]
[Bug]: Transition applied on content instead of Disclosure panel #918
Closed
[MathieuAndrade](https://github.com/MathieuAndrade) opened this issue on Nov 8, 2021 · 15 comments
Closed
[[Bug]: Transition applied on content instead of Disclosure panel](https://github.com/tailwindlabs/headlessui/issues/918#top)
#918
[MathieuAndrade](https://github.com/MathieuAndrade) opened this issue on Nov 8, 2021 · 15 comments
Comments
@[MathieuAndrade](https://github.com/MathieuAndrade)
MathieuAndrade commented [on Nov 8, 2021](https://github.com/tailwindlabs/headlessui/issues/918#issue-1047883377)
What package within Headless UI are you using?

@headlessui/react

What version of that package are you using?

v1.4.2

What browser are you using?

Chrome (Tested on Edge and Firefox)

Reproduction URL

https://codesandbox.io/s/headlessui-disclosure-transition-issue-6ogxj?file=/src/App.tsx

Describe your issue

When i use Transition component on Disclosure Panel, the transition is applied on content of panel instead of panel himself.
I tried to use only documentation exemple, outside my project, but the exemple on documentation was already broken 🤔

(Note: I have volontarily increase the duration of transition to expect the beahavor)
(Note 2: I tried to use unmount prop already, but seems to component was systematicaly unmounted regardless this prop)

muratoreT, benderillo, dbrookes, mreduar, AndreiManolache, allthesignals, and QuantumNoisemaker reacted with thumbs up emoji
@[MathieuAndrade](https://github.com/MathieuAndrade) MathieuAndrade changed the title Transition applied on content instead of Disclosure panel [Bug]: Transition applied on content instead of Disclosure panel [on Nov 8, 2021](https://github.com/tailwindlabs/headlessui/issues/918#event-5585472804)
@[brantchoate](https://github.com/brantchoate)
brantchoate commented [on Nov 11, 2021](https://github.com/tailwindlabs/headlessui/issues/918#issuecomment-965994498)
Having the same problem myself on a custom drawer component

muratoreT reacted with thumbs up emoji
@benderillo
benderillo commented on Nov 25, 2021
Having the same behaviour.
Pure example from the documentation doesn't work as explained.
Expectation is that the entire panel will transition but the result is very weird transition: the panel appears instantly and the content transitions within the duration time.
Can somebody from headlessui team comment on this?

MathieuAndrade, muratoreT, mreduar, and AndreiManolache reacted with thumbs up emoji
@RobinMalfait
Collaborator
RobinMalfait commented on Jan 19, 2022
Hey! Thank you for your bug report!
Much appreciated! 🙏

The transition is applied onto the Disclosure.Panel, I applied a background color to the panel that showcases this: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-hzww3?file=/src/App.tsx

The issue with your example is that the purple background color is not coming from the Disclosure.Panel, but it is coming from the Disclosure itself.
This means that if you move the background color from the Disclosure to the Disclosure.Panel then your problem goes away: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-kdtd9?file=/src/App.tsx

mreduar, vyas-meet, ayhanap, hacknaked, alfredomtzrmz, and nicolasgomeztoua reacted with thumbs down emoji
hacknaked reacted with confused emoji
@RobinMalfait RobinMalfait closed this as completed on Jan 19, 2022
@[benderillo](https://github.com/benderillo)
benderillo commented on Jan 19, 2022
@RobinMalfait What about the behaviour I described in my comment? the sandbox example you provided also shows it.
When you expand the Disclosure, the panel appears instantly, or at least everything shifts down instantly and the contents emerge from 0 opacity gradually (based on transition time function and duration).
This produces ugly jump of a page content below the disclosure which the Transition meant to avoid at the first place.

n3oAlex, Maronato, mreduar, gunsodo, RegulEsteban, nathanielfostanperry, biezenskiSECPSD, vyas-meet, Teekola, allthesignals, and 4 more reacted with thumbs up emoji
@mreduar
mreduar commented on Mar 31, 2022
Hi @benderillo, I am having exactly the same inconvenience as you. Basically the behavior of the disclosure makes the content that is located at the bottom jump in a jerky way and I am looking for this to be nice, unfortunately it is not built in tailwindui either. Did you find a solution to the problem?

@benderillo
benderillo commented on Apr 1, 2022
Hi @benderillo, I am having exactly the same inconvenience as you. Basically the behavior of the disclosure makes the content that is located at the bottom jump in a jerky way and I am looking for this to be nice, unfortunately it is not built in tailwindui either. Did you find a solution to the problem?

Yes, I found the solution!
The solution is to DO NOT USE headlessui/disclosure component.
I abandoned use of the component and just implemented my own super simplistic disclosure using the https://www.npmjs.com/package/react-animate-height package.

Here is my source code, it works for my needs, albeit is very simplistic:

import React, { useState } from 'react';
import AnimateHeight from 'react-animate-height';

type Props = {
  buttonContent: (open: boolean) => JSX.Element;
  children: JSX.Element | Array<JSX.Element>;
  initialOpen?: boolean;
};
export function Disclose({ buttonContent, children, initialOpen = false }: Props) {
  const [open, setOpen] = useState(initialOpen);

  return (
    <div className='relative'>
      <button className='accordion_button w-full' onClick={() => setOpen(!open)}>
        {buttonContent(open)}
      </button>
      <AnimateHeight id={'sliding_wrapper'} duration={300} height={open ? 'auto' : 0}>
        {children}
      </AnimateHeight>
    </div>
  );
}

mreduar, mohamadjavad, ProdByGR, lansolo99, hacknaked, and nicolasgomeztoua reacted with thumbs up emoji
mreduar reacted with laugh emoji
@mreduar
mreduar commented on Apr 1, 2022
Yes, I found the solution!
The solution is to DO NOT USE headlessui/disclosure component.
I abandoned use of the component and just implemented my own super simplistic disclosure using the https://www.npmjs.com/package/react-animate-height package.

Thanks, I also had to make my own component, in my case I am using vue.

@hodbn
hodbn commented on Aug 1, 2022
Another workaround is to use the Disclosure component but manage its state manually using static, and then transition the height (or max-height to workaround the transition to auto):

<Disclosure>
  {({ open }) => (
    <>
      <Disclosure.Button>button</Disclosure.Button>
      <Transition
        show={open}
        className='overflow-hidden'
        enter='transition transition-[max-height] duration-200 ease-in'
        enterFrom='transform max-h-0'
        enterTo='transform max-h-screen'
        leave='transition transition-[max-height] duration-400 ease-out'
        leaveFrom='transform max-h-screen'
        leaveTo='transform max-h-0'
      >
        <Disclosure.Panel static>content</Disclosure.Panel>
      </Transition>
    </>
  )}
</Disclosure>
rub1e, peepers-rick, tayanderson, ProdByGR, teye, AnsonH, zachlankton, JohannesLudloff, akshayrajpaul13, OFFLlNE, and 15 more reacted with thumbs up emoji
giovannetti-eric and cullylarson reacted with thumbs down emoji
@zanami
zanami commented on Oct 14, 2022 • 
@hodbn this way you can't use transitions other than max-height (opacity, scale etc), transition-[max-height] overwrites transition-property set by transition. Can be fixed globally https://tailwindcss.com/docs/transition-property#customizing-your-theme

Actually I couldn't just add height and max-height to default transition so ended up using transition-all instead of transition-[max-height]
Another option is using an arbitrary value like [transition-property: max-height opacity]

@giovannetti-eric
giovannetti-eric commented on Jan 15
Another workaround is to use the Disclosure component but manage its state manually using static, and then transition the height (or max-height to workaround the transition to auto):

<Disclosure>
  {({ open }) => (
    <>
      <Disclosure.Button>button</Disclosure.Button>
      <Transition
        show={open}
        className='overflow-hidden'
        enter='transition transition-[max-height] duration-200 ease-in'
        enterFrom='transform max-h-0'
        enterTo='transform max-h-screen'
        leave='transition transition-[max-height] duration-400 ease-out'
        leaveFrom='transform max-h-screen'
        leaveTo='transform max-h-0'
      >
        <Disclosure.Panel static>content</Disclosure.Panel>
      </Transition>
    </>
  )}
</Disclosure>
In this example, if the height of the panel is greater than the screen, the panel will be truncated, I don't think that's a safe use case.

cullylarson reacted with thumbs up emoji
@BrennerSpear
BrennerSpear commented on Feb 22
Is there a correct way to do this with headlessui?

developedbygeo, HenrikFricke, allthesignals, codeyacine, ayhanap, and alfredomtzrmz reacted with thumbs up emoji
@olehoutvio
olehoutvio commented on Mar 29 • 
export function PortalAccordionPanel({ title, text }: { title: string; text: string }) {
  const ref = useRef<HTMLDivElement>(null);
  return (
    <Disclosure>
      {({ open }) => (
        <>
          <Disclosure.Button
            className={`border-t border-portal-black/15 first-of-type:border-t-0 flex w-full justify-between items-center bg-white pt-6 pb-6 font-semibold text-base text-portal-black`}
          >
            <span>{title}</span>
            <ExpandMore
              className={`${
                open ? 'rotate-180 transform transition duration-300' : ''
              } text-3xl text-portal-black opacity-15`}
            />
          </Disclosure.Button>
          <Transition
            ref={ref}
            show={open}
            beforeEnter={() => {
              ref.current &&
                ref.current.style.setProperty(`max-height`, `${ref.current.scrollHeight}px`);
            }}
            beforeLeave={() => {
              ref.current && ref.current.style.setProperty(`max-height`, `0px`);
            }}
            className="transition-all duration-300"
            enterFrom="transform opacity-0 max-h-[0px]"
            enterTo="transform opacity-100"
            leaveFrom="transform opacity-50"
            leaveTo="transform opacity-0"
          >
            <Disclosure.Panel className="font-base text-portal-black -mt-4 pb-6">
              {text}
            </Disclosure.Panel>
          </Transition>
        </>
      )}
    </Disclosure>
  );
}
@hacknaked
hacknaked commented on Apr 11
Hey! Thank you for your bug report! Much appreciated! pray

The transition is applied onto the Disclosure.Panel, I applied a background color to the panel that showcases this: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-hzww3?file=/src/App.tsx

The issue with your example is that the purple background color is not coming from the Disclosure.Panel, but it is coming from the Disclosure itself. This means that if you move the background color from the Disclosure to the Disclosure.Panel then your problem goes away: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-kdtd9?file=/src/App.tsx

This issue should be reopen and fixed. All previous comments are valid: the component has a wrong and wired behavior when animating the Disclosure.Panel height.

QuantumNoisemaker, hobuttt, tobiashaefermann, and nicolasgomeztoua reacted with thumbs up emoji
@brokuka
brokuka commented on Apr 11
export function PortalAccordionPanel({ title, text }: { title: string; text: string }) {
  const ref = useRef<HTMLDivElement>(null);
  return (
    <Disclosure>
      {({ open }) => (
        <>
          <Disclosure.Button
            className={`border-t border-portal-black/15 first-of-type:border-t-0 flex w-full justify-between items-center bg-white pt-6 pb-6 font-semibold text-base text-portal-black`}
          >
            <span>{title}</span>
            <ExpandMore
              className={`${
                open ? 'rotate-180 transform transition duration-300' : ''
              } text-3xl text-portal-black opacity-15`}
            />
          </Disclosure.Button>
          <Transition
            ref={ref}
            show={open}
            beforeEnter={() => {
              ref.current &&
                ref.current.style.setProperty(`max-height`, `${ref.current.scrollHeight}px`);
            }}
            beforeLeave={() => {
              ref.current && ref.current.style.setProperty(`max-height`, `0px`);
            }}
            className="transition-all duration-300"
            enterFrom="transform opacity-0 max-h-[0px]"
            enterTo="transform opacity-100"
            leaveFrom="transform opacity-50"
            leaveTo="transform opacity-0"
          >
            <Disclosure.Panel className="font-base text-portal-black -mt-4 pb-6">
              {text}
            </Disclosure.Panel>
          </Transition>
        </>
      )}
    </Disclosure>
  );
}
if you open second disclosure and close first will bug

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This issue report is very confusing / overwhelming with all the copy pasted text so I am not 100% sure what the exact problem is.

Depending on the title and the first link you shared I'm assuming you are confused about why the `Disclosure.Panel` is not transitioning but the contents itself.

This issue happens because of a few reasons:
1. The panel doesn't have the background color, the background color is defined on the `Disclosure` itself so it looks like the contents is transitioning. Solution: move the background color classes to the `Disclosure.Panel`.
2. The `Transition.Child` component by default renders a `div` as well. If you want to render those classes on the child, aka the `Disclosure.Panel` then you can use `as={Fragment}` on the `Transition.Child` components. 
   1. But note that we can only have 1 child component if we do that otherwise we don't know to which child we have to forward the props. In this case it means dropping the `{" "}` pieces that are in there.

As a side note, the `static` prop on the `Disclosure.Panel` is not needed so I removed it as well.

Here is an updated CodeSandbox link with the solution I think you want: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-u598fd?file=/src/App.tsx

If this doesn't work for you, could you open a new issue with the actual issue and a reproduction without all the copy/pastes comments?

Hope this helps!

**Comment by nicolasgomeztoua** [comment]
No not at all, you just have to use another package for this I guess. Its just disappointing because this comes with the tailwindUI FAQ which is 259$ so you'd expect to be able to animate it.

![image](https://github.com/tailwindlabs/headlessui/assets/26136034/eb30d59c-af88-4338-991f-11e9a4515dbc)

Solution is to just use react-animate-height instead of disclosure.panel

**Comment by RobinMalfait** [comment]
Hey, I apologise if this isn't the answer you expected but let me try to explain what's going on because I think the issue here consists of 2 individual issues and only 1 part is solved right now.

The main issue I was noticing is that transitions were not always applied on the `Disclosure.Panel` but on its contents. That's the part I tried explaining and solved in the previous comment by making sure that 
- The background color is set on the `Disclosure.Panel`
- The `Transition` classes are put on the `Disclosure.Panel` instead of on the wrapping div by applying `as={Fragment}. This now ensures that transitions are happening on the `Disclosure.Panel`.

The next issue is where you want to transition the height of the `Disclosure.Panel` from nothing (`0px`) to the necessary height (`auto`). The problem here is that our `Transition` components is build for enter/leave transitions and those transitions are completely powered by CSS. The `Transition` component just makes sure that the mounting/unmounting happens at the correct time but the actual transitions are purely CSS based.

This brings us to the problem you are seeing. You are trying to transition the height from `0px` to `auto` and back. CSS right now doesn't have a way to do that at all, hence why it currently isn't working with the `Transition` component from Headless UI.

If you take Headless UI out of the equation then you have this behaviour: https://codesandbox.io/p/sandbox/kind-chaum-zfrysd?file=%2Fsrc%2FApp.jsx%3A1%2C1
As you can see the height is just jumping because CSS can't transition from `0` to `auto` and back for the height property. However the opacity is transitioned correctly because the browser can transition this CSS property.

There are a few ways you can make it work today.
1. You can transition the `max-height` property instead, but this means that you have to set the value to a value equal or slightly larger than the max height it will ever be. This is a bit of guess work because the height might not be known at all or it depends on the viewport / contents. This also gets tricky because if you don't get the guess/math right, then the duration would be incorrect because visually it will already be done but if the max height is set to 1000px and the actual contents is only 200px, then it's still going for the other 800px (which you won't see visually).
2. Another approach is to use some state to measure the height when it is fully rendered so that you can get a pixel based value, then once you measured that transition from `0px` to that `{x}px` based value you just calculated. This is typically the approach that libraries such as `AnimateHeight` use.

If the parent has a fixed height, then you can transition from `0` to `100%` because those are concrete values: https://codesandbox.io/p/sandbox/thirsty-faraday-jq129s?file=%2Fsrc%2FApp.jsx%3A17%2C11

But there are some caveats with this approach:
1. `100%` is based on the **parent** element, not the current element that's where you need `auto`. The CodeSandbox contains 2 examples to showcase the parent size issue. The first example has an explicit height on the parent, the second does not.
2. You also have to make sure that you are using `transition-all` instead of `transition` because otherwise we only transition some known properties such as `opacity` or colors.
3. You have to ensure that `overflow-hidden` is applied otherwise the contents immediately leak.

Since our `Transition` component's purpose is to provide enter/leave transitions powered by CSS and since your use case can't be implemented using pure CSS, the `Transition` component won't work for your use case right now.

Whenever you have more complex transitions/animations we recommend libraries like Framer Motion or React Spring to implement this instead. We expose information like the `open` prop such that you can implement your own transitions/animations with your library of choice (https://headlessui.com/react/disclosure#transitions).

Hopefully one day we can transition the `height` property from `0px` to `auto` with pure CSS (in an efficient way) and then it will work with our `Transition` component out of the box.

In the meantime, you do have to use another library such as Framer Motion. Here is an example using Framer Motion: https://codesandbox.io/s/headlessui-disclosure-transition-issue-forked-s6t2ei?file=/src/App.tsx

I hope this clears things up a little bit, and that the reasoning why you need another library also makes a bit more sense now.
