### ISSUE TITLE
Parent `Switch` not being used for `ui-*` classes when `Switch` is inside a `Dialog`

### ISSUE THREAD

**Issue by thedatasnok** [tailwindlabs/headlessui#2524]
**What package within Headless UI are you using?**

@headlessui/react
@headlessui/tailwindcss

**What version of that package are you using?**

React package: 1.7.15
TailwindCSS plugin: 0.1.3

**What browser are you using?**

Microsoft Edge (114.0.1823.37)

**Reproduction URL**
https://github.com/thedatasnok/headlessui-tailwindcss-nested-elements

**Describe your issue**

When using the `ui-*` utility classes on children elements of a Switch, it does not apply the appropriate styles if the Switch is placed within a Dialog. I have not checked whether this is true for other components, like Popover etc. I can also verify that if you want me to.

It seems to me the issue is that it will look at the state of the outermost parent, in this case the Dialog. Styling the Switch children elements with `ui-open:*` makes the classes apply within the opened dialog. 

I really appreciate being able to use these classes, but I can work around it by using `tailwind-merge` or manually applying classes conditionally where I need it for now. 

If there's anything missing let me know and I'll update the description and/or reproduction.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The issue here is not that it looks at the outer most parent, the issue is that it looks at _any_ parent. Right now this is a limitation of CSS itself (but hopefully we can fix that soon with `@scope`, more info on this topic: https://fullystacked.net/posts/scope-in-css/)

Right now, the solution is to always apply both the `ui-*` and `ui-not-*` classes and you should be good to go.

That said, when running your reproduction it looks like you are already using `ui-checked` and `ui-not-checked` and it looks like it is behaving the way I expect it to behave. 
<img width="674" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/1834413/8d1c39cf-6189-4e59-9634-3ffe2b9edb80">

I also don't see `ui-open` related classes so this part might be missing.

But yep the current solution should be to apply both `ui-*` and `ui-not-*` and you should be good to go.

Hope this helps!

**Comment by thedatasnok** [comment]
Thanks for the prompt answer! 

I'll attach an image with what happens when applying `ui-open:bg-purple-500` to the plugin-based switch. I also updated the reproduction accordingly. 

![image](https://github.com/tailwindlabs/headlessui/assets/47036430/d7a55def-2d4a-45fc-b510-c77887f3c5fb)

If it comes down to `@scope` we'll just have to wait. 

Appreciate your time & work!
