### ISSUE TITLE
Combobox - Keyboard interaction did not work as expected

### ISSUE THREAD

**Issue by meruyert93** [tailwindlabs/headlessui#2540]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.14

**What browser are you using?**
Chrome

**Reproduction URL**
https://codesandbox.io/s/combobox-react-virtual-pdx987?file=/src/Combobox.tsx:1910-2073

**Describe your issue**

I am experiencing two issue when I do keyboard interaction with Combobox.

1) Pressing `Enter` did not toggle the options list open and closed. In Listbox, it works smoothly, since Combobox and Listbox are very similar, I would expect that `Enter`  will also toggle the list.  However, interactions with up and down arrows ↑ ↓  to focus the items works good in this case. (you will understand in the next point why I mentioned it).

2) We have Dropdown design component, which is using Combobox under the hood. We would like to make search optional. So, there is `allowSearch` prop, so if it is provided search would be possible and it will use `Combobox.Input`, if not it would be just normal dropdown and use `Combobox.Button` to toggle the list.  Something like this. You can also play in the provided sandbox link.

```
<Combobox.Button>
  {allowSearch ? <ComboboxInput /> : <span>dropdown trigger </span>}
</Combobox.Button>;
```
The interesting thing is that in this case, In the second case, pressing the `Enter` toggle the options list by opening and closing it. However, Interactions with up and down arrows ↑ ↓  to focus the items did not work.  It is really frustrating because we did not want to implement two completely different Dropdown components with search and without search. We just would like to control allowing search via prop. 
   
Can you please take a look two these two issues and provided some solutions/feedback? Thanks a lot in advance! 
I will be looking forward to your response.

**Comment by rajeev-bstack** [comment]
We are also facing the same issue where the Combobox does not open the options list on `Enter` - it can be seen in the component [demo](https://headlessui.com/react/combobox). Would appreciate it if this could be looked by the headless UI team. 
Thanks!

**Comment by RobinMalfait** [comment]
Hey!

Let's answer your questions individually:

1. **Pressing `Enter` did not toggle the options list**

   A `Combobox` component is a combination of an `input` field and a `Listbox` for the suggestions. In other words, you can think of it as a "fancy" input with additional functionality. Because the combobox needs to work together with the `input`, you always have to render a `<Combobox.Input />` component.

   When the `Combobox` is closed, it still behaves as a normal `input` field. The main reason `Enter` doesn't open the `Combobox`, is because otherwise you can't press `Enter` to submit the form if a `Combobox` is in a form which means you would break that default behaviour.

   We could try to be smart and detect if a `Combobox` is used inside a `<form>` or not and adjust the behaviour. But that will lead to different behaviour depending on where/how you use the `Combobox` component. To the end user, it is also not always visible if a form is used or not.

   There are already a few ways to open the suggestions right now:

   - Start typing
   - Use arrow keys
   - Add an additional `<Combobox.Button />` component

   More info on the keyboard interactions can be found here: https://headlessui.com/react/combobox#keyboard-interaction

   Additionally, the reason a `Listbox` does open is because it only has a `<button type="button" />` component (`<Listbox.Button />`) which doesn't have this form-submit behaviour.

2. **We would like to make search optional**

   The moment you remove the `<Combobox.Input />`, then the combobox won't be a combobox anymore and won't behave as expected anymore. The moment a combobox opens, the `<Combobox.Input />` is focused such that we can capture all the necessary keyboard events. If you remove this input, then there is nothing to capture the events.

   In this case, I would recommend to swap the entire component with a `<Listbox />` component which does have the necessary keyboard handling for a list without search.

---

@rajeev-bstack The explanation in the first point should also explain your use case.

---

Hope this helps!
