### ISSUE TITLE
Upgrading to v1.7.5+ breaks tests for Combobox and Listbox components

### ISSUE THREAD

**Issue by grantiverson** [tailwindlabs/headlessui#2581]
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.7.3, trying to upgrade to 1.7.5+

**What browser are you using?**
N/A

**Reproduction URL**
This issue occurs when running tests, so I have created a small repository that reproduces the issue
https://github.com/grantiverson/headlessui-issue-example

Steps to reproduce ([screen recording](https://d.pr/v/ARn3hb))
- clone the repository
- run `npm install`
- run `npm test`
  - you may need to type "a" to run all tests
  - tests should pass since v1.7.3 is used
- install v1.7.5 or higher
  - `npm install @headlessui/react@1.7.5`
- rerun tests
  - tests should fail this time

**Describe your issue**

### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2148

<div type='discussions-op-text'>

<sup>Originally posted by **grantiverson** January  4, 2023</sup>
Upgrading to v1.7.5+ breaks my tests for Combobox and Listbox. There seems to be an issue with how "hover" events are triggered by tests. Everything seems to work fine in the browser.

I am using the v1.7.4 of the Combobox and Listbox components to make a dropdown. I am also using the Option components to create options for my dropdown. When an option is hovered, `active` should be set to `true` and conditionally add a class. My component logic looks something like this. The Listbox is similar.
```
<Combobox {...comboboxProps}>
    <Combobox.Options as={Fragment}>
        {() => (
            {options.map((option) => (
                <Combobox.Option as={Fragment} {...optionProps}>
                    {({ active }) =>
                        <li className={`combo-box__option${active ? " combo-box__option--active" : ""}`}>{name}</li>
                    )}
                </Combobox.Option>
            ))}
        )}
    </Combobox.Options>
</Combobox>
```

I am using React Testing Library to make sure that the "active" class is added when the option is hovered. My test looks like this:
```
it(`sets active options as "active"`, async () => {
    const user = userEvent.setup();
    render(<TestComboBox />);

    // open the dropdown
    await user.click(screen.getByRole("button"));
    await user.hover(screen.getAllByRole("option")[3]);

    // the active option should have the active class
    expect(screen.getAllByRole("option")[3]).toHaveClass(
        "combo-box__option--active",
    );

    // only one option should be active
    expect(
        document.querySelectorAll(".combo-box__option--active").length,
    ).toBe(1);
});
```

What I’m expecting to happen is something like this:
1. The test triggers a "hover" event
2. headless UI updates the option with an `active = true` prop
3. The Option component adds the `combo-box__option--active` class

However, on v1.7.5 the `active` prop is never set to `true`.</div>

**Comment by RobinMalfait** [comment]
Hey!

One of the dangers by testing another component library using lower level implementations (`user.hover`) is that this now relies on internal/private implementations. For example, if we swapped a `mouseover` to a `pointermove` and `user.hover` isn't aware of that then the tests will start breaking as well even though we didn't technically made a breaking change.

I think in an ideal scenario we expose some testing utils for making tests in users' code easier. We currently don't have this planned, so let's try and solve your issue another way.

We recently made an improvement where the `hover` is only making a `Combobox.Option` an active option if the mouse actually moved. Otherwise it could be that in a scrollable list, scrolling to a `Combobox.Option`, also activated another `Combobox.Option` because it just happened to be that your mouse was still in the scrollable area and mouse events were fired even though you didn't move your cursor.

Running tests in JSDom are a bit of a headache when using mouse related events because there is no cursor.

To solve it for your use case right now, I would recommend to use a different and more stable testing strategy by using keyboard events and arrow keys instead. I also added the missing `<Combobox.Input />` component.

I created a PR here that should make the tests more stable: https://github.com/grantiverson/headlessui-issue-example/pull/1

Will this work for you?
