### ISSUE TITLE
`Dialog` interferes with `ui-checked:*` on `Switch`

### ISSUE THREAD

**Issue by aaronadamsCA** [tailwindlabs/headlessui#2589]
**What package within Headless UI are you using?**

@headlessui/tailwindcss

**What version of that package are you using?**

v0.1.3

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/sandbox/nifty-curran-v34zlz

**Describe your issue**

When I use `Switch` inside `Dialog`, the `ui-checked:*` classes don't always work correctly. In the reproduction, you can see a styled switch works fine on its own, but does not work correctly within a dialog. The child `span` does not correctly translate its x-position.

Checked `Switch`:

<img width="183" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/1505561/70daa812-2df1-4331-854d-67669e726a0f">

Checked `Switch` inside `Dialog`:

<img width="198" alt="image" src="https://github.com/tailwindlabs/headlessui/assets/1505561/c6c11c42-8e21-4c5e-9014-b0a7e4988e37">

**Comment by aaronadamsCA** [comment]
I realize this would be a breaking change, but it feels like the best solution here would be to change the API design to match Tailwind v3; make me add a `group` class to my `Switch`, and then let me use `group-ui-checked:*` utility classes.

For anyone who needs a workaround, I've added a second set of switches to the reproduction URL that use `group` and `data` directly, bypassing the `@headlessui/tailwindcss` utility selectors. This works.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is unfortunately a downside of the current implementation because we can't tell CSS to _only_ look at the nearest state as far as I know. However there are some workarounds you can use. The main goal of the `@headlessui/tailwindcss` plugin was to make things a bit easier. For example the `ui-{state}` and `ui-not-{state}` variants are built in a way where you can apply the classes on the current component with the state _or any of its children_ (in your case, the nested span in the `Switch`) and it would read information from the parent. But since the `Dialog` is also setting some `data-headlessui-state` this is interfering now. But we can use this knowledge in our workarounds!

- **Workaround 1** — Use the important modifier `!` to let the `ui-checked` case win, even if the `ui-not-checked` case was winning before because of the `Dialog`.
```diff
  function StyledSwitch() {
    return (
      <Switch className="ui-checked:bg-green-500 ui-not-checked:bg-gray-400 relative inline-flex h-6 w-12 flex-shrink-0 rounded-full border-4 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
        <span
          aria-hidden="true"
-         className="ui-checked:translate-x-6 ui-not-checked:translate-x-0 pointer-events-none inline-block h-4 w-4 rounded-full bg-white transition-transform"
+         className="ui-checked:!translate-x-6 ui-not-checked:translate-x-0 pointer-events-none inline-block h-4 w-4 rounded-full bg-white transition-transform"
          //                    ^
        />
      </Switch>
    )
  }
```
- **Workaround 2** — Hoist the variant to the `Switch`, then apply it to the children. This is a bit of a mouthful, but instead of storing the classes on the inner `span` you can put them on the `Switch` itself and attach an additional `[&>*]:` variant in front. This variant will target all the direct children. Let's look at an example instead:
```diff
  function StyledSwitch() {
    return (
-     <Switch className="ui-checked:bg-green-500 ui-not-checked:bg-gray-400 relative inline-flex h-6 w-12 flex-shrink-0 rounded-full border-4 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
+     <Switch className="[&>*]:ui-checked:translate-x-6 [&>*]:ui-not-checked:translate-x-0 ui-checked:bg-green-500 ui-not-checked:bg-gray-400 relative inline-flex h-6 w-12 flex-shrink-0 rounded-full border-4 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
      {/*                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  Inject here */}
        <span
          aria-hidden="true"
-         className="ui-checked:translate-x-6 ui-not-checked:translate-x-0 pointer-events-none inline-block h-4 w-4 rounded-full bg-white transition-transform"
          //         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  Remove here
+         className="pointer-events-none inline-block h-4 w-4 rounded-full bg-white transition-transform"
        />
      </Switch>
    )
  }
```
- **Workaround 3** — Use CSS Variables. Similar to the one above, we can hoist the classes to the `Switch` itself and set a CSS variable, next we can use that variable inside the `span`.
```diff
  function StyledSwitch() {
    return (
-     <Switch className="ui-checked:bg-green-500 ui-not-checked:bg-gray-400 relative inline-flex h-6 w-12 flex-shrink-0 rounded-full border-4 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
+     <Switch className="ui-checked:[--x:theme(spacing.6)] ui-not-checked:[--x:theme(spacing.0)] ui-checked:bg-green-500 ui-not-checked:bg-gray-400 relative inline-flex h-6 w-12 flex-shrink-0 rounded-full border-4 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2">
      {/*                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Insert here */}
        <span
          aria-hidden="true"
-         className="ui-checked:translate-x-6 ui-not-checked:translate-x-0 pointer-events-none inline-block h-4 w-4 rounded-full bg-white transition-transform"
          //         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Drop this part
+         className="pointer-events-none inline-block h-4 w-4 translate-x-[var(--x)] rounded-full bg-white transition-transform"
          //                                                  ^^^^^^^^^^^^^^^^^^^^^^ Insert here
        />
      </Switch>
    )
  }
```
- **Workaround 4** — In all other cases, you can also fallback to the exposed variables directly: https://headlessui.com/react/switch#using-render-props

We've talked about this internally before where we maybe expose those states for each component but where the name of the component is encoded in the variant. That way you could do something like `ui-switch-checked` (API not decided). But this is not something that's planned right now, so I hope these workaround work for you right now.

Hope this helps!

**Comment by aaronadamsCA** [comment]
Thanks for the detailed response, appreciate it.

Our workaround of choice is to replace `@headlessui/tailwindcss` with simple custom data selectors in our Tailwind config:

```js
const config = {
  theme: {
    extend: {
      data: {
        "headlessui-checked": "headlessui-state~=checked",
        "headlessui-open": "headlessui-state~=open",
      },
    },
  },
};
```

They can be used like this:

```jsx
<Switch className="group relative ... bg-gray-400 data-ui-checked:bg-green-500">
  <span
    aria-hidden="true"
    className="... transition-transform translate-x-0 group-data-ui-checked:translate-x-6"
  />
</Switch>
```

You can see it in action here: https://codesandbox.io/p/sandbox/spring-fire-x8c96n

I hope you'll consider changing the API in the next `@headlessui/tailwindcss` major release to use `group` modifiers like this. It's a much better fit with the rest of Tailwind, the selectors are much less complex, and the results are more reliable. Thankfully it only takes a few lines of config to recreate on our own.
