### ISSUE TITLE
cannot switch between popovers with button: as="div"

### ISSUE THREAD

**Issue by ahoyahoy** [tailwindlabs/headlessui#2595]
If I use as="div" for the popover-button, I can't switch between popovers, but the popover just closes.
Without as="..." it works as expected and clicking the button opens another popover.
I found the same behavior for Menu.

minimal example
https://stackblitz.com/edit/github-lbvgvg?file=src%2FApp.vue

**Comment by adamwathan** [comment]
While the `Popover.Button` does have an `as` prop, the intention is that you ultimately still use it to render a button, like `<Popover.Button as={MyStyledButton}>`.

Buttons and `div` elements are very different with very different default behavior and we don't do the work internally in Headless UI to make sure that whatever element you pass in is modified/extended to have all of the default behavior (in terms of event handling and stuff) that a button has.

What's the reason you want to use a `div` here instead of a `button`? Semantically if something can be clicked to trigger an action, it's important that it's a `button`.

**Comment by ahoyahoy** [comment]
I understand. Thanks
