### ISSUE TITLE
lost transition effect if using 'top-x'

### ISSUE THREAD

**Issue by korosu** [tailwindlabs/headlessui#2597]
```js
<Transition.Child
            enter="transition ease-in-out duration-300 transform"
            enterFrom="translate-x-full"
            enterTO="-translate-x-0"
            leave="transition ease-in-out duration-300 transform"
            leaveFrom="-translate-x-0"
            leaveTo="translate-x-full"
          >
            <div className="absolute bottom-52 right-0">
              <p className=" text-gray-100 text-xl">{prix} euro</p>
              <p>
                {qty}
              </p>
            </div>
          </Transition.Child>
```
this work fine , but if replace 'bottom-52' with 'top' the transition will lost effect

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I can't seem to reproduce this issue, but here is a CodeSandbox that renders both examples and they seem to work as expected: https://codesandbox.io/p/sandbox/github/tailwindlabs/reproduction-headlessui-react/tree/main

If this is still an issue for you, can you open a new issue with a minimal reproduction repo or CodeSandbox attached so that we can take a look?

In the meantime:
- Make sure that you rebuild the CSS to ensure that the `top-52` is included in the final CSS.
