### ISSUE TITLE
RadioGroup generates `aria-labelledby` value that does not exist

### ISSUE THREAD

**Issue by dlindahl** [tailwindlabs/headlessui#2631]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.7.16 (or whichever is used to build the examples on headlessui.com)

**What browser are you using?**

Chrome

**Reproduction URL**

https://headlessui.com/examples/react-radio-group-hero

**Describe your issue**

The `aria-labelledby` property for the root `RadioGroup` component references an element that does not exist in its sub-tree. In the official example on headlessui.com, I would expect the root component's `aria-labelledby` value to match the `id` of its first child, the `label` tag with an `id` value of `headlessui-label-:R1m:`. Instead, the `aria-labelledby` value is `headlessui-label-:Rr6:`.

Additionally, `headlessui-label-:Rr6:` does not match any element.

![Screenshot 2023-07-31 at 10 18 02 AM](https://github.com/tailwindlabs/headlessui/assets/55945/9190e999-7ff7-4099-999d-2f834a9270a9)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Luckily this was not a bug in Headless UI itself but a bug because of the setup in our documentation website. This should now be solved.

If you run into this issue in your own projects then I would recommend to open a new issue with a minimal reproduction repo attached so that we can take a look.

Thanks again!
