### ISSUE TITLE
Transition component enter animation does not show up

### ISSUE THREAD

**Issue by chsir17** [tailwindlabs/headlessui#2636]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.16

**What browser are you using?**

Chrome

**Reproduction URL**

[Using v1.7.16](https://codesandbox.io/s/fz8rl6?file=/src/App.js)
[Using v1.7.11](https://codesandbox.io/s/react-hot-toast-tailwindcss-headless-ui-forked-3mf2kd?file=/src/App.js)
[Using v1.6.4](https://codesandbox.io/s/react-hot-toast-tailwindcss-headless-ui-forked-fpw3jc?file=/src/App.js)

**Describe your issue**

I am using [react-hot-toast](https://github.com/timolins/react-hot-toast) with the transition component from headless ui. I've linked code sandbox example I've found and the enter animation seems to be broken in recent versions.

The enter animation has different buggy behaviours when changing package version:

- When using v1.7.16 there is no enter animation
- When using v1.7.11 there is no animation for the first toast after a refresh
- When using v1.6.4 the enter animation works and has a normal behaviour

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #2646, and will be available in the next release. We also added this specific example as one of our manual tests for future reference: https://headlessui-react.vercel.app/transitions/react-hot-toast

You can already try it using:
- `npm install @headlessui/react@insiders`.
