### ISSUE TITLE
reopen: tab content is not displayed when components are imported async

### ISSUE THREAD

**Issue by ahoyahoy** [tailwindlabs/headlessui#2640]
I'd like to reopen https://github.com/tailwindlabs/headlessui/issues/2596

I didn't get why you asked questions and closed the ticket without an explanation and the possibility to respond :)

Since the components work fine with import() (and they should), only except for the initial state (only for first render), I guess it should not be difficult to fix this situation?

Could i ask about the obstacles rather than researching the whole repo?

thx :)

**Comment by RobinMalfait** [comment]
Hey!

Sorry for the delay. As mentioned in the original issue #2596, closing an issue doesn't mean that the conversation is over. Closing is more of a way to know that we handle an issue and if new information is available that wasn't available yet that results in the fact that an actual issue is present in Headless UI then we can take next steps and re-open the issue if necessary.

In this case, the potential solution I provided was not enough for your use case which is totally fine. But now that I know your use case a bit more, I dug deeper to see what's going on exactly.

It just took a bit of time on my end to get back to this issue, my apologise for this.

That said, this should be fixed by #2642, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
