### ISSUE TITLE
`<PopoverButton>`: Component inside <Transition> renders non-element root node that cannot be animated.

### ISSUE THREAD

**Issue by DamianGlowala** [tailwindlabs/headlessui#2665]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Chrome

**Reproduction URL**

```
<Popover>
  <Transition
    appear
    enter-active-class="duration-300 ease-out"
    enter-from-class="opacity-0"
    leave-active-class="duration-200 ease-in"
    leave-to-class="opacity-0"
  >
    <PopoverButton />
  </Transition>
</Popover>
```

![image](https://github.com/tailwindlabs/headlessui/assets/48835293/e303dbcf-9842-4704-acf8-0d91c382ea51)

**Describe your issue**

Same as https://github.com/tailwindlabs/headlessui/issues/1629, but for the `<PopoverButton>` component.

**Comment by RobinMalfait** [comment]
Hey!

A few things are going on here. The built-in Transition component requires the child to be a single DOM node (even if you forward all the props / attributes to the correct element internally).

Our `PopoverButton` renders a button and a sibling focus guard for accessibility purposes. They are both wrapped in a `Fragment` to ensure we only return a single component from `render`.

In the PR you mentioned (#1692) we were able to make the outer element the actual `PopoverPanel`, but in this case that's not possible because otherwise we would render something like this:
```html
<button>
  The Popover button
  <button>The focus guard button</button>
</button>
```

One solution we could apply is wrapping those buttons in a real element which would look like this:
```html
<span>
  <button>The Popover button</button>
  <button>The focus guard button</button>
</span>
```

But this would be a breaking change because it could break the layout of existing applications out there. We would also need to find a way to ensure that you can put classes on the `span` and/or on the `button` for the `PopoverButton` itself.

The good news is that there are some solutions we can apply outside of a Headless UI fix right now:

1. Wrap the `PopoverButton` in an element yourself:
```diff
  <Popover>
    <Transition
      appear
      enter-active-class="duration-300 ease-out"
      enter-from-class="opacity-0"
      leave-active-class="duration-200 ease-in"
      leave-to-class="opacity-0"
    >
-     <PopoverButton as="button" />
+     <div>
+       <PopoverButton as="button" />
+     </div>
    </Transition>
  </Popover>
```

This would make the built-in Transition component happy because now there is a "real" DOM node being used (the `div`). You also have control over the elements such that you can apply classes if you need to add additional classes.
With the classes you are applying in the example, this shouldn't make any difference to the output because you are just using an opacity transition. (I do realise that this is a reproduction so might be a bit different in the real code)

2. Use Headless UI's Transition component

The component we expose can handle this because we just forward the props to the child component and since the `PopoverButton` forwards every prop and attribute to the underlying DOM node this should solve it.

```diff
  <Popover>
-   <Transition
+   <TransitionRoot
+     show
      appear
-     enter-active-class="duration-300 ease-out"
+     enter="duration-300 ease-out"
-     enter-from-class="opacity-0"
+     enter-from="opacity-0"
+     enter-to="opacity-100"
-     leave-active-class="duration-200 ease-in"
+     leave="duration-200 ease-in"
-     leave-to-class="opacity-0"
+     leave-from="opacity-100"
+     leave-to="opacity-0"
    >
      <PopoverButton as="button" />
-   </Transition>
+   </TransitionRoot>
  </Popover>
```
And don't forget to import `TransitionRoot` from `@headlessui/vue`.

Would this work for you?

Hope this helps!

**Comment by DamianGlowala** [comment]
Hey Robin!

I really appreciate the effort you put to write an in-depth explanation of what is happening behind the scenes and how tricky (or impossible) it is to make this work without introducing other breaking changes.

The alternative approach no 2 sounds best and works _flawlessly_, thanks! 💯

Do you think this is worth mentioning in the Vue part of the `<Popover>` docs or is it a relatively rare use-case and having it documented in this issue alone is more than enough?
