### ISSUE TITLE
Importing Components from HeadlessUI then using them in another project gives an error

### ISSUE THREAD

**Issue by LeviXIII** [tailwindlabs/headlessui#2670]
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2632

<div type='discussions-op-text'>

<sup>Originally posted by **LeviXIII** July 31, 2023</sup>
I'm trying to use the Menu component in one of my projects which acts as a package for another project I have. I can install the package correctly and use the component correctly. The problem comes when I am importing the package in another project. That project uses headlessui as well and functions fine. I get this error as soon as I start up my project though:

> react.development.js:220 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

The code in the project being imported is simple:
```
<Menu>
   <div>Something</div>
</Menu>
```

I'm aware that Menu should have more in it, but if I add `Menu.Button` or `Menu.Items` I get null pointers on Button and Items.

I've also seen a similar issue posted on stackoverflow:
https://stackoverflow.com/questions/73153159/components-importing-headlessui-throwing-errors-when-built-and-then-used-in-anot

I'm using react 17.0.2, tailwindcss 3.3.3, barrelsby 2.3.4, and gulp. </div>

**Comment by thecrypticace** [comment]
Without a reproduction to look at I'm afraid I might not be of much help here. I suspect that something is happening to the exports and they're being tree-shaken or overwritten but neither of which should be possible. Is there a chance you could you provide a reproduction?

Also, as an aside, **the accepted stack overflow answer is incorrect**. The core of the problem is that, in Node/NPM, exports is _the way_ to define dual ESM/CJS builds. Because webpack overloads require such that it can handle CJS _and_ ESM that means that it's up to webpack to handle this case — not Headless UI. The user can override the behavior by utilizing webpack aliases which is what should've been suggested.

**Comment by LeviXIII** [comment]
Ok, thanks for responding. I'll check out the way I'm bundling first.

**Comment by thecrypticace** [comment]
Hey, gonna close this one for now. If you're able to create a reproduction we can take a look at please feel free to open another issue. Thanks! ✨

**Comment by arjunpredev** [comment]
Hey there @thecrypticace I'm receiving the same problem and I'm trying to build my project with webpack. Do you have an example of how this would work in a webpack.config.js?
