### ISSUE TITLE
'Dialog' is not exported from '@headlessui/react'

### ISSUE THREAD

**Issue by mkrkelj1** [tailwindlabs/headlessui#269]
I've tried installing both the main (`^0.3.1`) and dev (`^0.3.1-d519f7d`) branches respectively. The code I just lifted from the docs: 

```
import { useState } from "react";
import { Dialog } from "@headlessui/react";

function Example() {
  let [isOpen, setIsOpen] = useState(true)

  return (
    <Dialog open={isOpen} onClose={setIsOpen}>
      <Dialog.Overlay />

      <Dialog.Title>Deactivate account</Dialog.Title>
      <Dialog.Description>This will permanently deactivate your account</Dialog.Description>

      <p>
        Are you sure you want to deactivate your account? All of your data will be permanently
        removed. This action cannot be undone.
      </p>

      <button onClick={() => setIsOpen(false)}>Deactivate</button>
      <button onClick={() => setIsOpen(false)}>Cancel</button>
    </Dialog>
  )
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `Dialog` component is not released on the latest version yet. It is released on the `dev` tag.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.

Make sure you are on the latest `dev` branch (`0.3.1-d519f7d` not `^0.3.1-d519f7d`).
Also verify that that is the actual correct version in your `node_modules`.

The pinned version number is important, because `0.3.1-d519f7d` resolves only to `0.3.1-d519f7d`. But `^0.3.1-d519f7d` can resolve to `0.3.1`, `0.3.1-ece9b5f` and `0.3.1-d519f7d`.

Here is a codesandbox that prints the version and all exported components (including Dialog):
https://codesandbox.io/s/nervous-proskuriakova-69yg5?file=/src/index.js
