### ISSUE TITLE
Transition component enter animation does not work with Combobox and virtualized rendering

### ISSUE THREAD

**Issue by denisgursky** [tailwindlabs/headlessui#2696]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

[Codesandbox](https://codesandbox.io/s/hungry-lalande-3l5psc?file=/src/App.tsx)

**Describe your issue**

Transition's enter animation doesn't work when rendering Combobox options via [react-virtual](https://tanstack.com/virtual/v3/docs/adapters/react-virtual)

https://github.com/tailwindlabs/headlessui/assets/6468871/ecd75c38-9d5e-4946-8fc9-94ab08e8d661

**Comment by thecrypticace** [comment]
Hey! So we don't currently support virtual scrollers using things like `react-virtual`. This is because some things like keyboard navigation of items won't work properly without direct involvement and integrations in Headless UI.

Even with that, I dug into this a bit more because the behavior seemed super strange. Under the hood `react-virtual` basically calls `Element.scrollTo(…)` in `useLayoutEffect` for every render. In this case, it stops the transition from running for elements that were just inserted into the DOM. Now, I don't know why this is but you can reproduce this without `react-virtual` being involved by removing the react-virtual code and adding something like this to the `<Options>` component:

```js
useLayoutEffect(() => {
  parentRef.current.scrollTo?.({ top: 0 })
})
```

This issue is quite similar to this one — which seems to be a quirk of browsers handling just-mounted elements (and their descendants) in the DOM: https://github.com/tailwindlabs/headlessui/issues/2557#issuecomment-1684339882

The minimal HTML/JS-only reproduction for this issue is the same as the one above except for swapping out some code to call `scrollTo` before classes are added.

There's unfortunately probably not much we can do here to fix this until such a time that we build in native virtual scrolling support in the future. Sorry :(
