### ISSUE TITLE
Button in Popover.Button components break nextjs hydration in React 18

### ISSUE THREAD

**Issue by MFrizzy** [tailwindlabs/headlessui#2744]
**What package within Headless UI are you using?** 

@headlessui/react 

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Chrome, Safari

**Reproduction URL**

https://codesandbox.io/p/sandbox/lucid-mestorf-8t23t8

**Describe your issue**

When providing a button as children of Popover.Button, hydration doesn't work in nextjs 13 + react 18 (worked fine in next 12/ react 17)

More to add, i tried to add `as="div"` in my Popover.Button, works in the sandbox, not in my project, searching to find a way to reproduce

**Comment by RobinMalfait** [comment]
Hey!

You don't want to render a button inside a button. The `Popover.Button` already is a button so you can add all the necessary props to that component as is.

Alternatively you can use the following syntaxes:
```js
<Popover.Button as={Fragment}>
  <button>...</button>
</Popover.Button>
```

This will make sure the `Popover.Button` doesn't render a `button` by default and it will forward all the necessary props to the `<button>` that you are rendering as the `children`.

Alternatively, you can use this syntax: 
```js
<Popover.Button as="button">
  ...
</Popover.Button>
```

But since this is the default, you don't have to do this.

If, you want to render a custom button component, you can do that as:
```js
<Popover.Button as={Fragment}>
  <MyCustomButton>...</MyCustomButton>
</Popover.Button>
// OR
<Popover.Button as={MyCustomButton}>
  ...
</Popover.Button>
```

But make sure to forward the props & ref to the underlying `button` component in the  `MyCustomButton` component.

```js
const MyCustomButton = React.forwardRef((props, ref) => {
  return <button ref={ref} {...props} />
})
```

Hope this helps!
