### ISSUE TITLE
React: Visible flicker when selecting an option in Listbox wrapped in Transition

### ISSUE THREAD

**Issue by dd-jonas** [tailwindlabs/headlessui#2751]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17

**Reproduction URL**

https://stackblitz.com/edit/react-ts-wtdwdo?file=App.tsx

Left Listbox uses Transition, right one doesn't. Only the left one has the visible flash mentioned before.

**Describe your issue**

When selecting a Listbox option that is wrapped in Transition, there seems to be an extra render cycle before the options window closes. This is especially visible in my case as I render a check icon in front of the selected option, which means that this icon can be quickly seen appearing before the options close, causing a visual flash.

Here's a x16 slowed down GIF. The check icon should not be visible, only after reopening the  options it should show.
![trimmed-1dvz8n1u_RQo8HXUL](https://github.com/ycs77/headlessui-float/assets/69415794/fc9ccba0-3239-49b2-8082-d831d5962b62)

**Comment by RobinMalfait** [comment]
Hey!

This is currently expected behavior because the `Transition` component delays the unmounting of component it is transitioning. In your case it looks like you don't have any transition related classes attached to it. 

If this is because you wanted to provide a very minimal case without all those classes attached then I would assume that you would see a transition effect in your real application. If the component is used as-is without transition related classes on them then you can safely remove the wrapping `Transition` component (which you did in the second example).

Let's say you _do_ have a transition effect but you are seeing the change in data as well causing a "flicker". Right now we don't have a snapshot feature where we capture the DOM right before transitioning to maintain the state at that point in time. Instead, we do allow child components to update while transitioning out.

A very basic implementation of such a snapshot could look like this:
```js
function Snapshot({ children, value }) {
  let [snapshot, setSnapshot] = React.useState(null);
  let container = React.useRef(null);

  let previousValue = React.useRef(value);
  let previousHTML = React.useRef('');

  React.useLayoutEffect(() => {
    if (!container.current) {
      return;
    }

    if (snapshot) {
      return;
    }

    if (previousValue.current !== value) {
      setSnapshot(
        <div dangerouslySetInnerHTML={{ __html: previousHTML.current }} />
      );
      previousValue.current = value;
    }
    previousHTML.current = container.current.outerHTML;
  });

  return snapshot ?? <div ref={container}>{children}</div>;
}
```

Then you can use it as:
```diff
    <Listbox value={value1} onChange={setValue1} as="div">
      <Listbox.Button>{value1 ?? "Select"}</Listbox.Button>

      <Transition as={React.Fragment}>
        <Listbox.Options>
+         <Snapshot value={value1}>
            {people.map((name) => (
              <Listbox.Option key={name} value={name} className="option">
                <span className="check">✓ </span>
                {name}
              </Listbox.Option>
            ))}
+         </Snapshot>
        </Listbox.Options>
      </Transition>
    </Listbox>
```

To wrap things up, this isn't a bug to me, but a feature request for a snapshot like feature. This is a very interesting feature, but I can't promise if/when we will build this feature into the `Transition` component.

Hope this helps!

**Comment by dd-jonas** [comment]
Thanks for the quick answer and detailed explanation! I am not using any transition classes, instead I was redirected here from https://github.com/ycs77/headlessui-float/issues/61. I guess I could add a small transition to make the layout shift less noticeable. The Snapshot component looks like a promising feature though.

Cheers!
