### ISSUE TITLE
Using `appear: true` ignores transition events when unmounting

### ISSUE THREAD

**Issue by ynnoj** [tailwindlabs/headlessui#276]
Thanks for your great work on this lib! ❤️ 

I'm trying to use the `appear` prop on a `<Transition />` component in my Next.js application. The parent component is conditionally rendered using the same prop that is passed to `show`. This works great when mounting, however when unmounting the transition event/classes are ignored.

Is there an approach I can use so that the outward transition classes are visible before the component is unmounted?

**Comment by jamosaur** [comment]
@ynnoj I had this issue yesterday while showing notification toasts, the way I got around it was adding a `show` prop to my toast data. On removal of the notification toast, I set `show` to false (this triggers the outward transition) then in a timeout I remove the data once the animation time is finished.

here's my code as an example for you:
```js
export function ToastContextProvider({ children }) {
  const [toasts, setToasts] = useState([]);

  const addToast = useCallback(
    (toast) => {
      const transformedToast = {
        show: true,
        ...toast,
      };
      setToasts((existingToasts) => [...existingToasts, transformedToast]);
    },
    [setToasts]
  );

  const removeToast = useCallback(
    (id) => {
      setToasts((existingToasts) => [
        ...existingToasts.map((toast) => {
          if (toast.id === id) {
            return { ...toast, show: false };
          }

          return toast;
        }),
      ]);

      setTimeout(() => {
        setToasts((existingToasts) => [
          ...existingToasts.filter((toast) => toast.id !== id),
        ]);
      }, 1000);
    },
    [setToasts]
  );

  return (
    <ToastContext.Provider value={{ addToast, removeToast }}>
      {children}
      <div className="absolute top-4 right-4 w-80">
        {toasts.map((toast) => (
          <Transition
            show={toast.show}
            appear={true}
            key={toast.id}
            enter={'transform ease-out duration-300 transition'}
            enterFrom={
              'translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2'
            }
            enterTo={'translate-y-0 opacity-100 sm:translate-x-0'}
            leave={'transition ease-in duration-1000'}
            leaveFrom={'opacity-100'}
            leaveTo={'opacity-0'}
          >
            <Toast
              removeToast={removeToast}
              id={toast.id}
              title={toast.statusText}
              subtitle={toast.data.message}
            />
          </Transition>
        ))}
      </div>
    </ToastContext.Provider>
  );
}
```

**Comment by ynnoj** [comment]
@jamosaur Thanks for replying and providing an example.

I figured a separate prop to control mounting would provide a clear path forward. Will take that approach for now!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you render a parent with something like `{expression && <ChildComponentWithTransitions />}` then the Transition cannot transition out, since it will already be removed.

What you can do, is instead of using that check, do something like this:

```tsx
<Transition show={expression}>
  <ChildComponent />
</Transition>
```

Inside your ChildComponent, you can then use the `<Transition.Child />` component. A few things will happen:

1. The parent component won't transition (because you didn't provide `enter`, `enterFrom`, ... props), but will conditionally render.
2. The parent component will also delay the unmounting until all the `Transition.Child` components are done.
3. The `Transition.Child` components will inherit the `show` prop.

More information about this can be found here: https://github.com/tailwindlabs/headlessui/tree/main/packages/%40headlessui-react#co-ordinating-multiple-transitions
