### ISSUE TITLE
React Listbox - Inconsistent accessibility labels for selected and not selected items

### ISSUE THREAD

**Issue by tobeycodes** [tailwindlabs/headlessui#2774]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

latest

**What browser are you using?**

Chrome

**Reproduction URL**

Bug is present in examples https://headlessui.com/examples/react-listbox-hero

**Describe your issue**

The selected and not select labels for accessibility differ
- Tom Cook not selected, (1 of 6)
- Wade Cooper, selected, (4 of 6)

I would expect a comma to appear after the value on the non selected values

**Comment by RobinMalfait** [comment]
Hey!

Thanks for the report, unfortunately we don't have control over the exact values here because that's controlled by the browser / VoiceOver for example.
Internally, we just set a few `aria-*` related attributes and the browser does the rest.

Going to close this for now since we don't have control over these values.

Thanks!
