### ISSUE TITLE
Slot's refs resolve later since 6444e01

### ISSUE THREAD

**Issue by AEM5299** [tailwindlabs/headlessui#2789]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

latest

**What browser are you using?**

Chrome

**Reproduction URL**

Broken (0.0.0-insiders.6444e01): https://codesandbox.io/p/sandbox/not-working-6444e01-jr3qqx?file=%2Fsrc%2Fmain.js

Working with older version (0.0.0-insiders.5a3d556): https://codesandbox.io/p/sandbox/working-5a3d556-87497y?file=%2Fsrc%2Fmain.js

**Describe your issue**

Since 6444e01 commit, the slot refs seems to resolve tiny bit later (I think it's nextTick). If you have a look at the working reproduction url in the `main.js` file, it can access and logs successfully the correct element. However, in the broken reproduction, it will log `null` instead. If I delay the log by few milliseconds it does log the correct element.

I isolated the issue to the commit mentioned above, but not quite sure why yet. I happen to have an application that relies on the old behaviour, where the ref is immediately accessible, so hoping this can be fixed.

**Comment by thecrypticace** [comment]
Yes, any refs inside a portal are delayed by one tick after mount. The reason this happens is because if they're not SSR generates entirely different HTML than hydration — and that's not allowed by Vue — and in some cases causes errors. Because portals don't work on SSR this can result in large trees of HTML / DOM nodes that are present during hydration but not SSR.

I'm 99% sure we _cant_ change this without breaking SSR again. it's an either/or situation afaik. I'll give this some more thought but I'd suggest using a `watch` on the ref with an if check rather than `onMounted()` which should work no matter what.

**Comment by thecrypticace** [comment]
Hey, so @RobinMalfait and I discussed this and given that this fixes something fairly important _and_ follows the recommendations [from Vue's own docs](https://vuejs.org/guide/scaling-up/ssr.html#teleports) this is unlikely to be something we'll change back.

I've updated your codesandbox using my suggestion — though in this case since it's not using onMounted but directly accessing it from expose I'm using `watchEffect` instead of `watch`:

You can see it working here:
https://codesandbox.io/p/sandbox/not-working-6444e01-forked-k9y9c2?file=%2Fsrc%2FApp.vue%3A45%2C19

In general it should be feasible to change behavior such that even when refs are not immediately accessible things should still be able to react accordingly when they become available. If you have a specific situation that can't do this please post it here and we'll try to provide some suggestions to see if we can figure out a way to make it work.

Hope that helps!
