### ISSUE TITLE
Should users be allowed to specify a DOM node for Dialog to portal to?

### ISSUE THREAD

**Issue by mperrotti** [tailwindlabs/headlessui#280]
I have a use case where only part of the UI is covered by a Dialog and Dialog.Overlay. Currently, I can't think of a good way to do this without picking a specific place for the Dialog to portal to.

This seems like an intentional restriction. If so, I'd appreciate hearing from one of the maintainers about why a Dialog can only Portal to a div rendered to the root. If it's not intentional, I would be happy to submit a PR that adds the ability to choose where the Dialog portals to.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

You can think of Dialogs like pages, but rendered inside the current page. Once you are interacting with a Modal/Dialog, you should not be able to interact with anything else on the page. If you think about the "A dialog is a page in the current page", then it makes sense that you cannot interact with the previous page you were on.

That said, from an accessibility perspective, once you render a Dialog with `role="dialog"`, screenreader users cannot escape this Dialog, unless they trigger an action inside the Dialog that closes it, or when they press escape.

If you think about your use case where only a part is covered by the Dialog, does that mean that you can still interact with the other part? If so, keep in mind the accessibility aspect and that those users can't use that part of the screen.

I'm going to close this for now, but if things are not clear then feel free to comment on this issue so that I can re-open it if you have outstanding questions. If you tell us more about your exact use case, then we can probably recommend you another component that might fit the problem better.

**Comment by kieranm** [comment]
@RobinMalfait Thank you for the explanation.

We use Next.js and have a custom `<DarkMode enabled={true}> ... </DarkMode>` wrapper in `_app.tsx` which sets the "dark" class using a `<div>` - enabling us to use the `dark:` selectors that Tailwind offers. Ideally modals should render inside this wrapper so that they render in dark mode correctly.

There are probably other ways to solve this problem but it would be good to get your thoughts on whether or not you think this is a valid use case for being able to specify the DOM selector in which to place the portal.

**Comment by RobinMalfait** [comment]
Hey @kieranm 

The biggest issue with this is that we have to mark all other content as `inert` and fallback to `aria-hidden="true"` so that screenreaders don't read other content, but only the content in the Dialog.

By using a portal by default, we can mark all direct children of the `body` as inert, but we don't have to go deeply nested. If we render a Dialog deeper in the tree, then we have to make sure to mark all content as inert, but not the dialog and all of its parents. This becomes pretty hard to maintain and might affect performance since we would have to crawl the whole DOM tree.

One thing that is important to know with Portals is that the DOM tree is different, but the React tree is still correctly nested. This means that you should still be able to use React's context.

So to fix your problem, I think using `context` could be a really good fit. I created a small repo for you here: (https://github.com/RobinMalfait/headlessui-dark-mode-context). The most important parts can be found here:

- Usage outside the Dialog: https://github.com/RobinMalfait/headlessui-dark-mode-context/blob/main/pages/index.js#L25-L31
- Implementation: https://github.com/RobinMalfait/headlessui-dark-mode-context/blob/main/pages/index.js#L36-L51
- Usage inside the Dialog: https://github.com/RobinMalfait/headlessui-dark-mode-context/blob/main/pages/index.js#L73-L78

What do you think of this approach? Would this help you to solve your problem?

**Comment by kieranm** [comment]
Thank you @RobinMalfait for taking the time to put that together! It's super helpful and we will switch to that approach.

**Comment by NikitaIT** [comment]
@RobinMalfait below I described a scenario that is now difficult to implement with headlessui
@mperrotti this workaround might work

It may sound strange, but I do most of the portals in the main interface.

This is a pretty good approach in terms of space utilization.

For an ordinary user, this always moves the focus along the red arrows (pic 1) in the context of the main page, since the portal is part of it.

I use the poppover behavior for implementation, but poppover does not allow control over hiding, this greatly interferes in cases where I want the opened popover to be visible for a while and could be hidden by the button inside.
And i use my own portals for this(This works because aria-controls can target any element on the page).

Moreover, if the dialog contains a lot of things, then I always avoid the dialog by creating nested pages like a normal router-view.

On mobile, this turns into a Dialog or Disclosure or "embeds" in different ways.

It's not really about dialogs, of course, but it's a pretty good way to avoid dialogs and tooltips in cases where I need to build a non-blocking interface.

Example:
![image](https://user-images.githubusercontent.com/16810067/122657575-14744b80-d165-11eb-8b3b-7c1c6c1564c5.png)
