### ISSUE TITLE
[Bug]: iOS scroll issues

### ISSUE THREAD

**Issue by Emiliano-Bucci** [tailwindlabs/headlessui#2801]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v1.7.17

**What browser are you using?**

For example: Chrome (MacOs) and iOS v16/v17

**Reproduction URL**

https://github.com/tailwindlabs/headlessui/blob/0276231c31/packages/%40headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts#L27-L28

**Describe your issue**

I have a header that should appear/disappear when user scrolls up/down. It seems that, for some reason, on iOS devices, on the `handleIOSLocking` method, the library is making some scroll, causing the header to disappear (this is because the window.scroll event is fired). So, the problem is that on iOS devices, when a dialog is opened the `window.onscroll` event is fired, which I guess is an unintentional side effect. Can this be fixed or bypassed, somehow?

This is also causing issues on iOS if the Dialog si animated with **react-spring** during layout calculation (because of the scroll). There should be a way to opt out this hacky stuff...

**Update**: If someone is facing the same issue, a quick fix can be done by modyfing the original window.scrollTo 
```
window.scrollTo = () => {}
```

**Comment by huntersfuntime** [comment]
I'm having a similar issue that seems to be from this code https://github.com/tailwindlabs/headlessui/discussions/2388#discussioncomment-5709250

**Comment by thecrypticace** [comment]
Hey so the use of `scrollTo` is intentional as it is used to work around an issue on iOS when implementing scroll locking. The behavior you're seeing is a byproduct of us doing these two things on iOS:
- Adding a `margin-top` to the document equal to the current vertical scroll offset
- Subsequently resetting the scroll position via `window.scrollTo(0, 0)`

The scrolling causes the Safari browser chrome to extend as when it's in it's collapsed state the viewport is almost always scrollable. In addition, this is one of the requirements to prevent the screen from jumping up and back down a full page (or something close to that) when focusing form inputs in a dialog. Though I think we might be able to augment this to only trigger when focusing form inputs. I'll have to look into that. But, in general, this behavior is done on purpose because, on iOS, `overflow: hidden` is not enough to implement scroll locking.

If you want to side-step this I would suggest either:
1. Going with your solution — but know that this will break scroll locking on iOS in some situations; or
2. Set some state in a context when a dialog is open such that you can disable the header appear/disappear while the dialog is open.

**Comment by Emiliano-Bucci** [comment]
@thecrypticace Since this "feature" could potentially break (like in my case) I don't see how this can be considered a solution. If you're ok with this, ok 👎
