### ISSUE TITLE
More helper-components like Transition for much more readability!

### ISSUE THREAD

**Issue by machiaveli88** [tailwindlabs/headlessui#281]
Hello together!
First of all, I am a huge fan of yours and love tailwindcss. Unfortunately, headlessui is still in its beginnings (but the idea behind it is awesome!), so it's hard to use for productive everyday life. But one component stands out: `<Transition />`!

In fact, besides the functionality, this component extremely helps to improve the readability of the code. For example something like this

```
<div className={`absolute left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0 z-30${ open ? ' transition ease-out duration-200 opacity-100 translate-y-0' : ' transition ease-in duration-150 opacity-0 translate-y-1' }`} />
```

turns into the much more readable (and more functional)

```
<Transition
    className="absolute left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0 z-30"
    show={!!open}
    enter="transition ease-out duration-200"
    enterFrom="opacity-0 translate-y-1"
    enterTo="opacity-100 translate-y-0"
    leave="transition ease-in duration-150"
    leaveFrom="opacity-100 translate-y-0"
    leaveTo="opacity-0 translate-y-1"
/>
```

The question is why not make more helper components, for example for conditions and responsiveness. With something like `<Condition if={bool} then="classname" else="classname" />` or `<Condition cond={bool} true="classname" false="classname" />` the example from the beginning would turn to 

```
<Condition
    cond={open}
    true="transition ease-out duration-200 opacity-100 translate-y-0"
    false="transition ease-in duration-150 opacity-0 translate-y-1"
    className="absolute left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0 z-30"
    as="div"
/>
```
and would therefore be much more readable. Multiple conditions could easily be nested. Conceivable would also be a condition component with several options (similar to switch-case).

The same with responsiveness: Something like this

```
<nav class="grid gap-y-10 px-4 py-8 bg-white sm:grid-cols-2 sm:gap-x-8 sm:py-12 sm:px-6 lg:px-8 xl:pr-12" />
```

would turn to 

```
<Responsive
    onSmallUp="grid-cols-2 gap-x-8 py-12" // or onSmall, small, sm, ...
    onLargeUp="px-8"
    onExtraLargeUp="pr-12"
    className="grid gap-y-10 px-4 py-8 bg-white"
    as="nav"
/>
```

I personally would find these helper classes really cool and since they don't involve much logic, they should be easy to implement. I'm sure other users would be happy about this feature as well because the biggest criticism I always hear about tailwindcss is just these long and badly readable class names.

**Comment by alexanderbluhm** [comment]
This is an interesting idea but I think it is definetely out of the scope of HeadlessUI.

Also the idea to have a condition as a (functional) component feels a bit weird.
Personally I would do something like this instead:
```jsx
<div className={resolveResponsive({
   sm: "grid-cols-2 gap-x-8 py-12",
   md: "px-8",
   // ...
})}
```
For conditional classes this concept is already implemted, e.g., in [classnames](https://github.com/JedWatson/classnames)

With the new Tailwind JIT compiler something like `sm:{grid-cols-2 gap-x-8 py-12}` would also be very interesting and create some more clarity.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

As @alexanderbluhm already mentioned, this is out of the scope of Headless UI. 

There are also a few concerns that we have to take into account:

- Headless UI is created by people from Tailwind Labs, but it can be used without Tailwind CSS. You can use your own css or other css frameworks.
- If you look at the Responsive example with `onSmallUp`, those suddenly are dependant on Tailwind, we are dependant on the `screens` config, we have to create a mapping from `sm` to `onSmallUp`. We also introduce an issue that this is not purgeable.

While the ideas look cool, I don't think they are a good idea, they introduce too many issues imo.

For example, if you look at the condition component. Imagine you have a component that renders a user profile card:

```jsx
export function MyComponent() {
  let [user, setUser] = useState(null)

  <Condition
      cond={user !== null}
      true="transition ease-out duration-200 opacity-100 translate-y-0"
      false="transition ease-in duration-150 opacity-0 translate-y-1"
      className="absolute left-1/2 transform -translate-x-1/2 mt-3 px-2 w-screen max-w-xs sm:px-0 z-30"
      as="div"
  >
    {user.name}
  </Condition>
}
```

This will actually crash, because `user.name` is reading the `name` property from a `user` that can be null, eventhough you have a `cond={user !== null}`. You can of course choose to not render the children inside the Condition, bu this code is still evaluated.

Another example is that now you introduce unnecessary abstractions, and your team members have to learn about these components and their API's. It's true that they already have to do that for other components, or even Headless UI components. But if you are used to writing `{user !== null && <div>{user.name}</div>}` then the `<Condition />` component can be just too much.

The reason why we have a `Transition` component is simply because React doesn't have a way to delay unmounts, therefore you can't make "transition out" transitions. So this component solves that by delaying that, and once all transitions are done we would unmount components.
