### ISSUE TITLE
Combobox nested in a Popover does not reset Options rendered after opening and closing

### ISSUE THREAD

**Issue by ferrucc-io** [tailwindlabs/headlessui#2816]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.17.15

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/s/combobox-popover-sh4pjc

**Describe your issue**

If I put a combobox in `static` mode to use it inside a popover with a search field. When the search popover closes after I typed something in the input the options don't re-render correctly after the component is reset

Here's a video reproducing:

https://github.com/tailwindlabs/headlessui/assets/8315559/a08c32f6-4c75-4b83-a62e-4c9c6868bf4f

**Comment by ferrucc-io** [comment]
As a temporary fix I've added two things to handle the closing:

onBlur on the Popover:

```
 <Popover
          className="relative"
          onBlur={() => {
            setSearchValue('');
          }}
        >
          ....
```

An event listener for Escape to make sure the state is reset:

```
 useEffect(() => {
    const handleKeyUp = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setSearchValue('');
      }
    };

    window.addEventListener('keyup', handleKeyUp);

    return () => {
      window.removeEventListener('keyup', handleKeyUp);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```


Is there a cleaner way to do this or is this the only way of composing these two components?

**Comment by RobinMalfait** [comment]
Hey!

This is happening because you are not re-setting the `searchValue` when the Popover closes. We currently don't expose lifecycle related methods to know when a popover is opened or not. 

However, the contents of the `Popover.Panel` will be mounted / unmounted based on the internal state.

Because of this, we can introduce a little `Lifecycle` component that can clear state when it gets unmounted.

I've updated your CodeSandbox with an example on how you can do that: https://codesandbox.io/s/combobox-popover-forked-tf9sq6?file=/src/App.js

We might add methods like that in the future, but for now this is a valid workaround where you can rely on Reacts "lifecycles" and act when those happen. 

Hope this helps!

**Comment by ferrucc-io** [comment]
Thanks a lot that is very helpful!
