### ISSUE TITLE
 Dialog doesn't work on ios < 13

### ISSUE THREAD

**Issue by hoandq-amela** [tailwindlabs/headlessui#2823]
In low-end devices (eg: iphone 6, IOS <= 13) when accessing screens containing components Dialog react of this library, the screen will be dead like in the video.
Error: An unexpected error has occurred.
https://github.com/tailwindlabs/headlessui/assets/133618442/2d1dfdae-62af-43d5-8cce-a8e30f09e888

**Comment by RobinMalfait** [comment]
Hey!

Currently we don't have active support for older versions of iOS but most components should just work as is. 

This is one in particular is very likely caused by the use of `ResizeObserver` which we use in the Dialog component. 
If you are running into this in your own project, then adding a polyfill for `ResizeObserver` should do the trick.

Hope this helps!
