### ISSUE TITLE
Combobox with `virtual` prop doesn't accept a non-template option

### ISSUE THREAD

**Issue by DamianGlowala** [tailwindlabs/headlessui#2829]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

Unreleased

**What browser are you using?**

n/a

**Reproduction URL**

n/a

**Describe your issue**

There doesn't seem to be a way to pass a non-template, 'static' option, e.g. to display a 'No data available' text whenever filtered options are empty. Empty white space below the combobox looks bad UX-wise.

![image](https://github.com/tailwindlabs/headlessui/assets/48835293/8f6155bc-d086-4dfc-bf98-645646b4e8e7)

Currently, without a `virtual` prop, I am adding a disabled option with a `v-if` condition:

```
<HeadlessComboboxOption
    v-if="filteredInternalOptions.length === 0"
    disabled
>
    ...
</HeadlessComboboxOption>
```

**Comment by thecrypticace** [comment]
Hey, this is a good piece of feedback. It's is a known issue with the current implementation. We'll look into a way to do this or at least some way of properly supporting empty states but in the meantime you actually _can_ wire things up to show one though it's definitely not ideal.

Basically what you need to do is pass a dummy option that represents your empty state instead of passing an empty array, you can then check for that option and render something different for that option. Though, that empty state can't have any interactive elements (you *might* be able to make it work with hacky code but I don't recommend it).

As an example you'd want to change the `virtual` prop to:
1. Show the empty option
2. Make sure it's disabled

```html
<Combobox
  :virtual="{
    options: filtered.length > 0 ? filtered : [{ name: 'No results', disabled: true, empty: true }],
    disabled: (option) => option.disabled || option.empty,
  }"
>
  …
</Combobox>
```

and, for `<ComboboxOptions>`, you'll want to:
1. Conditionally render the UI based on whether or not the option is the empty one
2. Mark the option as `disabled` (pretty sure this is a bug — you shouldn't have to do it in the `virtual` prop _and_ `<ComboboxOption>`)


```html
<ComboboxOptions v-slot="{ option }">
  <template v-if="option.empty">
    <ComboboxOption
      :value="option"
      disabled
    >
      <div>No people found</div>
    </ComboboxOption>
  </template>
  <template v-else>
    <ComboboxOption
      v-slot="{ active }"
      :disabled="option.disabled"
      :value="option"
    >
      {{ option.name }}
    </ComboboxOption>
  </template>
</ComboboxOptions>
```

I set up an example here:
https://headlessui-vue.vercel.app/combobox/combobox-virtual-with-empty-states

And the source for it is here:
https://github.com/tailwindlabs/headlessui/blob/24486b39ca229da53c7293ccbbfa78975c61f65e/packages/playground-vue/src/components/combobox/combobox-virtual-with-empty-states.vue

And here's a video of this working:

https://github.com/tailwindlabs/headlessui/assets/614993/be39d080-cb7a-4c2c-a033-0ba569bbdebf

**Comment by thecrypticace** [comment]
I've add a todo internally for us to find a way to make empty states work — but in the meantime I'm going to close this issue since there is at least a workaround that can be used right now.

Thanks for the feedback — it's really appreciated!

**Comment by DamianGlowala** [comment]
Thank you for your thorough explanation and linked example. Will go ahead and implement it the way you suggested. Much appreciated! 💙

**Comment by DamianGlowala** [comment]
@thecrypticace could you please provide an example equivalent to the above, where the `:value="option"` is changed to a subkey instead (e.g. `:value="option.option"`? I can't get this to work (all the options get highlighted when I hover over a single one). This might be a bug that needs addressing.

Let's take the following list as a source of data for the example:
```
let list = ref([
  { option: { label: 'Option 1', value: 1 }, disabled: false },
  { option: { label: 'Option 2', value: 2 }, disabled: false },
  { option: { label: 'Option 3', value: 3 }, disabled: false }
])
```
