### ISSUE TITLE
nextjs 14.0.3 error

### ISSUE THREAD

**Issue by zhiyongsun** [tailwindlabs/headlessui#2854]
nextjs 14.0.3 

when i added it to nextjs 14.0.3 

got error : Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

**Comment by RobinMalfait** [comment]
Hey!

This typically happens when you have multiple version of React installed. You can try to remove the `node_modules` and remove the caches `.next`. 

If you still see this issue, try to use `npm why react` and check if you seem multiple versions or not.

If this doesn't work, please open a new issue with a minimal reproduction repo attached so that we can take a look.

**Comment by cmj2002** [comment]
I have also encountered the same issue. Your proposed solutions have been ineffective for me.

I have already created a [minimal reproduction repository](https://github.com/cmj2002/headlessui2854), which is basically just the repository created by `create-next-app@14.0.3` plus ["basic example" in headlessui docs](https://headlessui.com/react/menu#basic-example).

Can you reopen it? @RobinMalfait

**Comment by virzs** [comment]
> 我也遇到过同样的问题。你提出的解决方案对我来说是无效的。
> 
> 我已经创建了一个[最小的复制](https://github.com/cmj2002/headlessui2854)存储库，它基本上只是 [headlessui 文档中加上“基本示例”](https://headlessui.com/react/menu#basic-example)创建的存储库。`create-next-app@14.0.3`
> 
> 你能重新打开它吗？

Add "use client" to the file

https://github.com/vercel/next.js/issues/42153
