### ISSUE TITLE
Menu isn't working in last nuxt version 

### ISSUE THREAD

**Issue by EvilaMany** [tailwindlabs/headlessui#2874]
Impossible to use Menu component with example from docs in last nuxt version
Reproduction: https://stackblitz.com/edit/github-as55bc-h3vgq3?file=layouts%2Fdefault.vue

**Comment by adamwathan** [comment]
Hey! I tried out the reproduction and it doesn't seem to start up at all, even if I clone it down and run it locally. Can you create a fresh reproduction starting with a working new Nuxt project? Seems like there are a bunch of other issues here getting in the way that aren't related to Headless UI.

**Comment by thecrypticace** [comment]
Hey @EvilaMany, I couldn't get your reproduction working either but I copied your code into a fresh Nuxt app to test and noticed a some issues:

1. `<Menu>` needs `as="div"` **or** a wrapping `<div>` on the inside of `<Menu>` to support a class attribute. This is because it renders a `<template>` by default which doesn't accept props.
2. You're trying to use multiple links inside a single `<MenuItem>` — this isn't supported. Each link should be its own menu item.
3. Because of the above I added a wrapper div with the `grid` classes around the menu items.

Here's an updated example where I addressed these:

```vue
<template>
  <div>
    <Menu class="relative">
      <div>
        <MenuButton>
          <div>BTN</div>
        </MenuButton>
  
        <MenuItems class="absolute z-10">
          <div class="grid grid-cols-2">
            <MenuItem>
              <NuxtLink to="/firstpage" style="margin-right: 10px">This is a NuxtLink</NuxtLink>
            </MenuItem>
            <MenuItem>
              <a href="/secondpage" style="margin-right: 10px">This is classic {{ '<a>' }}</a>
            </MenuItem>
          </div>
        </MenuItems>
      </div>
    </Menu>
  </div>
</template>

<script setup>
  import { Menu, MenuItem, MenuButton, MenuItems } from '@headlessui/vue'
</script>
```

Hope that helps! ✨
