### ISSUE TITLE
Close Dialog via clicking outside the dialog will fail on test

### ISSUE THREAD

**Issue by jilykate** [tailwindlabs/headlessui#2879]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

@headlessui/react : v1.7.17
react: v18.2.0

**What browser are you using?**
Browsers are fine. Only fail on jest tests

**Reproduction URL**

https://github.com/jilykate/headlessui-test-failure
then run 
````
npm install
npm run test
````
You will see the failing tests

**Describe your issue**

We have a jest test to test close Dialog by clicking the outside of the dialog. However, this test is always fail because cannot trigger the onClose callback. In the meanwhile, when test manually in any browser, it works.

By checking the source code of headlessui/react package "useOutsideClick" hook (https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/hooks/use-outside-click.ts) I found the following line for tests:

![image](https://github.com/tailwindlabs/headlessui/assets/3614910/e647bcad-115d-40dd-9507-3878ea05a82f)

However, this only works for tests inside the package, it won't work in our project as "process.env.NODE_ENV" will be compiled to a static string during build.

I would like to suggest this change for users need to have tests on this function
https://github.com/tailwindlabs/headlessui/pull/2878

**Comment by thecrypticace** [comment]
Hey, so while that check does exist it's _for our tests only_ and we're keen on actually reworking things so we can remove the need for that code eventually. We're on an older version of JSDOM iirc that doesn't polyfill `requestAnimationFrame`. Additionally, your proposed change in #2878 would only work for users using Jest and not other testing frameworks.

It looks like the main problem in your reproduction is that `requestAnimationFrame` doesn't fire at the right time in JSDOM compared to event handlers. It happens to work sometimes and doesn't in others. For example, if you focus just the 2nd block of tests they all pass. And if you focus just the first block of tests they all pass. But when run together the 2nd test fails.

An ideal solution would use fake timers in Jest but I can't get a solution to work using them as things are still fired in the wrong order.

One solution I got working is similar to something we use in some of our own tests: overwriting `requestAnimationFrame` to call it's callback immediately using something like this:
```ts
beforeEach(() => {
  // @ts-ignore
  jest.spyOn(window, 'requestAnimationFrame').mockImplementation(cb => cb());
});

afterEach(() => {
  // @ts-ignore
  window.requestAnimationFrame.mockRestore();
});
```

I think it'd be preferable to use something like Playwright for these kinds of tests (we've looked into it ourselves as well) because JSDOM doesn't (nor can it) get everything right. But, in lieu of that, I think the mock of `requestAnimationFrame` is the best solution for now.
