### ISSUE TITLE
PopoverButton not closing popover when using custom component

### ISSUE THREAD

**Issue by simon-tma** [tailwindlabs/headlessui#2885]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.16

**What browser are you using?**

Reproduced in Firefox and Safari. Have not tested in a Blink browser.

**Reproduction URL**

https://play.vuejs.org/#__DEV__eNp9U01PwzAM/StRLlxGI4QE0igTH+IAB5iAYy6l87ZuaRLFzpg07b+Tj677EHCp8p6f7WfL3fB7a4uVBz7kJdauscQQyNuR1E1rjSO2YWNjzQrcYPd48ERG93BcaVBsy6bOtOzsbg7VRAGib0Soe3bTF8ppnawQGcbeUVOK3D30DYCgtaoiCIixsuuTwB525YYV3kqegeSj/CjFkSgVPcxNlkfp20szlxruqIBKceCFD3ie5bytbLFAo8PaNjFFdgGUfMgSE7mTXcSY5HMii0MhvLbLWVGbVpzI7i6K6+LiSkwaJLEPFYBt6Cl5rL6VehvcENZGT5vZiZdQ1DYK3JulxuhjT5VS5vslceQ8DHZ8PYd6+Qu/wHX2PXaA4FZhij5GlZsB5fDTxyusw7sPtmbiVTfzH8F3QKN89JhlD16HYd2BLrl9Tqtt9OwTn9YEGndDRaNpG0kveVje4z+j7+1eFpcHW9xfYvwLjm/vKx9QicoQE6NSdMTpZWx/AJYUHns=

**Describe your issue**

When using a custom component for the `PopoverButton` that opens a popover, clicking it while the popover is open does not close the popover.

The behaviour seems to be:
- Outside click listener detects a click and closes the popover
- Button's click event is then triggered and re-opens the popover

**Comment by thecrypticace** [comment]
Hey this is fixed in v1.7.17 of `@headlessui/vue` which was just released.

Here's an updated SFC playground: https://play.vuejs.org/#eNqNU8Fu4jAQ/RXLl17ApkLaSmwWsV31sHvYRdseczHJFFwc27LHFAnx73XskABqq14iv5nneTMvngP9aS3bBaAzWvjKSYvEAwY7L7VsrHFIDmRprNmBG50O9wHR6B4uhQZFjuTZmYbcLDYgagXeB8lj3ZvvfaF8raMxnmGr3XIKntWjbgQIjVUCISJCik4ngQF25WbC/yhpBiWd50PBL0ip6Pnd1PI8fXtqjiXBUyiigp/1Qkc0zzJuhGUv3uho26G9UnYJX9IZSZE2duVFmyvpBtH6GedB2+2aVabhV7TFLbtjt3e8lh75kGLgm6hZ0lFfHoX2KKot30mHQahxZdzHKu+yF1M2YZPxClCwbxO+ClLVXMkVl7qG/aeaAcZdpS9IDuQvKraCx1Ifo+foK6Of5frK8ahgpQL3z6I0+tJ5oZR5/ZNi6AL07VcbqLbvxF/8Pg+xdODB7aKLfQ6FWwPm9MPjX9jHc59sTB1U5/kHyf/gjQptj5l2H3T8pe6Ml7r9nR6Q1Osn/7BH0P40VNtociPxSxq9/PXJ6EO7UzY9c3HYt3bXLzdsldek8Mog4fMi/pVuby7f//ENcg5s8g==
