### ISSUE TITLE
[DOCS]: Combobox docs first example - missing command for installing @heroicons

### ISSUE THREAD

**Issue by LiorAgami** [tailwindlabs/headlessui#2896]
In the **React** [Combobox](https://headlessui.com/react/combobox#installation) docs - When trying to implement the first Combobox example, copying the code and following the installation step - we will get an error related to @heroicons because it isn't mentioned as part of the installation step.

Do you want me to fix it?

**Comment by adamwathan** [comment]
Hey! Since `@heroicons/react` isn't actually needed to use Headless UI we don't include it in the installation instructions. I think I'd rather just use inline SVGs in the examples than add it to the installation instructions and confuse people into thinking it's a peer dependency, but referencing the library makes the code simpler to follow as SVGs can add a lot of noise.

Going to just keep it as is for now but appreciate the feedback and if this becomes a big point of confusion we'll figure out a way to improve it 👍

**Comment by LiorAgami** [comment]
NP, sounds good :)
