### ISSUE TITLE
Watch mode is broken in @headlessui/react latest release

### ISSUE THREAD

**Issue by thetnaingtn** [tailwindlabs/headlessui#2899]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.0.0-alpha.3

**What browser are you using?**

Chrome

**Reproduction URL**
Sorry, I can't provide reproduction url.

**Describe your issue**
The `yarn react playground` command is somehow broken. I try to make some changes in `packages/@headlessui-react/src/components/dialog/dialog.tsx` (for example adding `console.log`) and the changes are not reflect in the browser. I also try to use `yarn workspace playground-react dev` but it doesn't work either.'
The watch mode is working fine until v1.6.5, I can use `yarn react playground` and changes are reflect in the browser.

**Comment by RobinMalfait** [comment]
Hey!

Thanks for the bug report. This recently started happening indeed. This should be fixed now, and we also switched to `npm workspaces` instead of `yarn workspaces`. All the commands should be the same but with `npm run ...` instead of `yarn ...`

The main issue was that for some reason yarn v1 kept installing `@headlessui/react` as an actual dependency from npm instead of pointing to the package in the workspace itself.

Last but not least, we also moved the `packages/playground-*` to `playgrounds/*` instead to have a nice split between playgrounds and packages.
