### ISSUE TITLE
Transition enterFrom classes not working with Menu

### ISSUE THREAD

**Issue by zce** [tailwindlabs/headlessui#2914]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v2.0.0-alpha.4

**What browser are you using?**

Edge

**Reproduction URL**

https://stackblitz.com/edit/stackblitz-starters-a9u657?file=app%2Fmenu-demo.tsx

**Describe your issue**

https://github.com/tailwindlabs/headlessui/assets/6166576/d05ae94f-2766-4b8a-bf30-806c11360013

**Comment by ilkkakuivanen** [comment]
I have similar issue with [Dialog](https://headlessui.com/react/dialog).
- The issue started with [1.7.18](https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-react/CHANGELOG.md#1718---2024-01-08).
- Current fix is to roll back to 1.7.17.
- One noticeable issue seems to be not all steps are correctly iterated. At least the "enterTo" class is not persistent as it should when the dialog is open.
- The issue seems to occur with any use of `<Transition/>`

**Comment by RaenonX** [comment]
> I have similar issue with [Dialog](https://headlessui.com/react/dialog).
> 
> * The issue started with [1.7.18](https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-react/CHANGELOG.md#1718---2024-01-08).
> * Current fix is to roll back to 1.7.17.
> * One noticeable issue seems to be not all steps are correctly iterated. At least the "enterTo" class is not persistent as it should when the dialog is open.
> * The issue seems to occur with any use of `<Transition/>`

I think this bug might be introduced by https://github.com/tailwindlabs/headlessui/pull/2722. Agree that `enterTo` should persist what it has, as making what was `enterTo` to be `entered` will be a different behavior here.

**Comment by sahibjotsaggu** [comment]
@ilkkakuivanen I've created a codesandbox [here](https://codesandbox.io/p/sandbox/headless-ui-dialog-not-working-dqw3cy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls9iejd900063b6lortbhzlj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls9iejd900023b6ltenlb0yy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls9iejd900033b6lf1my2uvf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls9iejd900053b6lx9j5z1px%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls9iejd900023b6ltenlb0yy%2522%253A%257B%2522id%2522%253A%2522cls9iejd900023b6ltenlb0yy%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls9iejd900053b6lx9j5z1px%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls9iejd900043b6l8qgsq8xo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls9iejd900053b6lx9j5z1px%2522%252C%2522activeTabId%2522%253A%2522cls9iejd900043b6l8qgsq8xo%2522%257D%252C%2522cls9iejd900033b6lf1my2uvf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls9iejd900033b6lf1my2uvf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with version 1.7.17 but the transition still isn't working. Any ideas?

**Comment by areriklq** [comment]
I have pinpointed a bug relating to `enterTo` to being introduced in 1.7.18, I upgraded version-by-version to confirm this.

The following transitions worked in 1.7.17 but in 1.7.18 the classes for `enterTo`  are never appended to the element.
![image](https://github.com/tailwindlabs/headlessui/assets/156663890/11442ccb-24a2-4649-8f7f-bbb8cf91fd3b)

As mentioned before this is most likely due to #2722 . Could @RobinMalfait confirm?

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3074, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.

**Comment by RaenonX** [comment]
Hi @RobinMalfait 
May I know which version include this fix?
Despite the timeline (your comment 2 weeks ago vs v1.7.19 release 5 days ago), this fix seems only included `insiders` version, not the formal release version.

See https://github.com/RaenonX/test-transition/commits/main/ where after https://github.com/RaenonX/test-transition/commit/a915a75be566c2c9bdfac02970c772cc14451489, the issue still persists, and only gets fixed by https://github.com/RaenonX/test-transition/commit/45f73ad377f546358a2a03aa83b96d8a05ce8d8d.
