### ISSUE TITLE
Combobox selects first item on blur

### ISSUE THREAD

**Issue by NilsEvers** [tailwindlabs/headlessui#2932]
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Chrome

**Reproduction URL**

[Basic example on stackblitz](https://stackblitz.com/edit/vitejs-vite-bwfoj5?file=src%2FApp.vue)

**Describe your issue**
When a `Combobox` that does not already have a value is closed by clicking outside the element, the first value is selected.

Steps to reproduce:
1.  No value is yet selected in the Combobox (`v-model = undefined`)
2. Open the Combobox
3. Click outside the element to cancel the selection
4. The first item will be selected now

If the selection is cancelled by pressing the esc key the issue does not occur.

**Comment by reinink** [comment]
Hey thanks for reporting this! I've been able to reproduce this issue. It only happens (at least for me) when I open the combobox and immediately move the mouse away and click, however if I open the combobox and first hover over items in the dropdown and then move away and click, it doesn't happen. We'll look into it 👍

**Comment by omernoach** [comment]
same happens on @headlessui/react: 1.7.18

**Comment by eatmoarrice** [comment]
When you use the arrow keys to move up and down and then click outside, whichever option currently active will be selected.

**Comment by omernoach** [comment]
yes

**Comment by omernoach** [comment]
@reinink do you work on solution for react lib too?

**Comment by reinink** [comment]
Hey folks, thanks for your patience on this one. I've had a closer look at this today, and realizing now that this is actually expected behavior. By default the `Combobox` component in Headless UI requires a value. You can allow empty values using the `nullable` prop:

```js
<Combobox value={selectedPerson} onChange={setSelectedPerson} nullable>
```

Here's an updated reproduction that uses this prop: https://stackblitz.com/edit/vitejs-vite-ncgpkn?file=src%2FApp.vue

You can read more about the `nullable` prop in the Headless UI documentation here: https://headlessui.com/react/combobox#allowing-empty-values

The combobox behaves oddly when you pass it a `null` value but don't have the `nullable` prop set — which is what you were experiencing.

Hope that helps! 🤙

**Comment by omernoach** [comment]
First of all thanks for the response, in the demo you sent the problem still exists. try to move up and down with the arrows and then click outside, it will select the focused one...
I've changed to nullable in my project and still got the same problem :/

**Comment by NilsEvers** [comment]
I can confirm that the issue is still present after setting the `nullable` prop.
Here is another [demo on Stackblitz](https://stackblitz.com/edit/vitejs-vite-obchsf?file=src%2FApp.vue).
The behaviour is exactly the same. If you open the combobox and then click outside the element without first hovering over a combobox option, the first option will be selected.

**Comment by NilsEvers** [comment]
After additional testing I've noticed that you have to set the initial value of the ref to `null`. `undefined does not work.

I think this behaviour is really awkward and counterintuitive.
First of all, why do you have to set `nullable` in the first place? There is no way to clear the combobox anyway, so why is it the concern of the component. If you don't want to allow empty values, then don't bind the component to an empty value. I really don't see any benefit at all for this prop.
And not allowing undefined is another quirk that makes using this component way more involved than needed.

**Comment by reinink** [comment]
Hey folks! Just wanted to let you know that the upcoming v2 release is going to make the combobox "nullable by default". You can read more about this change in #3064.

Thanks for sharing all this feedback! 👍

**Comment by DanWebb** [comment]
@reinink I've tested this in [the react v2 alpha](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0-alpha.4) and the issue still exists with or without the nullable prop – if there's an "active" option in `Combobox.Options` it'll be automatically added to the input when clicking anywhere outside the Combobox.

Should this be re-opened?

**Comment by djerraballi** [comment]
So, testing this on v2 shows that it seems to be still broken. Clicking away from the combobox behaves exactly the same as hitting the return key (enter).

What I think is happening is that when combobox displays options, the first option is sort of "hovered" by default. Hovering over that option and then clicking away has the desired behavior of closing the options. Ive tested this by hitting the down arrow and clicking away and noted that the second option in the list is what ends up triggering the onChange on the combobox.

**Comment by DanWebb** [comment]
@reinink Thanks! I've tested on 2.0.3 this morning and it all seems to be fixed 👍 

@djerraballi I did have to move to the new components `ComboboxInput` instead of `Combobox.Input`, `ComboboxOptions` instead of `Combobox.Options` etc. I'm not seeing the `onChange` being called when clicking away from the input like it was before including when an item in the list is active.

**Comment by ali-ayyad-1** [comment]
This is also an issue when a value is already selected.

I have used the same demo used above  [demo on Stack blitz](https://stackblitz.com/edit/vitejs-vite-ezxxbg?file=src/App.vue) 

Instead of 
`let selected = ref(null);`
replace with to select the third item initially
`let selected = ref({ id: 3, name: 'Devon Webb' });`

Expected behaviour: 
Devon Webb is selected

Actual behaviour: 
First item is highlighted in the list and onBlur it will replace it.

**Comment by LadyAiss** [comment]
@NilsEvers I had the same issue and have created a fix PR for it: https://github.com/tailwindlabs/headlessui/pull/3628
this issue was introduced in the version 1.7.17 of @headlessui/vue ([commit](https://github.com/tailwindlabs/headlessui/pull/2712/files#diff-2a99fce8dc890b1d7968934853ae2a5eff4d46a3b7b70d2d4619f23ccb0f4c29))
