### ISSUE TITLE
Switch not submitting form with type="submit"

### ISSUE THREAD

**Issue by danthegoodman1** [tailwindlabs/headlessui#2935]
`"@headlessui/react": "^1.7.18"`

`type="submit"` does not submit a form when clicked

**Comment by danthegoodman1** [comment]
possibly related to https://github.com/tailwindlabs/headlessui/issues/2482

**Comment by danthegoodman1** [comment]
I tried wrapping in a button, and using `as="div"` and it seems to disable the lcick of the parent. Doesn't submit form unless I click in space around  the switch

**Comment by RobinMalfait** [comment]
Hey!

This sort of mimics the native `<input type="checkbox" />` where clicking the checkbox _only_ toggles its state and doesn't submit form.

A native checkbox doesn't submit its form on click, it only does that if you press enter while focused on the checkbox and if you have a submit button.

I think it would be confusing if you _and_ toggle its state _and_ submit the form, but I'm interested in your use case on why you want this behaviour.

Since I believe this is not an actual bug, I'm going to close this issue for now.

Hope this helps!

**Comment by danthegoodman1** [comment]
@RobinMalfait I think there's a decent use case for saving on change for something like a long list when you want to just quickly tap through and change stuff. I guess I could just listen of a form `onChange` and submit it.
