### ISSUE TITLE
dosen't work in react newest version 

### ISSUE THREAD

**Issue by valueinvestment** [tailwindlabs/headlessui#2943]
I just make create-react-app,
```
npx create-react-app test
```

install  tailwind through the site
https://tailwindcss.com/docs/guides/create-react-app

install headlessui 
https://headlessui.com/react/combobox

but Headlessui component dosen't work 
that looks like do not adjust css.

here is my package.json

** node -v : v20.10.0 **

```json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@headlessui/react": "^1.7.18",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "tailwindcss": "^3.4.1"
  }
}
```

here is the result of Combobox
![image](https://github.com/tailwindlabs/headlessui/assets/78516146/2aac0a2d-4b99-4cf5-a773-767c7a78ee29)

this is the project
[test.zip](https://github.com/tailwindlabs/headlessui/files/14033060/test.zip)

**and plz check headlessui is work with react + vite + tailwindcss**

**Comment by RobinMalfait** [comment]
Hey!

The issue is not that Headless UI is not working, but that Tailwind CSS isn't configured correctly. I would not recommend to use Create React App, instead use Vite: https://tailwindcss.com/docs/guides/vite

Once a project using Vite is setup, adding Headless UI should work as expected. However, keep in mind that Headless UI is headless, meaning that it doesn't come with any styles, you have to add the styles yourself.

Hope this helps!
