### ISSUE TITLE
Insiders version of Tabs is breaking page overflow on mobile

### ISSUE THREAD

**Issue by ovidiuwin** [tailwindlabs/headlessui#3085]
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

Insiders `^0.0.0-insiders.c8037fc`

**What browser are you using?**

Chrome, Safari etc.

**Reproduction URL**

https://codesandbox.io/p/devbox/headless-insiders-overflow-q32rhd

**Describe your issue**

When using the insiders version of headlessui, the `<Tabs />` component is breaking the page overflow on mobile. I have a use case where I have multiple tabs so I added `overflow: auto` on the `<Tab.List />`. After scrolling inside the Tabs, users are unable to scroll the page unless they click one of the Tab items.

Steps:
- Go to the repro sandbox provided.
- Inspect element and choose any mobile device or open the link from a real mobile device
- Scroll horizontally insde the `<Tabs />` component
- Try to scroll the page
- Page is not scrollable anymore unless clicking one of the Tab items

**Comment by RobinMalfait** [comment]
Hey!

This was a fun one to track down, but there are multiple issues happening here.

1. You have both a `pnpm-lock.yaml` and a `yarn.lock` file and they don't match the `package.json` version. Not a super big deal, but wanted to make you aware of this.
2. The `^` does not work properly when using insiders builds. This is because the hash used is not ordered so it could be that you get wrong results here. If you use the insiders version, you always need to lock the version explicitly.
You can see this behaviour if you inspect the `yarn.lock` file:
```
"@headlessui/react@^0.0.0-insiders.c8037fc":
  version "0.0.0-next.f3df979"
```

The actual version you are using is `0.0.0-next.f3df979`.

To solve your issue, make sure that you are _not_ using the `^` and using the exact version of the insiders build. If you want to update you can use `yarn add @headlessui/react@insiders` (in this case, it will always point to the latest correct `insiders` version).

Hope this helps!
