### ISSUE TITLE
Windows computer unable to start the project 

### ISSUE THREAD

**Issue by YIngChenIt** [tailwindlabs/headlessui#3136]
**What package within Headless UI are you using?**
 @headlessui/vue

**What version of that package are you using?**

 v0.3.1

**What browser are you using?**

window

**Reproduction URL**

![image](https://github.com/tailwindlabs/headlessui/assets/53081460/e70ab1d2-935a-4dce-9abb-2333a43173b4)

**Describe your issue**

I encountered difficulties when starting the project on my Windows computer. I can offer help to improve it.

**Comment by RobinMalfait** [comment]
Hey!

The project currently assumes unix based systems because we all use macOS, this way we don't have to maintain setups that we don't use ourselves. If you want to run it locally in a Windows environment, I would recommend you to use WSL which should just work.

Right now we have no intention to make the local development possible on Windows.

So yeah, I would say use WSL, maybe `git bash` terminal works as well because I believe they use unix style paths.

Hope this helps!
