### ISSUE TITLE
Extra empty div on adding Transition component

### ISSUE THREAD

**Issue by BrainBuzzer** [tailwindlabs/headlessui#33]
Hey guys, great work on the library. I've been using TailwindUI in some of my projects. Recently, I started migrating base Transition components to the ones provided by headlessui.

I use React Portals to create the notifications. I started noticing issues when I added transition wrapper around the notification component. Here is a screenshot of how the notification looks after I've added the transition wrapper provided by headlessui.
![image](https://user-images.githubusercontent.com/10351046/95010432-ea1a4680-0646-11eb-9617-d45039464b88.png)

I was able to pinpoint this issue to an empty div being added on adding transition wrapper. This issue does not occur on using the previous transition wrapper.
![image](https://user-images.githubusercontent.com/10351046/95010469-36fe1d00-0647-11eb-88a3-72efb05a9b48.png)

**Comment by adamwathan** [comment]
Check the documentation, they explain how to avoid the extra element when it’s an issue:

![426B3AD4-782B-4821-B8C8-0393D95CCFF7](https://user-images.githubusercontent.com/4323180/95013600-56795380-060f-11eb-8684-2ee15ba26deb.png)

We had to change this in this new version to be compatible with strict mode in React, due to old implementation requiring some deprecated APIs.
