### ISSUE TITLE
Focus not returned to triggering button when closing modal

### ISSUE THREAD

**Issue by eroltibern** [tailwindlabs/headlessui#3320]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.17 - v.2.x.x

**What browser are you using?**

Chrome

**Reproduction URL**

[Sandbox](https://codesandbox.io/p/devbox/happy-glitter-x9l3jt?workspaceId=3ed7720e-5436-4924-b7c1-668abe103ce5)

**Describe your issue**

When opening a Dialog by clicking on a button with its content wrapped in a `span`, focus is not properly restored to the triggering button after the dialog closes. Focus is instead returned to `body`. 

```tsx
<button onClick={open}>
  <span>Click me</span>
</button>
``` 

I believe this is due to the `span` element being added as the latest focused element in the active element history, and when trying to focus the `span` the browser falls back to focusing `body` instead. 

A solution could be to find the first focusable element in the history array and trying to focus that? Something like this: 

```typescript
return useEvent(() => {
    return (
      localHistory.current.find(
        (x) => x != null && x.isConnected && x.matches(focusableSelector)
      ) ?? null
    )
  })
``` 

Here: https://github.com/tailwindlabs/headlessui/blob/6ac6930116c47cbd72402c33bfe327698c8e2780/packages/@headlessui-react/src/components/focus-trap/focus-trap.tsx#L271

What do you think? I can open a PR if I'm not missing something important here.

**Comment by RobinMalfait** [comment]
Hey thanks for the bug report, your idea is a good idea, but instead of checking if the element is the focusable element when figuring out the element to restore, I resolved the closest focusable element when recording the click instead.

This should be fixed by #3365, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders`.
