### ISSUE TITLE
transition context conflict

### ISSUE THREAD

**Issue by haola1210** [tailwindlabs/headlessui#3322]
**@headlessui/react**

**v2.1.0**

**Chrome**

**Describe your issue**

I created a component called MyDrawer with the `Transition` component. I render children inside the `TransitionChild`
Inside MyDrawer, I use a `Dialog` component and add `transition` props to the `DialogPanel` component.
When I close the `Dialog` (click on the backdrop) -> the  dom content of the `TransitionChild` is gone

it's ok when I remove the `transition` props from the `DialogPanel` component. but then my `Dialog` wont have animation :(

**Comment by RobinMalfait** [comment]
Hey!

Can you share a minimal reproduction?

**Comment by RobinMalfait** [comment]
I figured out a reproduction that seems to reproduce this. So this should be fixed by #3331, and will be available in the next release. If this does not fix your issue after testing, please open a new issue with a minimal reproduction GitHub repo attached. 

You can already try it using:
- `npm install @headlessui/react@insiders`.
