### ISSUE TITLE
Combobox: When ComboboxInput is clicked combobox gets closed

### ISSUE THREAD

**Issue by prtmwrkr** [tailwindlabs/headlessui#3383]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.2

**What browser are you using?**

All

**Reproduction URL**

[Working example v1.7.19](https://codesandbox.io/p/sandbox/headlessui-combobox-ngvq3x?file=%2Fsrc%2FDemo.tsx%3A98%2C13)

[Failing scenario v2.1.2](https://codesandbox.io/p/sandbox/headlessui-combobox-2-gw8c27?file=%2Fsrc%2Findex.tsx)

**Describe your issue**

It's a simple combobox: you click the button, you can click one color from the list to select it; you can click the input box to focus it and filter the list... Here's everything is working fine. The demo is using version `@headlessui/react@1.7.19`.

The only difference in the two sandbox is the version of @headlessui/react; so this seems a regression in the library. Thoughts?

Thank you

**Comment by thecrypticace** [comment]
Hi! This is because you're nesting the combobox input inside the combobox button and the click on the input is bubbling to the button and closing the combobox. Placing an input inside a button is not supported and I am quite surprised that it worked at all in v1.7.

I'd advise against conditionally rendering the input of a combobox as the input is the element marked with `role="combobox"` — hiding it without some kind of replacement will make things less accessible.

I'm not sure what kind of UI you're trying to achieve but it's likely that you should render the entire combobox conditionally instead of just the input / button.

**Comment by prtmwrkr** [comment]
@thecrypticace Thank you - that helped.
