### ISSUE TITLE
TypeError: node.getAnimations is not a function

### ISSUE THREAD

**Issue by roomman** [tailwindlabs/headlessui#3470]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

For example: v2.1.6

**What browser are you using?**

N/A

**Describe your issue**

I am seeing the following errors when running Jest tests using the latest version of HeadlessUI:

```
 TypeError: node.getAnimations is not a function
      
            at waitForTransition (../../node_modules/@headlessui/react/dist/headlessui.dev.cjs:3752:26)
            at ../../node_modules/@headlessui/react/dist/headlessui.dev.cjs:3739:13
```
It looks like the changes made on [L236]( https://github.com/tailwindlabs/headlessui/blob/03d80f496d79804a433ec980570429738cf8a31e/packages/%40headlessui-react/src/hooks/use-transition.ts#L236) in https://github.com/tailwindlabs/headlessui/pull/3452 introduced a bug.

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #3473, and will be available is available in the latest release. 

The issue is that we rely on `Element.prototype.getAnimations(…)` which is a browser feature that's available in browsers since 2020. Unfortunately, jsdom is not up to date and therefore it crashes.

To solve this, we ship with a very minimal polyfill, just enough to run the tests. However, we do show a warning now that guides you to using a polyfill to silence the warnings. 

I would also recommend to:
1. Try and move to real browser tests (e.g.: Playwright)
2. Use a proper polyfill like `jsdom-testing-mocks`

You can already try it using:
- `npm install @headlessui/react@latest`.
