### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event.

### ISSUE THREAD

**Issue by vladavoX** [tailwindlabs/headlessui#3531]
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

`v2.1.2`

**What browser are you using?**

`Chrome`

**Reproduction URL**

You can test this warning on your website
https://headlessui.com/react/menu
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0f47188a-fb77-4838-9cf1-4cc8984d891b">

**Describe your issue**

Clicking on dropdown button `Options`, causes this warning to pop up

**Comment by RobinMalfait** [comment]
Hey!

Unfortunately this is coming from a dependency (Floating UI), that we use to make positioning easier. 

That said, looking at the code, the warning suggests to add `passive: true`. This means that we promise to never call `e.preventDefault()` but the code _does_ call `e.preventDefault()`.

This is part of the `inner` middleware (https://floating-ui.com/docs/inner) that allows us to improve the UX to mimic macOS-style select menu and grow the select on scroll.

So while I see that this could be annoying while developing, since it's a warning and you don't run into actual (UX) issues, I don't think there is anything we can or even should do in this scenario at this point.

Going to close this for now and see if we can improve this in the future. 

Hope this helps!
