### ISSUE TITLE
Dialog autoFocus does not work

### ISSUE THREAD

**Issue by 99diagha** [tailwindlabs/headlessui#390]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headlessui-dialog-7qm6p?file=/pages/index.js

### Description

If you look at the repro, you'll see that upon the opening of the Dialog/Modal the focus is on the button. Not the input where `autoFocus` is used. Either I am missing something or this doesn't work properly. Same thing with `initialFocus`.

**Comment by hugotiger** [comment]
Hey!

I took a look at the problem and it seems to be because of the way React polyfills the autoFocus-behaviour. I don't know if this can be fixed or not seeing as it might have to do with React's behaviour.

Although from what I can tell it works using `initialFocus`. 
I created a sandbox for the solution here: https://codesandbox.io/s/headlessui-dialog-forked-pu2eb?file=/pages/index.js

Best regards,
Hugo

**Comment by 99diagha** [comment]
@hugotiger Stort tack Hugo! It seems that the problem was on my end regarding `initialFocus`. I'll leave this open even though it seems that React is causing it.

**Comment by nikhilkutinha** [comment]
This seems to be the case in the Vue package as well. The first element in the dialog ends up getting focused even when the initialFocus or autofocus is set.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As @hugotiger mentioned in https://github.com/tailwindlabs/headlessui/issues/390#issuecomment-821874574, `autoFocus` in React has some quirks. React will polyfill it and call `.focus()` on initial mount of the component. However once you use a Transition component there are multiple renders. This results in the incorrect behaviour.

That said, React also doesn't put the `autofocus` prop on the actual DOM node as an attribute. This means that we can't crawl the DOM once we want to "autoFocus".

Because of this we stopped documenting the `autoFocus` approach, and recommend you to use the `initialFocus` ref as described in here: https://headlessui.dev/react/dialog#managing-focus-within-your-dialog.

Here is a CodeSandbox example with the updated code: https://ffs4b.sse.codesandbox.io
@nikhilkutinha here is the equivalent for Vue: https://v6uib.csb.app
