### ISSUE TITLE
Headlessui on components.studio

### ISSUE THREAD

**Issue by georges-gomes** [tailwindlabs/headlessui#4]
Hi guys,

I'm one of the makers of https://components.studio
I feel like our project would be a perfect fit for creating the showcases for the components.

I quickly ported the drop-down demos to it:

React -> https://components.studio/edit/collection/6d5uIF7OtJs0hiNTEj3T/aiJBj9ughZLbkcHBGoar
Vue3 -> https://components.studio/edit/collection/6d5uIF7OtJs0hiNTEj3T/EUR79YhD81LGflajWtlH

You can also view them as a collection (betteron desktop for now): 
https://components.studio/edit/collection/6d5uIF7OtJs0hiNTEj3T/aiJBj9ughZLbkcHBGoar

I can create a `tailwindlabs` or `headlessui` organisation and you can collaborate around theses demos.
They are all embeddable and relatively lightweight.

We are tailwindcss users, happy to help and improve the platform for you guys.

I hope you like it ♥️
Looking forward chatting with you guys 👍

---

Side notes, we ported 2 `tailwind-ui` a while back.
https://components.studio/user/georges-gomes?collection=tailwind-ui

**Comment by adamwathan** [comment]
Hey thanks for sharing! I looked briefly but had a hard time really understanding what the product is, maybe because I've never used Storybook before? Right now I don't think we have the bandwidth to research any new tools for our demos just because CodeSandbox is totally fine for our needs currently, but I'll definitely follow along with what you're doing and with any luck one day it'll be obvious to me that we should change our approach :)

Thanks for the recommendation and good luck with the project!

**Comment by georges-gomes** [comment]
Hi @adamwathan,
If it's not obvious then I failed :)
If you ever feel like it, hit me up on twitter `@georges_gomes` 
and I can make a quick visio 15min max so you don't waist your time.

Good luck with ALL your projects as well!
