### ISSUE TITLE
[Bug]: Vue Listbox Popup do not close when wrapped with a label

### ISSUE THREAD

**Issue by mseele** [tailwindlabs/headlessui#411]
Wrapping the vue listbox like this
```
<label class="block">
    <span class="font-medium">{{ label }}</span>
    <Listbox>...</Listbox>
</label>
```
prevents the Popup (ListboxOptions) from beeing closed when a ListboxOption is selected by the mouse.

Please see my demo-repo for reproduction: https://github.com/mseele/headless-ui-select-issue

**Comment by mseele** [comment]
**Package** @headlessui/vue
**Version** 1.0.0
**Browser** Chrome
**Repository** https://github.com/mseele/headless-ui-select-issue

**Comment by vassbence** [comment]
Same for React.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is expected behaviour, but you should not wrap your Listbox with a label. When you wrap a button or an input with a label, and click the label than the `onClick` of the `button` will be executed. In this case we select an item, the listbox closes, but you also clicked the label, which triggers the `onClick` of the Listbox and re-opens it.

I would recommend you to use our `ListboxLabel` component instead: https://headlessui.dev/vue/listbox#using-a-custom-label

If you use our `ListboxLabel` component then the result is similar to the native version (https://jsfiddle.net/edzu68rq/2/). When clicking the label, it will focus the Listbox, but not open it.
