### ISSUE TITLE
[Bug]: `selected` slot prop doesn't work in `ListboxOption`

### ISSUE THREAD

**Issue by sto3psl** [tailwindlabs/headlessui#434]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.0.0

### What browser are you using?

Firefox (doesn't matter though)

### Reproduction repository

https://codesandbox.io/s/epic-austin-py45z?file=/src/components/Select.vue

### Describe your issue

When building a custom select component based on `Listbox`, the `selected` slot prop of `ListboxOption` always returns `false`. My guess is, that the comparison of values is comparing the selected `value` and a Proxy of the `value`.

In my reproduction you can see that `selected` always equals `false` but when I do the check in my code `markRaw(modelValue) === option` returns `true` (`option` is the `ListboxOption` value). 

When I'm using `Listbox` directly and don't pass props through my wrapper `Select` component, it works fine. I'm not sure if this is really a bug in Headless UI or if I'm misunderstanding some Vue 3 functionality and how values get converted into Proxies.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We are using the `toRaw` behind the scenes. The issue is that you used `:value` instead of `:modelValue`. Here is a codesandbox with the fix: https://codesandbox.io/s/hidden-night-z49o8?file=/src/components/Select.vue

The diff:

```diff
-  :value="modelValue"
+  :modelValue="modelValue"
   @update:model-value="$emit('update:modelValue', $event)"
```

This is a breaking change from Vue 2 where it used to be called `:value`, more info from the Vue docs: 
- Vue 2: https://v3.vuejs.org/guide/migration/v-model.html#_2-x-syntax
- Vue 3: https://v3.vuejs.org/guide/migration/v-model.html#_3-x-syntax

**Comment by sto3psl** [comment]
Oh wow, I could have thought of that 🤦‍♂️. Thank you so much for fixing my problem 😅!

**Comment by zynth17** [comment]
hello, i just gone through this bug with the newest version of headlessui/vue. the selected slot props is always false.
