### ISSUE TITLE
[Bug]: id contains undefined on initial render

### ISSUE THREAD

**Issue by LeanderG** [tailwindlabs/headlessui#444]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.0.0

### What browser are you using?

Firefox

### Reproduction repository

https://headlessui.dev/examples/react-radio-group-hero

### Describe your issue

On initial render, the ids of the radio group are `headlessui-radiogroup-option-undefined`. I also tested the menu component and it has the same issue.
Could this be a regression of https://github.com/tailwindlabs/headlessui/issues/110?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `undefined` value should only happen on the server or on the very first render but it should also "fix" itself pretty quickly.
The id with an `undefined` that you are seeing, is that being applied all the time or just very temporarily?

**Comment by LeanderG** [comment]
Hey, thanks for looking into this.
The undefined only shows up on the server rendered html. After hydration, the ids are all fixed. Honestly, I don't know if this is even a big issue. Does the server rendered html have to be accessible?

**Comment by RobinMalfait** [comment]
I think the answer here is yes and no. If you don't enable JavaScript, then there will be elements with possibly the same ID and that will make the components inaccessible. That said, if you disable JavaScript then you can't use any of these components anyway so it might not be a big deal.

Maybe we can improve the way we generate id's, but it is not that easy:
- When you use a global counter, on the server not all components will be rendered so this will result in certain mismatches when hydrating.
- When you use `uuid`s, then it will always result in mismatches when hydrating.

Something that we could explore is to use a scoped counter. For example we are doing something like this currently:

```js
let id = `headlessui-menu-button-${useId()}`
```

But if we move the "prefix" in the hook:

```js
let id = useId('headlessui-menu-button')
```

Then maybe we can make it more deterministic without `undefined` id's and without hydration mismatches.
I will have to play with this to make sure that we cover all scenario's with this.

**Comment by valerie-makes** [comment]
I encountered this issue today - it results in invalid HTML when multiple popovers are used on a single page, since there are multiple elements with the same ID.

> When you use a global counter, on the server not all components will be rendered so this will result in certain mismatches when hydrating.

This would not result in any mismatches, since the first-pass render is identical between server and client.

I will have a look at the source code and see if I can write a PR to fix this :)

**Comment by valerie-makes** [comment]
Ah, I see from the [Reach UI `useId` hook](https://github.com/reach/reach-ui/blob/develop/packages/auto-id/src/index.tsx), which is also used by Headless UI, that rendering order can be nondeterministic when using React concurrent mode, so my previous assumption is wrong. They've heavily documented why they believe this approach is the best compromise.

> That said, if you disable JavaScript then you can't use any of these components anyway so it might not be a big deal.

I think I agree with this having now understood the logic behind the `useId` hook - it results in "invalid" HTML, but it improves usability in practice since JavaScript is required for these components anyway.

**Comment by RobinMalfait** [comment]
Hey all!

Doing a big GitHub cleanup. Our conversation is spread across multiple months (sorry about that!). I think that it is a good trade-off for now and we probably eventually want to fix this, but instead of fixing this ourselves, I think it would nice to use the new `useId` that React is providing.

Once we are working (and relying) on React 18 (improved) support, this should hopefully fix itself.
