### ISSUE TITLE
[Bug]: Dialog missing matching `<div>`

### ISSUE THREAD

**Issue by davidluhr** [tailwindlabs/headlessui#450]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.1.0

### What browser are you using?

Any

### Reproduction repository

https://github.com/davidluhr/headless-ui-nextjs-dialog-bug

### Describe your issue

Using `<Dialog>` in a NextJS app results in the following error: `Expected server HTML to contain a matching <div> in <div>.`

This can be recreated with the [example Dialog code](https://headlessui.dev/react/dialog) and is [also occurring with Modals in Tailwind UI](https://github.com/tailwindlabs/tailwindui-issues/issues/577).

**Comment by kieranm** [comment]
Also having this issue. Not sure if this is helpful but I've had the same issue using Portals with all of the other components. In order to get around the issue I used the [Next.js recommended approach](https://github.com/zeit/next.js/tree/canary/examples/with-portals) for making portals play nicely with SSR.

This involves creating a custom Portal component like this...

```
import { useRef, useEffect, useState } from "react"
import { createPortal } from "react-dom"

interface PortalProps {
  selector: string
  children: any
}

export const Portal: React.FC<PortalProps> = ({ children, selector }) => {
  const ref = useRef<Element | null>()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    ref.current = document.querySelector(selector)
    setMounted(true)
  }, [selector])

  return mounted ? createPortal(children, ref.current!) : null
}
```

However, with modals, portals are managed internally with Headless UI so I don't think I can apply this fix.

**Comment by arpitjacob** [comment]
Having this same error in a project I am working on. How do I resolve this?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.

**Comment by davidluhr** [comment]
@RobinMalfait Thanks so much! You're the best.
