### ISSUE TITLE
[Bug]: Vue scoped styles are not applied

### ISSUE THREAD

**Issue by livthomas** [tailwindlabs/headlessui#518]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0

### What browser are you using?

Brave

### Reproduction repository

https://github.com/livthomas/headlessui-bugs

### Describe your issue

Some components from this library cannot be properly styled when using scoped styles in a Vue application. This problem does not affect all components and styles are applied properly to a few simple ones (such as `DialogOverlay`).

I try to use Headless UI to create components in the UI library I'm building. But I don't want to define global class names since this library will be used in multiple applications and I want to avoid any potential clashes in class names.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This seems like a very strange bug. I don't even think it is a Headless UI bug 🤔 
When I inspect the actual DOM, I can see the class being applied correctly:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/1834413/118260610-d1162580-b4b2-11eb-9c4a-2805d7b11d52.png">
But the actual class definition is not available for some reason.

I'm going to investigate this a bit more, because I have no idea what is going on here..

**Comment by livthomas** [comment]
@RobinMalfait Correct me if I am wrong but this could be caused by [inheritAttrs](https://v3.vuejs.org/api/options-misc.html#inheritattrs) being set to `false` and the fact that scoped CSS is only applied to [root elements of child components](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements). Because I can see that [Dialog](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/dialog/dialog.ts#L67) component which is affected by this issue sets `inheritAttrs` to `false` while [DialogOverlay](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/dialog/dialog.ts#L281) does not set it.

**Comment by RobinMalfait** [comment]
I looked more into this, and we have a chicken and egg problem at the moment:

- We **need** the `inheritAttrs: false`, because we return a set of non-dom element components, but Vue can only forward the attributes to the "root" that is returned. It also logs a warning that it can't forward those attributes. To fix this we use the `inheritAttrs: false` and manually passthrough the attributes to the correct element.
- When you use scoped styles, certain data attributes are put on the element(s). This data attribute in combination of the styles make them scoped styles. However, the data attributes are not available in the `attrs` we passthrough therefore your scoped styles won't work. In this case we don't want the `inheritAttrs: false`.

Going to close this for now.
