### ISSUE TITLE
[Bug]: Dialog component adds white space due to padding

### ISSUE THREAD

**Issue by Ghoul2077** [tailwindlabs/headlessui#533]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.2.0

### What browser are you using?

Firefox, Chrome

### Reproduction repository

https://codesandbox.io/s/headlessui-dialog-right-padding-bug-forked-t6rvi

### Describe your issue

Headlessui adds padding-right to compensate for "hiding" the scrollbar on dialog component which leaves white space to the right on pages with background other than white , this might not be adequate from UI point of view.

![image](https://user-images.githubusercontent.com/42601281/118413041-ec538180-b6ba-11eb-8e49-7efe5f12ef3a.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I think that the linked CodeSandbox is broken. I fixed the incorrect import and also simplified the modal component itself https://codesandbox.io/s/headlessui-dialog-right-padding-bug-forked-541bm?file=/pages/modal.js however, as you can see the `white` gap is already there _before_ the Modal is open. 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1834413/119993184-98ef0680-bfcb-11eb-853d-bf143d313951.png">
If you go to the endpoint directly (https://541bm.sse.codesandbox.io/) then you will notice that it works correctly. Once you open the Dialog it still works correctly.

Another thing that I want to mention is that it is a good idea to put your page background color on the actual `html` or `body`. This will also make sure that there are no white gaps when you are scrolling up/down on Mac or on pages that implement the "rubber band" effect.

The padding-right is necessary otherwise the whole content will jump when the model opens/closes. If we remove the "scroll lock" then you will be able to interact (scroll) with the content behind the Dialog, and that's not good from an accessibility perspective.

Going to close this for now, if this still occurs please open a new issue with a working example that showcases the issue.
