### ISSUE TITLE
Component Name Prefix

### ISSUE THREAD

**Issue by timpulver** [tailwindlabs/headlessui#55]
The [Vue.js 2 docs](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential) recommend not to use single word component names to avoid conflicts with future HTML elements. If e.g. a HTML element `switch` was introduced it would clash with the Headless UI `Switch`.
The [Vue 3 docs](https://v3.vuejs.org/guide/component-registration.html#component-names) are not as clear about this, but it might be a good idea to prefix all components, e.g. `HSwitch` instead of `Switch`.
Other frameworks do this as well:

- `v-alert` used by [Vuetify](https://vuetifyjs.com/en/components/alerts/#usage)
- `el-switch` used by [Element](https://element.eleme.io/#/en-US/component/switch)
- `b-switch` used by [Buefy](https://buefy.org/documentation/switch)

**Comment by iamohd** [comment]
It's possible that you import the component as different name, for example

```
import ListboxButton as VListboxButton from '@headlessui/vue'

components: {
   VListboxButton
}
```

This will prefix the component's name with v-

**Comment by timpulver** [comment]
I am a bit worried that existing code-bases that do not use the import style mention by @iamohd will not build any more once conflicting HTML elements are introduced.

**Comment by adamwathan** [comment]
Hey thanks for bringing this up! Thought about it a lot and as far as I can tell it's not an issue, because you have to register components with Vue manually no matter what, and you always have the chance to give them your own name when doing so.

Inside a SFC:

```vue
<script>
import { Switch } from '@headlessui/vue'

export default {
  components: {
    MySwitch: Switch,
  }
}
```

When registering globally for DOM templates:

```js
import Switch from '@headlessui/vue'

const app = Vue.createApp({})

app.component('my-switch', Switch)
```

Even when using the UMD build right in the browser with no build step:

```js
const app = Vue.createApp({})

app.component('my-switch', headlessui.Switch)
```

So there is never a situation where you aren't able to alias it yourself. I'd rather people work around that in the rare situations it matters (which is none yet, there's no switch element in HTML) than add a prefix to every component, since that just adds more work for 99% of people without any benefit.

Thanks for raising the issue though, was helpful to think it through and make sure there are no real problems 👍🏻
