### ISSUE TITLE
[Bug]: `dark:` modifier doesn't seem to work with `Dialog`s

### ISSUE THREAD

**Issue by leggettc18** [tailwindlabs/headlessui#558]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/leggettc18/devmarks-frontend-web/

### Describe your issue

Pretty self explanatory with the title. Basically I have a Dialog, a div within that where the background color is specified, and a `dark:` version as well. Only the light one seems to get added in. It actually does seem to work if I remove the `bg-white` class while the rest of my site is in dark mode, but then the light version looks weird.

**Comment by leggettc18** [comment]
Correction, if I don't specify a non dark background color it just takes the dark background color from a parent element.

**Comment by leggettc18** [comment]
The Dialog in question in the provided codebase starts around line 12 of src/views/Bookmarks.vue, and the div where the background color is specified starts on line 38 of that file.

**Comment by leggettc18** [comment]
Another update, I have managed to find a workaround by applying the different classes via a `:class=""` attribute that applies the proper bg and text color classes according to the boolean value I store in my state management for whether or not the site is in dark mode. Still a bit puzzled as to why this was necessary. I also needed to do this for the `DialogTitle` component as well.

**Comment by florianfranconi** [comment]
Same issue

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI itself doesn't care about which classes you apply and which you don't. If you are experiencing issues with missing classes than make sure to include all the paths, where components with certain classNames live, to your purge config.

Additionally, I wanted to look at your reproduction repo but I have to sign up / sign in, so can't help you with that one. That said, there is one thing you have to keep in mind with the `Dialog` is that it renders in a portal right in the `<body>` tag. This means that if you are using a `dark` class, that you have to add it to the `html` or `body` tag so that all children can use this information to render the dark/light mode.

If you don't like that approach, then you could look into using context for this. Here is a similar issue with React, but the same logic applies: https://github.com/tailwindlabs/headlessui/issues/280#issuecomment-828376470
