### ISSUE TITLE
[Bug]: TypeError: React.createContext is not a function

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [tailwindlabs/headlessui#564]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.2.0

### What browser are you using?

N/A

### Reproduction repository

https://github.com/rgbrizzlehizzle/ba-sing-se

### Describe your issue

I am experiencing the same issue raised in https://github.com/tailwindlabs/tailwindui-react/issues/5 😞 

I'm a total front-end scrub so apologies if this turns out to be something that is completely my fault lol. 

It also seems possible that this is a problem with Jest, but it seemed to make sense to open it up here first since someone else also had the same issue.

Issue can be replicated by cloning the repo that I linked and running `yarn test`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'm very confused by the reproduction repo. You are not using Headless UI in the linked repo, so can't really help you there. If this problem still occurs please open a new issue with a minimal reproduction repo that showcases the issue.

That said, if you are getting issues like the one you mention, then make sure that you are not using multiple versions of React. I can see in your `package.json` that you are both using `react` and `next`. `next` already comes pre-bundled with React so that's probably your issue here.

**Comment by rgbrizzlehizzle** [comment]
oh I'm sorry I don't have the issue merged, this is the PR https://github.com/rgbrizzlehizzle/ba-sing-se/pull/3 my bad

**Comment by rgbrizzlehizzle** [comment]
I'll check out the next vs react, that sounds promising

**Comment by rgbrizzlehizzle** [comment]
> next already comes pre-bundled with React so that's probably your issue here

hmm this doesn't seem right, I just tried that and got

>  Cannot find module 'react' from '__tests__/components/auth/login.test.tsx'

when i run `yarn test` in the PR I linked

IMO this ticket should not be closed

**Comment by RobinMalfait** [comment]
> next already comes pre-bundled with React so that's probably your issue here
Ah yep, this a mistake on my part it does not come bundled together.

**Comment by venables** [comment]
For those encountering this issue, it is likely due to including `.` in the `moduleDirectories` section of `jest.config.js` like so:

```js
moduleDirectories: ['node_modules', '.'],
```

Either removing the `.` or changing it to `<rootDir>` solved the issue:

```js
moduleDirectories: ['node_modules', '<rootDir>'],
```

A similar issue + solution was reported with [theme-ui](https://github.com/system-ui/theme-ui/issues/1000#issuecomment-656035612).

**Comment by ethanmick** [comment]
@venables I cannot thank you enough, I've been tracking this bug all over the Internet and finally got here.

```
--- a/jest.config.js
+++ b/jest.config.js
@@ -17,6 +17,6 @@ module.exports = {
   },
   globalSetup: '<rootDir>/test/setupEnv.ts',
   // To support baseUrl relative imports from tsconfig.json, add current directory as a module source
-  moduleDirectories: ['node_modules', '.'],
+  moduleDirectories: ['node_modules', '<rootDir>'],
   setupFilesAfterEnv: ['<rootDir>/jest-setup.ts']
 }
```

Changing `.` to `<rootDir>` was the magic to get it working (In my case, `@apollo/client`.

**Comment by sebpowell** [comment]
Worked for me too (in my case, it was linked to `@tiptap/react`)

**Comment by fa8ster** [comment]
You have to add ` 'use client';` if you're using Next13

**Comment by haghighi251** [comment]
Hi, If you are using Next.js 13 you have to add 'use client'; to your component. Please for more information check the link below:
https://beta.nextjs.org/docs/rendering/server-and-client-components

**Comment by yaffalhakim1** [comment]
> Hi, If you are using Next.js 13 you have to add 'use client'; to your component. Please for more information check the link below: https://beta.nextjs.org/docs/rendering/server-and-client-components Otherwise, check if you have installed the latest version of react and react-dom.

i added "use client" and got me new error undefined is not a valid json. do you have any solutions?
