### ISSUE TITLE
[Bug]: calling focus() on listboxRef does not focus the listbox button

### ISSUE THREAD

**Issue by mseele** [tailwindlabs/headlessui#569]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/mseele/headless-ui-select-focus-issue

### Describe your issue

Calling focus() on listboxRef does not focus the listbox button.

How to reproduce:
- Clone the repo and start it
- Click on "Focus Listbox" Button
- Listbox did not get the focus - expected behaviour
- Click on "Focus Listbox Button" Button
- Listbox get the focus - behaviour i expect for the previous action, too

**Comment by ipvalverde** [comment]
I've got the same behaviour using the React version of the library.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Interesting, I see why you would like to do that, but I think it makes a bit more sense to call `focus()` on the `ListboxButton` since that's what you want to focus. By default the `Listbox` doesn't render anything (`template` in Vue, `Fragment` in React) so we can't attach a focus listener anyway, we would have to check the as prop and or the first element that is being rendered and put the focus listener on that element.

I think that for now, I'm going to close this, and if there is more demand for this feature, then we can implement it later.
