### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by scottbedard** [tailwindlabs/headlessui#58]
Hi, first off I love the idea of this project! I'm really looking forward to using it once it's more fleshed out. Also, apologies if this was already covered somewhere, I looked around and did not find it.

I think we could benefit from some contributing guidelines. Just a bit of documentation around things like...

- Proposing new components
- Designing the API around those new components
- Implementing new components
- Quality guidelines

I'd love to help grow the library of components!

**Comment by adamwathan** [comment]
Hey Scott thanks for the kind words! Right now in this early phase I don't think we're quite ready to accept brand new components from the community because we're still figuring out our overall API design philosophy ourselves, and we're iterating pretty rapidly in real-time over pair programming sessions.

Once things are a bit more stable I agree it would be good to open things up more with some guidance around the best ways to contribute 👍🏻 

For now I would recommend just watching the repo closely and trying to get a feel for what we're doing, and don't hesitate to make suggestions or propose ideas if you have them. We don't have the resources to sort of onboard people into the codebase at the moment, but of course contributions from folks who have done the work to understand the codebase deeply on their own are more than welcome.
