### ISSUE TITLE
Listbox.Options within scrollable area is cut

### ISSUE THREAD

**Issue by Mojeer0** [tailwindlabs/headlessui#59]
When placed within a container with `overflow-auto` the Listbox.Options is cut, which is not aesthetic.
Also, when the container is not overflowing yet it can trigger the overflow.

A use case for this is for forms that are put in modals on mobile, where it's not rare to have overflow-auto on it. ([Example](https://ptpimg.me/7a25a7.png
))

[Codesandbox demo](https://codesandbox.io/s/headlessuireact-listbox-example-forked-eoukm?file=/src/App.js)

https://select2.org/ handle this by attaching the equivalent of Listbox.Options as a direct child of the body, and positioning it absolutely.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We know about this issue, and we prefer composition of some portals and popper.js for this instead of doing that work ourselves. 
Please have a look here: https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx#L12-L16 & https://github.com/tailwindlabs/headlessui/blob/develop/packages/%40headlessui-react/pages/menu/menu-with-popper.tsx#L46 these examples are in the Menu component, but the same rules apply.
