### ISSUE TITLE
[Bug]: Full SSR support

### ISSUE THREAD

**Issue by desaintflorent** [tailwindlabs/headlessui#614]
### What package within Headless UI are you using?

 @headlessui/vue

### What version of that package are you using?

v1.2

### What browser are you using?

N/A

### Reproduction repository

None

### Describe your issue

Popover component is using "window" and thus SSR is not working.
I tried to use Popover with inertiajs + SSR and had the error : `ReferenceError: window is not defined`

Would it be possible to make it work with SSR ?

**Comment by thalesagapito** [comment]
This is not the only instance of this problem, Selects and Dialogs also rely on client-only properties.
While I don't think this is a bug, (because the Vue docs don't mention SSR at all) I believe the documentation should be clearer about SSR support.
Maybe a dedicated section in the docs explaining which components work and if there are any plans to improve SSR support in Vue.

**Comment by denis-ilchishin** [comment]
@thalesagapito 
> While I don't think this is a bug, (because the Vue docs don't mention SSR at all) I believe the documentation should be clearer about SSR support.

Quite misleading statement. Using `window` in nodejs env has nothing to do with Vue ssr docs. https://v3.vuejs.org/guide/ssr/universal.html this info more than enough to write univesal components

**Comment by AndrewBogdanovTSS** [comment]
Vue.js doc actually mentions SSR https://v3.vuejs.org/guide/ssr.html#the-complete-ssr-guide
I also don't think that window should be requested on the initial creation of most of these components.

**Comment by thalesagapito** [comment]
I'm sorry, I think I wasn't clear enough. I meant that the Headless UI Vue docs don't mention SSR. Which is why my suggestion was to add a dedicated section in the docs explaining this.

**Comment by AndrewBogdanovTSS** [comment]
@thalesagapito yeah, I thought you meant regular Vue docs. I agree that having the dedicated section on Headless UI would be great 👍🏻

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release. We used a `watchEffect` instead of immediately using `window.addEventListener` for the `useWindowEvent` hook.

You can already try it using:
- `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
- `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.

**Comment by morgan4080** [comment]
yarn add @headlessui/vue@dev package still has the same error

**Comment by henribru** [comment]
Just tested it myself and found the same thing. The `watchEffect` callback runs on the server, so it hasn't made a difference
