### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by keithn** [tailwindlabs/headlessui#637]
### What package within Headless UI are you using?

ListBox

### What version of that package are you using?

1.2.0

### What browser are you using?

edge

### Reproduction repository

screenshot should do the trick

### Describe your issue

more of a documentation / example styling issue,   the example isn't stackable so you end up with

![image](https://user-images.githubusercontent.com/86080/123013811-064e5580-d419-11eb-8313-cdd6416beeca.png)

where the dropdown box of other controls sit on top of a the dropped down list.

**Comment by adamwathan** [comment]
Hey thanks! Will consider updating the styles in the docs, but they aren't meant to be an example you copy and use anyways — Headless UI itself is about providing the underlying behaviors and you can style things however you want of course, so if you need to use some z-index stuff because you need them to stack on top of each other in a list that's totally cool but also just a user-land concern I think.

Either way I do appreciate the suggestion! ❤️  Going to close since no action to be taken in this actual codebase, thanks again though.
