### ISSUE TITLE
[Bug]: Overlay covering most of the dialog

### ISSUE THREAD

**Issue by mikecousins** [tailwindlabs/headlessui#685]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.3.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/suspicious-water-2tono?file=/src/App.tsx

### Describe your issue

I'm just using the code from the HeadlessUI documentation. The overlay seems to cover everything in the modal except elements that are relative.

Here's a sandbox: https://codesandbox.io/s/suspicious-water-2tono?file=/src/App.tsx

Any idea what's going wrong?

**Comment by mikecousins** [comment]
I fixed it by adding a `transform` class to the modal background element. I don't understand why it worked though. Might want to update the documentation with this?

**Comment by Ghirigoro** [comment]
@mikecousins It's not a bug in headless.ui, it's just how stacking contexts work (which is really unintuitive). Basically the headless.ui `Dialog` component creates its own stacking context (probably through setting the position property) which puts it "above" its siblings (which include the contents of your dialog). Setting a transform on your element fixed the issue because that creates a new stacking context for your element, and now that both siblings have their own stacking context we return to the "standard" ordering rules.

Stacking contexts are a real sore spot in css for lots of folks but here's a link that hopefully demystifies them a bit: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by mikecousins** [comment]
Thanks for the explanation on the root cause! The only "bug" I can see now is the styled example on the headless site should be updated so that it works properly.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed a stacking context issue as @Ghirigoro described.
I updated the docs on Headless UI, I added a `relative` class to get the expected result.
