### ISSUE TITLE
[Bug]: Disabling enter key behaviour on switch component

### ISSUE THREAD

**Issue by tankvt** [tailwindlabs/headlessui#688]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.3.0

### What browser are you using?

Edge, Chrome

### Reproduction repository

https://github.com/tailwindlabs/headlessui

### Describe your issue

Hi there,

Because the ticket https://github.com/tailwindlabs/headlessui/issues/144 was closed so I create the new ticket for this issue.
This maybe duplicate with the issue https://github.com/tailwindlabs/headlessui/issues/144 and @RobinMalfait has fixed but this still happen for the latest version.

Thanks,

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you go to https://headlessui.dev/react/switch or https://headlessui.dev/vue/switch, focus the Switch and press `Enter` you will notice that nothing happens (expected behaviour, only `space` triggers a toggle).
I've tested this in Safari, Firefox and Brave.

If you think this is an actual bug, please open a new issue with an actual minimal reproduction repo that showcases the issue you are seeing.

**Comment by montanaflynn** [comment]
Should it toggle a selected switch on enter? I see space works, but is that the expected behavior, and would users know to try that?
