### ISSUE TITLE
[Bug]: Dialog - Escape doesn't work after focus

### ISSUE THREAD

**Issue by VincentVanclef** [tailwindlabs/headlessui#693]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.3.0

### What browser are you using?

Chrome

### Reproduce url

You can see the issue in the demo: https://headlessui.dev/vue/dialog

As soon as you click anywhere inside the dialog, escape no longer closes it

### Describe your issue

After a modal is openeed, and you click somewhere on it, you can no longer trigger the Escape event - is this intentional? 

I can close it fine with Escape UNTIL i interact with the modal, then its like the event is no longer fired.

**Comment by itsthekeming** [comment]
I'm encountering this same behavior when trying to disable the "click outside" behavior detailed in #621. It seems that the escape handler does not work if the currently focused element is not inside of the modal. In my case, `body` is focused when I click outside now. I also tested clicking somewhere inside my modal that was *not* a focusable element and it focused `body` as well (this is more like your example).

What I'm unsure is if this is intentional behavior. The [docs](https://headlessui.dev/react/dialog#keyboard-interaction) just say that pressing `Esc` "closes any open Dialogs," which says nothing about focus. [Here](https://github.com/tailwindlabs/headlessui/blob/b961a189d57fa24af2a0bd0a6d73fa44e1d34529/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L286) is where that `onKeyDown` handler that handles `Esc` is being declared, but I don't know much about the Headless internals. It seems that the handler is only being registered on the dialog itself and not on the window?

**Comment by RobinMalfait** [comment]
This should be fixed, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@dev` or `yarn add @headlessui/react@dev`.
- `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.
