### ISSUE TITLE
[Bug]: Vue3 click-away package not working on dialogs.

### ISSUE THREAD

**Issue by bastilavarias** [tailwindlabs/headlessui#721]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.3.0

### What browser are you using?

Chrome

### Reproduction repository

none

### Describe your issue

I also tried the vanilla js implementation of the click away function but it's not working on dialogs.

This is the package is use [https://www.npmjs.com/package/vue3-click-away](url)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `Dialog` component already includes a "click away" feature built-in.
For example, when you go to this page https://headlessui.dev/vue/dialog you will notice that the `Dialog` pops up. If you click outside of the `Dialog`, then it closes automatically.

I am not 100% sure what your goals / issues are. If this doesn't work as expected, please open a new issue with the issues you are facing, a minimal reproduction repo and your expected behaviour.
