### ISSUE TITLE
[Bug]: Listbox's List gets cut off when it's container isn't high enough

### ISSUE THREAD

**Issue by marijnyoast** [tailwindlabs/headlessui#726]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://youtu.be/eN8eQwqvQ5Y

### Describe your issue

The Listbox component relies on `position: absolute` and by doing so it doesn't make the container where in it's wrapped grow. This causes the list to be cut-off. So it should either make the wrapper grow, overflow it, or open to above instead of below.

example:

<img width="961" alt="Screenshot 2021-08-10 at 16 17 59" src="https://user-images.githubusercontent.com/69148430/128883479-cbef08ef-e61e-4cf8-9f30-79321915efe9.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I would recommend you to use a Portal, you can use the built-in `Portal` component that Headless UI exposes. You can then use https://popper.js.org/ to position it correctly.
The Portal will ensure that the actual contents is rendered in the root of the `document.body`, which moves it out of the current parent container that has the `overflow-hidden` on it. Popper will then position it correctly.

If you need inspiration for this, then you can checkout this: https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-react/pages/menu/menu-with-popper.tsx
This example uses the `Menu` component, but the idea is exactly the same.

---

Going to close this since the styling is up to the user.

**Comment by prestonholt** [comment]
For anyone searching, here is a Listbox example using a portal & Popper in Vue:

https://codesandbox.io/s/tailwind-listbox-select-custom-9xe0c?file=/src/components/SelectSimpleCustom.vue

I was able to get the dropdown to match the width of the trigger button using a Popper modifier.
