### ISSUE TITLE
[Bug]: CSS var values declared in global.sass are unavailable to Dialog component

### ISSUE THREAD

**Issue by j-sup** [tailwindlabs/headlessui#745]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.0

### What browser are you using?

Chrome, Brave

### Reproduction repository

https://www.youtube.com/watch?v=6bToUnlX4ns

### Describe your issue

`MyComponent` uses a Sass module in `Dialog.Overlay` class.  I expect the background color of the `Overlay` to change according the theme set at a higher-level parent component.  However, the outcome is that `Overlay` is transparent.  Inspection with Chrome dev tools reveals that the var, `--theme-app-main-background`, never resolves to either red or blue.

### global.sass
```
.app
  &.light
    --theme-app-main-background: #red
  &.dark
    --theme-app-main-background: #blue
```

### MyComponent.tsx
```
import { Dialog, Transition } from “@headlessui/react”;
import styles from “@/styles/main-nav.module.sass”;
const MobileMenu = ({
  mobileMenuOpen,
  setMobileMenuOpen,
}) => {
  return (
    <>
      <Transition.Root show={mobileMenuOpen} as={Fragment}>
        <Dialog
          as=“div”
          static
          className=“fixed inset-0 z-40"
          open={mobileMenuOpen}
          onClose={setMobileMenuOpen}
        >
          <Transition.Child
            as={Fragment}
            enter=“transition-opacity ease-linear duration-300”
            enterFrom=“opacity-0"
            enterTo=“opacity-100”
            leave=“transition-opacity ease-linear duration-300"
            leaveFrom=“opacity-100”
            leaveTo=“opacity-0"
          >
            <Dialog.Overlay
              className={`hidden sm:block sm:inset-0 sm:fixed sm:bg-opacity-75 ${styles.thisIsWhereCssVarsDontWork}`}
            />
          </Transition.Child>
          <Transition.Child
            as={Fragment}
            enter=“transition ease-out duration-150 sm:ease-in-out sm:duration-300”
            enterFrom=“transform opacity-0 scale-110 sm:-translate-x-full sm:scale-100 sm:opacity-100"
            enterTo=“transform opacity-100 scale-100  sm:-translate-x-0 sm:scale-100 sm:opacity-100”
            leave=“transition ease-in duration-150 sm:ease-in-out sm:duration-300"
            leaveFrom=“transform opacity-100 scale-100 sm:-translate-x-0 sm:scale-100 sm:opacity-100”
            leaveTo=“transform opacity-0 scale-110 sm:-translate-x-full sm:scale-100 sm:opacity-100"
          >
            <nav
              className={`stufffffff`}
              aria-label=“Global”
            >
              <MobileMenuTopBar setMobileMenuOpen={setMobileMenuOpen} />
              <NavList />
            </nav>
          </Transition.Child>
        </Dialog>
      </Transition.Root>
    </>
  );
};
```
### @/styles/main-nav.module.sass
```
.thisIsWhereCssVarsDontWork
  background-color: var(--theme-app-main-background)
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI itself doesn't render anything so that part is up to you.
I would recommend you to see if you can get the styles in the browser without using Headless UI first (maybe put the classes directly on a div to test). Once you figure that out, it should be usable with Headless UI without any issues.

Note that our components only want classNames, so if your `styles.thisIsWhereCssVarsDontWork` don't generate a className but a styles object instead, then it won't work. 

Another issue I see is this part:
```css
--theme-app-main-background: #red
```

I have no idea if you have plugins that resolve this, but `#red` is not a valid color. Either use `red` or `#f00`.

Since you didn't provide a minimal reproduction repo, I can't reproduce it and can't help you further.
If you are sure this is an issue with Headless UI, please create a minimal reproduction repo and open a new issue.
