### ISSUE TITLE
[Bug]: `initialFocus` with Modal does not work with Vue Options API

### ISSUE THREAD

**Issue by Cherry** [tailwindlabs/headlessui#755]
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.4.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/headlessui-modal-initialfocus-options-fr3nc?file=/src/App.vue

### Describe your issue

When using the `initialFocus` property with `Modal`, this doesn't seem to work when using the Vue Options API as per https://codesandbox.io/s/headlessui-modal-initialfocus-options-fr3nc?file=/src/App.vue

The expected behaviour would be for the text box under the "get started" button in the modal to be the initial focus. 

When using the Composition API at https://codesandbox.io/s/headlessui-modal-initialfocus-composition-9ysh0?file=/src/App.vue, this works without issue. When using the options API though, it does not.

(Example forked from https://github.com/tailwindlabs/headlessui/issues/390).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because the `initialFocus` value will be passed as `null`. The docs say that this _will_ be the case and that the ref will only be available once it rendered at least once.

That said, even if we have code like this:
```js
    onMounted(() => {
      console.log(props)

      onUpdated(() => {
        console.log(props)
      })
    })
```

The `props.initialFocus` will always be `null`, even if we waited for the initial render.
I would recommend to use an actual `ref()` instead. More info about this: https://headlessui.dev/vue/dialog#managing-focus-within-your-dialog

**Comment by Cherry** [comment]
This doesn't really impact us anymore since we've moved over to the Composition API, but as far as I know with the older Options API, it's not recommended to use things like `ref()`, and instead use the older Options syntax.

I don't believe Headless UI provide any examples using the older Vue Options API, so perhaps it's just something that's not supported and should be noted as such?
