### ISSUE TITLE
[Bug]: Dialog adds padding-right to the HTML

### ISSUE THREAD

**Issue by maximegheraille** [tailwindlabs/headlessui#762]
### What package within Headless UI are you using?

1.4.0

### What version of that package are you using?

1.4.0

### What browser are you using?

chrome

### Reproduction repository

none

### Describe your issue

Hi,

when using this [example ](https://tailwindui.com/preview)(_Simple with gray footer_) in my own project it adds a weird padding-right: 17px to my HTML when to dialog is open.

![image](https://user-images.githubusercontent.com/32335849/130802978-2999cbe6-3574-4a8e-88ae-5fb32d4cae17.png)

I do not thins it is a normal behavior for the component because it adds padding-right to all my fixed elements (nav, footer).

Is there a way of removing those 2 added elements when opening the dialog ?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `padding-right` is added when the `Dialog` is open to account for the scrollbar. One of the features of the Dialog component is that it will block interaction with information behind the Dialog. Scrolling is also an interaction, so we disable that by adding `overflow: hidden;`. However, if you are on a page that had a scrollbar on the `html` already, then you would see a jump because `overflow: hidden;` will get rid of scrollbars. To account for that we add the `padding-right`.

There is no option to remove this behaviour currently. But I believe that something else is the issue here.
If this is still an issue for you, can you create a new issue with a minimal reproduction repo that showcases the issue?

**Comment by willishq** [comment]
If the page doesn't have a scrollbar, the padding still gets added to the page, which causes all of the page content to shift left.

Is there a way of detecting the content height and window height of the page, or if a scrollbar is currently showing, before adding the padding?

The only way around it I can think of is to set

```css
html {
    overflow-y: scroll;
}
```

which seems like a bad idea, although it would allow for consistency across pages which scroll and don't, though.

**Comment by perdanafm** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> The `padding-right` is added when the `Dialog` is open to account for the scrollbar. One of the features of the Dialog component is that it will block interaction with information behind the Dialog. Scrolling is also an interaction, so we disable that by adding `overflow: hidden;`. However, if you are on a page that had a scrollbar on the `html` already, then you would see a jump because `overflow: hidden;` will get rid of scrollbars. To account for that we add the `padding-right`.
> 
> There is no option to remove this behaviour currently. But I believe that something else is the issue here. If this is still an issue for you, can you create a new issue with a minimal reproduction repo that showcases the issue?

Hi, this is a very informatif reply , thankyou.

Anyway, i had an issue with this behaviour, when iam using a multiple dialog (not nested) when i open the 1st dialog, and close it, it is normal (the overflow hidden and padding is removed after its closed) but when i do transition from 1st dialog to 2nd dialog, there's a bug on it, (the overflow hidden and padding is removed and not coming back after the 2nd dialog is shown)

and when i close the 2nd dialog its getting weirder, because the overflow and padding is shown again

**Comment by rub1e** [comment]
@perdanafm I'm having this exact same issue! Did you have any success fixing this?

I'm working on it now, if I figure it out I'll update this comment.

**Comment by dev-tin** [comment]
One workaround for this, is to set document.documentElement.style.paddingRight = '0' e.g. in useEffect hook in react

**Comment by jaredloson** [comment]
I ran into this recently, but it was adding a very large and unsightly `padding-right: 165px`. Saw it on Chrome and Mobile Safari. For now, just overriding HTML padding-right with CSS. Would like to be able to disable this functionality.

**Comment by Naddiseo** [comment]
One way I found around this issue is to use the `scrollbar-gutter: stable` property. Reading up on [its history](https://github.com/w3c/csswg-drafts/issues/92) it's raison d'etre is to prevent the screen jank that occurs with things like the dialog. Unfortunately, safari doesn't support it yet so I've also had to fallback to using `overflow-y`. What seems to work from my limited testing is the following:
```css
/* apply to both html and body tags because different browsers use one or the other for the "scrollable element"*/
@supports (scrollbar-gutter: stable) {
  html,
  body {
    scrollbar-gutter: stable;
  }
}
/* For safari, which does support "@supports" */
@supports not (scrollbar-gutter: stable) {
  html,
  body {
    overflow-y: scroll;
  }
 }
```

**Comment by IronHeart0225** [comment]
I also have same problem when using Transition. If I open slideover using <Transition.Root>, the <html> tag has padding-right: 17px which is covering scroll bar, but in mobile view, the content under the slideover have minor jumps up or down.
I didnt mainly solved the problem but use following css to fix it temporally
html {
  padding-right: 0 !important;
}

**Comment by jvcss** [comment]
for those who came here because are following a tutorial, the quick workaround for this issue for mobile dimentions. if there is any suggestion to literally remove any inline style in the <html> tag I will appretiate it

```js
const [open, setOpen] = useState(false);

const onOpen = () => setOpen(true);

useEffect(() => {
    if (open) {
        document.documentElement.style.paddingRight = "0px";
    } else {
        document.documentElement.style.paddingRight = "0px";
    }
    // Clean up the style when the component unmounts
    return () => {
        document.documentElement.style.paddingRight = "0px";
    };
}, [open]);
```

**Comment by Ishaan28malik** [comment]
This worked for me 

```
html {
  font-family: "Helvetica Neue" !important;
  padding-right: 0px !important;
}
```

**Comment by luism6n** [comment]
I had the dropdown on a header. While closed, it was the right width to allow for scrollbar. When open, it would remove the scrollbar but the page would remain the same witdth, resulting in a dropdown that was larger than the header.

![Screenshot from 2024-05-17 18-43-14](https://github.com/tailwindlabs/headlessui/assets/35996614/2713f1b6-0b3e-49bb-9cc6-8f84638475f9)

![Screenshot from 2024-05-17 18-43-10](https://github.com/tailwindlabs/headlessui/assets/35996614/5d50f123-5cc9-4058-a970-2f34496ef2b5)

I fixed it mixing some of the anwers here:

```css
html {
  padding-right: 0 !important;
  overflow-y: scroll !important;
}
```

**Comment by joebartels** [comment]
The problem for me is that it adds `overflow: hidden; padding-right: 15px;` even when there is no scrollbar on the html... so, it causes a shift by trying to avoid causing a shift 🤣

**Comment by rhayes2** [comment]
I've moved away from this package because of this. Theres so many examples that just don't fit in to projects due to this behavior

**Comment by augustl** [comment]
This applies to comboboxes as well, at least in Firefox. For some reason, it only happens the second time I open a combobox that is relatively tall. For smaller comboboxes, it never happens.

**Comment by alexblack** [comment]
Is there a fix for this? I am using `With secondary text` from https://tailwindui.com/components/application-ui/forms/select-menus, and when the dropdown opens I see a 15px gap on the right of the window, pushing our page's scrollbar to the left, causing visible jank

**Comment by ArturSha** [comment]
`  html {
    padding: 0 !important;
    scrollbar-gutter: stable
  }`
here is my solution

**Comment by techking11** [comment]
used mui and tailwind in react pj and then got the same errror. fixed like this

`body {
  padding-right: 0 !important;
  overflow-y: scroll !important;
}`

**Comment by Tchilly** [comment]
Can this please be re-opened and just let this be a boolean of sorts on the component? It's 2025 and still, some edge cases need this fix  @RobinMalfait 

`html {
      padding: 0 !important;
      scrollbar-gutter: stable;
  }`

**Comment by JackScorpio** [comment]
Same issue here.
Have a chatBot project wrapped in a shadow DOM. When using the Dialog within the shadowDOM, consuming application html will be added style="padding-right: 14px; overflow: hidden;" causing entire chatBot move to right, overlap on top of the parent's scroll bar. When close the dialog, the chatBot move to left, besides the scrollbar. 
In my case, i can't access to the consuming application's html tag, can we have a fix on this?

**Comment by dmoughabghab** [comment]
html {
  overflow-y: auto !important;
  padding-right: 0px !important;
}

was what i did, so the scroll bar just stays where how it was before when the menu is open and then no padding change is needed

**Comment by dimas-fahmi** [comment]
In my case the issue is caused by redundant layout shift prevention both from the component and our application. 

The component added a padding-right to prevent layout shift because it uses `"overflow:hidden"` to block scrolling interaction when the dialog is open. This caused the browser to hide the scrollbar, which cause the rest of the app to shift to the right. The dialog prevents the shift layout by adding that padding, with the same width as our scrollbar.

The problem is, the previous developer already handles that layout shift with `"scrollbar-gutter:stable"`, which told the browser to preserve the scrollbar place even when it's not needed. So, when we added the component the effects double up. The scrollbar place is preserved but the application still adds that padding right, causing a layout shift to the left.

Our solution right now is to remove the `scrollbar-gutter` from our html/body, let the component handle the layout shift prevention as there is no clean way to disable this behavior from the component right now. It does fix the problem, tho we're still looking for side effects of doing that.

But adding `overflow: auto` is not a solution for us, as it allows the user to scroll when the dialog open. So, we'll stick with it for now.

Anyway, using padding-right is not really a good idea right now, as scrollbar-gutter already have a baseline since 2024. Every major browser already supports `scrollbar-gutter`.
