### ISSUE TITLE
[Bug]: defaultOpen prop for Disclosure not overriding internal open value

### ISSUE THREAD

**Issue by LorienOlive** [tailwindlabs/headlessui#770]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.0

### What browser are you using?

Chrome

### Reproduction repository

see code example below

### Describe your issue

The new defaultOpen prop is not working.  It is being passed through and set properly in the Disclosure component, but is not successfully overriding the internal value for Open.  Here's how I have it set up.  onLoad and active are props being passed to the wrapper component I've created.  

Not sure if it's something I'm doing wrong, or if others have had the same issue.

```
<Disclosure defaultOpen={onLoad && active} >
                {({ open }) => (
                        <div onClick={() => handleClick(onLoad ? true : open, name, onLoad)}>
                            <Disclosure.Button>
                                <span>{title}</span>
                                <span>
                                    <span>{selection}</span>
                                    <ChevronRightIcon open={open} />
                                </span>
                            </Disclosure.Button>

                            <Transition
                                show={open}
                                enter="transition duration-100 ease-out"
                                enterFrom="transform scale-95 opacity-0"
                                enterTo="transform scale-100 opacity-100"
                                leave="transition duration-75 ease-out"
                                leaveFrom="transform scale-100 opacity-100"
                                leaveTo="transform scale-95 opacity-0"
                            >
                                <Disclosure.Panel >{children}</Disclosure.Panel>

                            </Transition>
                        </div>
                    )
                }
            </ Disclosure>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `defaultOpen` prop is only used initially. This means that if `onLoad` or `active` changes, that the `defaultOpen` is not taken into account anymore.
One thing you can check is, add a `console.log(onLoad && active)` and the first value you will see in the console will be the one used for the `defaultOpen`.

We currently don't have a way to control the `Disclosure` component. However, you can _cheat_ by adding a `key` prop. Whenever the `key` prop changes, then the component will re-mount from scratch, taking the `defaultOpen` into account again.

**Comment by m1ky91** [comment]
@RobinMalfait you really closed this with the classic of the React workaround as a response? Re-mounting everything for a little feature? I think the Disclosure components need something to programmatically open/close them. It could be really helpful for the classic "Expand all" case as you can read [here](https://github.com/tailwindlabs/headlessui/discussions/589) too

**Comment by RobinMalfait** [comment]
@m1ky91 I did because the original issue was regarding the `defaultOpen` prop not being in sync, this is because the `defaultOpen` prop is only taken into account initially. Very similar to how it works with `defaultValue` on inputs. The first part about my response talks about that.

The issue you are describing is a totally different scope / issue than the original message, hence why I closed it.

**Comment by m1ky91** [comment]
@RobinMalfait the general issue is that there is no way to control the open status programmatically. The user is trying to achieve it playing with the `defaultOpen`. That's not right of course. But after explaining why it's not the right way to achieve the wanted result, you should give solutions, not workaround. If it's something WIP you should give at least ETA. Thanks

**Comment by RobinMalfait** [comment]
> the general issue is that there is no way to control the open status programmatically
Correct, but again that is not what the initial issue is about. As you pointed out yourself, there is already a discussion on the topic: https://github.com/tailwindlabs/headlessui/discussions/589.

I also mentioned "We currently don't have a way to control the `Disclosure` component." (aka, we currently don't have a solution for this specific problem, apart from the workaround).
I can't give an ETA since we didn't start working on this feature yet.

Going to lock this issue for now, since there is no point in arguing about this.
