### ISSUE TITLE
[Bug]: <FocusTrap /> does not recognize <Tab />s as focusable elements on first mount

### ISSUE THREAD

**Issue by LoganDark** [tailwindlabs/headlessui#771]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.0

### What browser are you using?

N/A

### Reproduction repository

N/A

### Describe your issue

When I have a dialog containing Tabs (as in, a TabGroup containing a TabList containing multiple Tabs), the FocusTrap still throws a fit because it thinks the tabs don't exist. This could be because the logic is weird, or maybe on first mount the TabGroup/TabList/Tabs don't actually render for whatever reason? Still, it's a bit weird.

**Comment by AndysonDK** [comment]
What you basically need to do now is the following:
https://github.com/tailwindlabs/headlessui/issues/265#issuecomment-880055784
I consider that a workaround not a proper solution, so you should probably still keep this issue open

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1231, and will be available in the next release.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
