### ISSUE TITLE
[Bug]: Clicking elements above Dialogs closes dialog

### ISSUE THREAD

**Issue by syropian** [tailwindlabs/headlessui#780]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.0

### What browser are you using?

Chrome

### Reproduction repository

n/a

### Describe your issue

Scenario: We have a HeadlessUI `Dialog` with a button that triggers some type of action. After this action happens we show a toast (custom component we built) saying their action was successful. The toast has its own close button to hide it, but when it's clicked, the entire dialog closes as well, which is undesirable in our case. I'm aware you can nest multiple `Dialog` components, but what about non-Dialog components that float above the Dialog? Is there a way to stop the Dialog from closing in this case?

**Comment by syropian** [comment]
Ha, just saw someone filed a PR for this! #768

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You can import the `Portal` component from Headless UI, and wrap the Toast/notification into a Portal component. When a `Portal` component is used inside a `Dialog` then we will render the contents in the root of the `Dialog` instead of the root of the document.
