### ISSUE TITLE
[Bug]: Menu.Items not forwarding ref

### ISSUE THREAD

**Issue by petercpwong** [tailwindlabs/headlessui#858]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/little-fog-bygcn

### Describe your issue

As demonstrated in the codesandbox above, the `ref` prop is not being forwarded to the container element in `Menu.Items`.

**Comment by brvnonascimento** [comment]
Same with `Tab.List` component

**Comment by jaredloson** [comment]
Are refs forwarded to any of the components? Running into the with `Tabs` as well.

**Comment by gchartier** [comment]
Any update on this? I'm also running into this with Menu.Items. Trying to use another component as the Menu.Items.

**Comment by petercpwong** [comment]
@RobinMalfait Sorry I accidentally deleted the codsandbox a while ago. It's back up now.

**Comment by RobinMalfait** [comment]
@petercpwong no worries, the ref is set correctly and also works in the example. The issue you are seeing is because a ref is an object with a `current` property and console.log calls are async. This means that the moment you click, we unmount the `Menu.Items` and once it flushes to the console it is set to `null` already.

If you use `console.log(containerRef.current)` instead then you _will_ see the actual DOM node being logged. However, if you right click in chrome on the logged value and click "Focus in elements panel" then you will notice that the DOM node is already gone, similar to what you saw with the initial `null` value.

**Comment by petercpwong** [comment]
@RobinMalfait You're right. Just updated the codesandbox and can confirm it works as expected. Thanks for looking into this.
