### ISSUE TITLE
Question about using active

### ISSUE THREAD

**Issue by CR1AT0RS** [tailwindlabs/headlessui#86]
Hey,

I am trying to use active on a button if active or not and changing the class dynamically. I am using classes as specified in TailWinds UI. 

```
 <nav className="hidden md:flex space-x-10">
          <div className="relative">
            {/* Item active: "text-gray-900", Item inactive: "text-gray-500" */}
            {({ active }) => (
              <button
                onClick={() => setIsOpen(!isOpen)}
                type="button"
                className={
                  (active ? 'group text-gray-900' : 'group text-gray-500') +
                  'inline-flex items-center space-x-2 '
                }
              >
                <span>Solutions</span>
                {/*
            Heroicon name: chevron-down

            Item active: "text-gray-600", Item inactive: "text-gray-400"
          */}
                <svg
                  className="text-gray-400 h-5 w-5 group-hover:text-gray-500 ..."
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                >
      
                </svg>
              </button>
            )}
```

Is active state check not supposed to work this way? Sorry I am a bit confused on how to use the active state.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You are using a callback in a random spot in the DOM.
I am not sure if you are talking about the Menu component or the Listbox component, but for both of them the same rules apply. You have to put the callback as a child of the `Menu, MenuButton, MenuItems or MenuItem` depending on what you what you want to style based on which information: 

- Example of active menu item: https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#styling-the-active-item

You can also have a look at the props table, look for the `Render prop object` because that is the object we expose for each render function:
- `Menu` https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#render-prop-object
- `Menu.Button` https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#render-prop-object-1
  Side note: For the button we are missing a `focused` prop in the docs, I'll add a PR to add this missing value.
- `Menu.Items` https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#render-prop-object-2
- `Menu.Item` https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#render-prop-object-3

---

For your actual question, what are you trying to do? Because the `active` we expose in `Menu.Item` means if that specific `Menu.Item` is active or not. A button in this case can't be "active". If you want to style it based on the `focused` prop then you can use a render function as mentioned above. If you want to style based on css states then you can look at the `active:...` tailwind variant. https://tailwindcss.com/docs/pseudo-class-variants#active
