### ISSUE TITLE
[Bug]: keydown events with wrapper doesn't work

### ISSUE THREAD

**Issue by yerlantemir** [tailwindlabs/headlessui#878]
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

chrome

### Reproduction repository

https://headlessui.dev/react/menu#rendering-a-different-element-for-a-component

### Describe your issue

[Here](https://headlessui.dev/react/menu#rendering-a-different-element-for-a-component) you have example _Rendering a different element for a component_ . If you copy-paste code from an example and try to use "Space" or "Enter" keywords on items, it won't work. If it's not a bug, I think it will be better to at least mention it on documentation.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed a documentation issue. With the example described the issue is that we render this:

```html
<ul>
  <li><a href="#">...</a></li>
  <li><a href="#">...</a></li>
  <li><a href="#">...</a></li>
</ul>
```

And the related `Menu.Item` props will now be put on the `li` instead of the `a`. Therefore pressing `enter` on the `li` won't invoke the normal action of the `<a>` tag.

If you really want to render a `ul` / `li`, then you can use a custom component like this:

```js
import { cloneElement, forwardRef } from "react";
import { Menu } from "@headlessui/react";

let CustomLi = forwardRef(({ children, ...rest }, ref) => {
  return <li>{cloneElement(children, { ...rest, ref })}</li>;
});


function MyDropdown() {
  return (
    /* Render a `div` instead of no wrapper element */
    <Menu as="div">
      <Menu.Button>More</Menu.Button>
      {/* Render a `ul` instead of a `div` */}
      <Menu.Items as="ul">
        {/* Render an `li` instead of no wrapper element */}
        <Menu.Item as={CustomLi}>
          {({ active }) => (
            <a
              className={`${active && "bg-blue-500"}`}
              href="#account-settings"
            >
              Account settings
            </a>
          )}
        </Menu.Item>

        {/* ... */}
      </Menu.Items>
    </Menu>
  );
}
```

What this will do is render an `li`, but instead of putting all the props on the `li`, it will put everything on the first child, in our case the `a` tag.

---

Will update the docs for this to use a better example.
