### ISSUE TITLE
Content behind modal flickers on page load when using Next

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/headlessui#963]
**What package within Headless UI are you using?**

@headlessui/react 1.4.2

**What version of that package are you using?**

1.4.2

**What browser are you using?**

Chrome 96.0.4664.55 (Official Build) (arm64)

**Reproduction URL**

https://github.com/agusterodin/headless-ui-modal-ssr-flicker-example

**Describe your issue**

I have a modal route in my application that uses Headless UI modal. When using NextJS, I notice that the contents behind the modal will show for a second before the modal actually appears on the screen. 

This leads to a jarring flicker. It is less apparent when trying my minimal reproduction out since rendering happens almost instantly on a basically empty project, but for large projects the contents behind the modal are shown for a longer time to the point where it is more obvious and janky.

To recreate: `yarn build` and `yarn start` the minimal reproduction. The error isn't present when using `yarn dev`. Is only present on built/compiled projects. As mentioned, it is a lot less obvious on the minimal reproduction but you will see the contents behind the modal (red background) by pressing CMD + R many times. Again, much more apparent in a project that has heavier render logic.

Here is a video of me recreating it: https://user-images.githubusercontent.com/10248395/143625820-eb3bc7ad-0a6f-4615-962d-195a7c91cba0.mov
 
My theory is that the NextJS calculated render doesn't contain the modal and that the modal appears AFTER hydrate, hence the delay.

Putting the overlay outside of the modal fixes the issue (you can verify this by uncommenting that line). Making the modal "static" doesn't fix the issue either.

**Comment by giliamverheide** [comment]
One more instance where I've noticed this issue occurring, is when the Dialog is used with a Transition, where the `Transition.Child` wrapper of the `Dialog.Overlay` is rendered as a `Fragment` with the structure below. Can be solved by opting out of using a Fragment for the transition around the overlay.

```json
"next": "11.1.2"
"@headlessui/react": "^1.4.2"
```

```js
<Transition show={isOpen} as={Fragment}>
  <Dialog as="div" className="fixed inset-0 z-10 overflow-y-auto" onClose={onClose}>
    <div className="min-h-screen px-4 text-center">
      <Transition.Child

        as={Fragment} // Removing this line fixes the flickering

        enter="ease-out duration-300"
        enterFrom="opacity-0"
        enterTo="opacity-100"
        leave="ease-in duration-200"
        leaveFrom="opacity-100"
        leaveTo="opacity-0"
      >
        <Dialog.Overlay className="fixed inset-0 bg-black opacity-30" />
      </Transition.Child>

      <Transition.Child
        as={Fragment}
        enter="ease-out duration-300"
        enterFrom="opacity-0 scale-95"
        enterTo="opacity-100 scale-100"
        leave="ease-in duration-200"
        leaveFrom="opacity-100 scale-100"
        leaveTo="opacity-0 scale-95"
      >
        <!-- Contents -->
      </Transition.Child>
    </div>
  </Dialog>
</Transition>
```

**Comment by divmgl** [comment]
This is still happening on `@headlessui/react@insiders`. I'm having the same effect in my Remix app.

This:
```
<Transition.Root show={open} as={Fragment}>
      <Dialog
        open={open}
        as="div"
        className="fixed inset-0 overflow-hidden"
        onClose={() => onClose()}
      >a
 ```

where `open` is `true` does not render the `Dialog` on the server. Looking at the source coming from the server shows that anything inside the dialog appears after hydration. You should reopen this issue (it's still happening). The solution is to not use `Dialog` at all in SSR.

**Comment by RobinMalfait** [comment]
@divmgl remove the open prop from the Dialog, it's inherited from the Transition above at the correctly timing.

If that doesn't work, please open a new issue with a minimal reproduction repo attached so that we can take a look.

**Comment by divmgl** [comment]
@RobinMalfait ok........ I don't think a repro case was necessary here but here it is. [git@github.com:divmgl/headlessui-bug.git](https://github.com/divmgl/headlessui-bug)

## Installation
1. Run:
```
npm i
npm run dev
```
1. Go to https://localhost:3000.

## Recreating the problem

Two ways of confirming this is happening:
 
* Right click on the page, click on View Source. You won't see the "hello" coming from the server.
or
1. Open the Chrome Devtools.
1. Go to the Network tab.
1. Click Throttling and set to Fast 3G.
1. Observe the screen go from Blue to Red instead of coming from the server as Red.

Here's a video.


https://user-images.githubusercontent.com/5452298/160526153-9264ba65-acc5-4cd9-ad11-141e48d67c83.mov

**Comment by divmgl** [comment]
Sorry, I didn’t read the bottom. Super busy at work.

The use case is a page route contained within the popover. Lever has a good
example of this (when you open a candidate from the list).

It works fine without the dialog, but I’ll need to bake in the input
functionality such as pressing escape or press on the overlay. Was hoping
maybe this was something Headless would support.

**Comment by divmgl** [comment]
I was just able to read through your comment thoroughly. If that's the case then I don't think this is worth spending too much time on. 

I see now that the whole point of a dialog accessibility component is that it's a popup that appears as a result of some kind of UI flow, like pressing a button. In this particular case, the slideover I was building was utilizing the dialog component because I was using the example provided by the Tailwind UI docs, but it's not necessarily applicable to my use case. This is an **actual page**, the only difference is that it appears on top of other UI elements.

The example that comes to mind is in Lever where you can view candidates based on a route, but even Lever doesn't do a great job of this because the page loads initially *and then* the slideover appears.

I think this is a super specific use-case and I can build for it without using `Dialog`.

As an aside, I think in general this design pattern for full-blown pages is slowly going out of fashion. I don't see very many sites using slideovers for pages anymore.

Thanks for your time @RobinMalfait.

**Comment by RobinMalfait** [comment]
@divmgl glad I could somehow help. If there is anything that pops up in the future, don't hesitate to open a Discussion or an Issue 👍

**Comment by agcty** [comment]
I also have this issue, it is definitely related to the Dialog component. In my case it flickers when there is a div that overflows. I'll work on a reproduction.

**Comment by MAfzalKhan1997** [comment]
any update on this ? I'm facing same.

**Comment by RobinMalfait** [comment]
Are these glitches happening on desktop or only on iOS? Because on iOS it is a bug. More info: https://github.com/tailwindlabs/headlessui/issues/2309#issuecomment-1450660821

If it is on desktop or another browser, please open a new issue with a minimal reproduction repo attached that shows the issue.
