### ISSUE TITLE
<FocusTrap /> does not work in foreign documents (i.e. new windows)

### ISSUE THREAD

**Issue by LoganDark** [tailwindlabs/headlessui#966]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.4.0

**What browser are you using?**

N/A

**Reproduction URL**

https://codesandbox.io/s/focus-trap-other-document-cme9d

Click the checkbox, press tab to confirm the focus trap works. Turn it off and open a new window. Try to use the focus trap inside that window.

**Describe your issue**

Trying to use `<FocusTrap />` in another document results in it throwing an error. This is because it uses the _global `document` object_ which is only valid for the document that Headless UI was loaded in.

Headless UI could instead check the document that the FocusTrap is contained in, and use that one instead - AKA, use the `ownerDocument` of the div.

**Comment by LoganDark** [comment]
Better late than never :)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1158, and will be available in the next release.
We now use the correct `ownerDocument` where we used to use `document` directly. We also use `ownerDocument.defaultView ?? window` instead of the `window` directly.

You can already try it using:
- `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.
- `npm install @headlessui/vue@insiders` or `yarn add @headlessui/vue@insiders`.
