### ISSUE TITLE
Can't pass disabled to Tab component when rendering as Fragment (TypeScript)

### ISSUE THREAD

**Issue by kendepelchin** [tailwindlabs/headlessui#972]
**What package within Headless UI are you using?**
`@headlessui/react`

**What version of that package are you using?**
`v1.4.2`

**What browser are you using?**
Chromium

**Reproduction URL**
https://codesandbox.io/s/competent-pasteur-27k63?file=/src/App.tsx

**Describe your issue**
When rendering <Tab /> components as Fragments (or any other component), when passing the `disabled` prop, TypeScript complains with the following error message:

```
Type '{ children: ({ selected }: TabRenderPropArg) => Element; as: ExoticComponent<{ children?: ReactNode; }>; disabled: boolean; }' is not assignable to type 'IntrinsicAttributes & Props<ExoticComponent<{ children?: ReactNode; }>, TabRenderPropArg, TabPropsWeControl>'.
  Property 'disabled' does not exist on type 'IntrinsicAttributes & Props<ExoticComponent<{ children?: ReactNode; }>, TabRenderPropArg, TabPropsWeControl>'.ts(2322)
(JSX attribute) disabled: boolean
```

**Note:** When I render the Tabs as fragments, the first one isn't automatically selected & active anymore. If I render it as "div", it is properly set as active.
Currently I can use ts-ignore and the prop is correctly passed through.

**Comment by aquaticone** [comment]
> Note:: When I render the Tabs as fragments, the first one isn't automatically selected & active anymore. If I render it as "div", it is properly set as active.

I'm experiencing a similar issue where I can't render a Tab as a custom component without it failing to properly set the first tab as active. Fragment and custom components have the same result here.

**Comment by enyelsequeira** [comment]
Have you made this work? I am trying to do something similar, but it does not work using the disabled, it doesn't actually disable the component ``<Tab
                as="div"
                disabled={true} >
some textt
</Tab>
``

**Comment by kendepelchin** [comment]
@enyelsequeira if you look at the production URL, I could only disable the <Tab> with `as={Fragment}. 

``` <Tab as={Fragment} disabled={true}>
            {({ selected }) => (
              <TabButton label={"Second!"} selected={selected}></TabButton>
            )}
          </Tab>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The reason that it doesn't work with `Fragment` itself is because when you use `Fragment`, then we forward all the props to the component you are rendering. In your case the `TabButton` component. You already passthrough the props which is good, the issue is that we don't have access to the `ref` (the actual DOM node), because React doesn't include this in the `props` variable. 

In fact, if you look at the console you will see this warning:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/1834413/155902066-3a6d9801-021e-4b5a-9d15-d22d32f76ef7.png">

If we fix the code to use `forwardRef`, and also use the `ref` on the button, then this works again: https://codesandbox.io/s/dreamy-bassi-0g3uwq?file=/src/App.tsx

Another issue was the `disabled` prop that is resulting in TypeScript errors. This isn't actually a prop on the Tab itself, what happens is that we render a `button` by default _and_ that we use the TypeScript definitions from the `button` component which happens to have a `disabled` prop. A `div` doesn't have a `disabled` prop, which is why you will get that TypeScript error.
Now, when we use the `as={Fragment}`, then we forward the props _at runtime_ to the first rendered child, which is something that (to my knowledge) we can't express in TypeScript, therefore we move the `disabled` prop to the `TabButton` itself.

Hope the changes made in the CodeSandbox (https://codesandbox.io/s/dreamy-bassi-0g3uwq?file=/src/App.tsx) make sense and work for your use case.
