### ISSUE TITLE
Can't style Dialog when prefixing tailwind classes with a selector

### ISSUE THREAD

**Issue by subeshb1** [tailwindlabs/headlessui#998]
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

1.4.2

**What browser are you using?**

Chrome

**Reproduction URL**

https://github.com/subeshb1/headless-ui-issue

**Describe your issue**

When prefixing tailwind classes with a selector in the configuration https://tailwindcss.com/docs/configuration#important,
```
{
 important: '#app'
}
```
the Dialog component doesn't get applied with styles since it's rendered via a portal i.e outside the specified selector. 

https://user-images.githubusercontent.com/27361350/147029378-e27430d2-6a23-490f-a2c3-40da8ae92b75.mov

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because the `Dialog` is rendered in a Portal as a child of the `document.body`. This means that the `#app` you have here: https://github.com/subeshb1/headless-ui-issue/blob/875a8fbe932484c89459576312b28f374cf2b954/pages/index.tsx#L8 will be a sibling of the Dialog content and not a child.

If possible, I would move the `#app` to the `<body>`.

**Comment by subeshb1** [comment]
@RobinMalfait Thank you for the response. 

It's too possible to move the styling to the body. 

We are using micro frontends, where each instance uses a different tailwind prefix to prevent class collision due to CSS precedence. 

A hack that I used was to add the `#app` to the Portal container itself.

**Comment by pfcodes** [comment]
I need this functionality as well. I'm exporting a package to be used in an existing project and the tailwind classes need to be scoped. Dialog not allowing me to use my own portal is causing issues.

**Comment by theomessin** [comment]
2 years since #666 and headlessui still doesn't support this basic functionality...
